### ISSUE TITLE
whether the transcriptomic data is must?

### ISSUE THREAD

**Issue by tiramisutes** [CompSynBioLab-KoreaUniv/FunGAP#1]
Hello,
Whether I can only used the PROTEIN DATABASE  for the 'homology-based' annotation? Because my study genome has does not sequence the RNA-seq data.
Thanks.

**Comment by choilab** [comment]
Hi there,

At the moment, FunGAP requires RNAseq data by default. We are developing various options but not yet plugged in the pipeline. You may try other _ab initio_ gene prediction programs (http://augustus.gobics.de/accuracy).

Best,
FunGAP team at CSBL
