### ISSUE TITLE
Name enforcing failure

### ISSUE THREAD

**Issue by jmonroynieto** [CompSynBioLab-KoreaUniv/FunGAP#12]
I ran Fungal's latest version with Cryptococcus H99 Data.
Genome and Proteome: GCF_000149245.1
RNA reads: SRR7288114
I renamed all files to H99.faa H99.fasta H99_s.fastq for the proteome, the genome, and the RNAseq respectively.

 The command that fails was:
`python miniconda/envs/fungap/bin/FunGAP/run_trinity.py --bam_files Tests/FunGAP/FEB_results/hisat2_out/H99.bam --output_dir Tests/FunGAP/FEB_results/trinity_out --log_dir Tests/FunGAP/FEB_results/logs --num_cores 16 --max_intron 2000 --jaccard_clip`

My Run fails when trinity looks for the BAM file that was created as _hisat2_out/H99.bam_ while the file is actually called _hisat2_out/H99_s.bam_

The error I get is` [ERROR] You provided wrong BAM FILES. Please check`

When providing just H99.fastq as a name so that this does not happen, the program enforces the _s notation by saying `TRANS_READ_SINGLE file name is incorrect. Should be <prefix>_s.fastq. You provided H99.fastq`.

Another error, which was lost to the upper limit of my terminal view, pointed me to the bamfile check on line 94 of in run_trynity.py. Running the glob() command on its own also fails because it is looking for a file that does not exist.

**Comment by mbnmbn00** [comment]
Yes. That's a bug. BAM file should be named `H99.bam` by `run_hisat2.py`.
I will fix it now.

You can simply rename `H99_s.bam` to `H99.bam` and re-launch the FunGAP.
It will recognize the bam file. In other words, you don't need to delete `hisat2_out` directory.
