### ISSUE TITLE
Post Failure python promt

### ISSUE THREAD

**Issue by jmonroynieto** [CompSynBioLab-KoreaUniv/FunGAP#13]
I am working on an issue when running Maker. If unable to solve will post an issue.

However, I've been noticing that after error failures I get into a python prompt which I am guessing means a variable containing the path to the next script in the pipeline is undefined.

**Comment by mbnmbn00** [comment]
Could you show me the error message? I will definitely help you solve that issue.

**Comment by jmonroynieto** [comment]
There is no error message for entering a python prompt after the pipeline fails. My previous post explains what my thoughts are on the mater. Decided to post since I suspect this will cause the pipeline to fail after the current hurdle is overcome.

If you are referring to the maker mater, I will post it gladly. Thank you for your help and quick support.

**Comment by mbnmbn00** [comment]
Currently, I have no idea about what happened. But let's see if fixing the Maker would make a difference.
