### ISSUE TITLE
failed to open ssi index

### ISSUE THREAD

**Issue by hpajot** [CompSynBioLab-KoreaUniv/FunGAP#15]
Hi, I am trying to install FunGAP, I installed all in my /home directory.
I managed to create the db directory inside FunGAP, downloaded and "gunziped" the pfam database and pfam.dat, however, when I execute hmmpress I keep getting the following:

(base) hpajot@hpajotpc /home/FunGAP/db/pfam $ hmmpress Pfam-A.hmm

Error: failed to open SSI index Pfam-A.hmm.h3i
(base) hpajot@hpajotpc /home/FunGAP/db/pfam $ hmmpress Pfam-A.hmm

I also tried it inside FunGAP:
(fungap) hpajot@hpajotpc /home/FunGAP/db/pfam $ hmmpress Pfam-A.hmm
failed to open SSI index Pfam-A.hmm.h3i

Could you tell what am I dooing wrong, please?

**Comment by mbnmbn00** [comment]
Which HMMER version did you sue?
Mine is v3.2.1 and just confirmed it works.

**Comment by hpajot** [comment]
Sorry, it was my mistake. I installed Hmmer in my root. I re-installed the complete package and it runs smoothly.
Thanks !

**Comment by mbnmbn00** [comment]
Sounds good! Let me know if there are further issues.
