### ISSUE TITLE
Maker issue

### ISSUE THREAD

**Issue by FengBang** [CompSynBioLab-KoreaUniv/FunGAP#18]
Hi, I am using the 1.01 version. Maker fails in the 4th runs. this is the error message:

[07-16 03:46] START training run3 & running maker run4
[Run] /home/austin/miniconda3/envs/fungap/bin/maker2zff -n /home/austin/Boletus_genome/annotation/BrMNGG/BrMNGG_annotation/maker_out/trans/maker_run3/pilon_polished.all.gff
[Run] /home/austin/miniconda3/envs/fungap/bin/fathom -categorize 1000 genome.ann genome.dna
[Run] /home/austin/miniconda3/envs/fungap/bin/fathom -export 1000 -plus uni.ann uni.dna
[Run] /home/austin/miniconda3/envs/fungap/bin/forge ../export.ann ../export.dna
[Run] /home/austin/miniconda3/envs/fungap/bin/hmm-assembler.pl snap_hmm_v3 parameters > snap_hmm_v3.hmm
Possible precedence issue with control flow operator at /home/austin/miniconda3/envs/fungap/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 845.
[Run] /home/austin/miniconda3/envs/fungap/bin/maker -fix_nucleotides > /home/austin/Boletus_genome/annotation/BrMNGG/BrMNGG_annotation/logs/maker/maker_trans_run4.log 2>&1
[07-16 03:53] DONE  training run3 & running maker run4
[Run] /home/austin/miniconda3/envs/fungap/bin/gff3_merge -g -n -d /home/austin/Boletus_genome/annotation/BrMNGG/BrMNGG_annotation/maker_out/trans/maker_run4/pilon_polished.maker.output/pilon_polished_master_datastore_index.log
[Run] /home/austin/miniconda3/envs/fungap/bin/fasta_merge -d /home/austin/Boletus_genome/annotation/BrMNGG/BrMNGG_annotation/maker_out/trans/maker_run4/pilon_polished.maker.output/pilon_polished_master_datastore_index.log
Traceback (most recent call last):
  File "/home/austin/FunGAP/run_maker.py", line 647, in <module>
    main(sys.argv[1:])
  File "/home/austin/FunGAP/run_maker.py", line 245, in main
    collect_result_final(input_fasta, output_dir, est_prefix)
  File "/home/austin/FunGAP/run_maker.py", line 556, in collect_result_final
    copyfile(merged_faa, output_faa)
  File "/home/austin/miniconda3/envs/fungap/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/austin/Boletus_genome/annotation/BrMNGG/BrMNGG_annotation/maker_out/trans/maker_run4/pilon_polished.all.maker.proteins.fasta'

I also checked the log file of the 4th run, and get the following message:

--Next Contig--

#---------------------------------------------------------------------
Now starting the contig!!
SeqID: Segkk0_pilon
Length: 429623
#---------------------------------------------------------------------

setting up GFF3 output and fasta chunks
doing repeat masking
collecting blastx repeatmasking
processing all repeats
in cluster::shadow_cluster...
...finished clustering.
doing repeat masking
collecting blastx repeatmasking
processing all repeats
in cluster::shadow_cluster...
...finished clustering.
doing repeat masking
collecting blastx repeatmasking
processing all repeats
in cluster::shadow_cluster...
...finished clustering.
doing repeat masking
collecting blastx repeatmasking
processing all repeats
in cluster::shadow_cluster...
...finished clustering.
preparing masked sequence
preparing ab-inits
running  snap.
#--------- command -------------#
Widget::snap:
/home/austin/miniconda3/envs/fungap/bin/snap /home/austin/Boletus_genome/annotation/BrMNGG/BrMNGG_annotation2/maker_out/trans/maker_run3/snp_training/snap_hmm_v3.hmm /tmp/maker_Z7qDJN/Segkk0_pilon.abinit_masked.0 > /tmp/maker_Z7qDJN/Segkk0_pilon.abinit_masked.0.snap_hmm_v3%2Ehmm.snap
#-------------------------------#
scoring....decoding.10.20.30.40.50.60.70.80.90.100 done
scoring....decoding.10.20.30.40.50.60.70.80.90.100 done
running  augustus.
#--------- command -------------#
Widget::augustus:
/home/austin/miniconda3/envs/fungap/bin/augustus --species=coprinus_cinereus --UTR=off /tmp/maker_Z7qDJN/Segkk0_pilon.abinit_masked.0 > /tmp/maker_Z7qDJN/Segkk0_pilon.abinit_masked.0.coprinus_cinereus.augustus
#-------------------------------#
Segmentation fault (core dumped)
Segmentation fault (core dumped)
ERROR: Augustus failed
--> rank=NA, hostname=austin-desktop
ERROR: Failed while preparing ab-inits
ERROR: Chunk failed at level:0, tier_type:2
FAILED CONTIG:Segkk0_pilon

ERROR: Chunk failed at level:4, tier_type:0
FAILED CONTIG:Segkk0_pilon

Any suggestions?
Thanks

**Comment by mbnmbn00** [comment]
I experienced this issue before.
What I did was to **re-install conda** dependencies with a new environment.
Note you may have to install at once, not one by one.

The thing is that I cannot see _py-boost_ package anymore from the _conda list_.
Also, you may have to use up-to-date conda by executing "conda update conda."

Since I couldn't reproduce the issue after it was fixed, I don't know what caused the problem.

To re-run the FunGAP, you can just delete the _maker_run4_ directory and run the command. FunGAP will recognize finished steps and save your time.

**Comment by FengBang** [comment]
Thanks for your suggestion. It seems that the issue was fixed.

**Comment by mbnmbn00** [comment]
Glad to hear that!
If you don't mind, could you click the 'star'..?
