### ISSUE TITLE
Maker run4 error

### ISSUE THREAD

**Issue by lmtani** [CompSynBioLab-KoreaUniv/FunGAP#19]
Hello! I have dedicated some hours trying to install this pipeline (that seems to be very complete).

Here some questions I had during the process:

- In https://github.com/CompSynBioLab-KoreaUniv/FunGAP/issues/14#issuecomment-470302228 other conda repos are pointed from those on wiki (https://github.com/CompSynBioLab-KoreaUniv/FunGAP/wiki#14-add-channels). I choose the comment config (with cf201901 hash)
- During GenMark instalation I choose to change the path using `change_path_in_perl_scripts.pl`.
- My GeneMark perl executable is in `$FUNGAP_DIR/external/gm_et_linux_64/` and not in `$FUNGAP_DIR/external/gm_et_linux_64/gmes_petap` as described on wiki.
- `sudo apt-get install build-essential` is required for others packages, not only for GeneMark

After following the wiki install doc I launched: 

```bash
python set_dependencies.py \
   --pfam_db_dir db/pfam \
   --busco_db_dir db/busco/basidiomycota_odb9/ \
   --genemark_dir external/gm_et_linux_64/ \
   --repeat_modeler_dir external/RepeatModeler-open-1.0.11

# and then
python /workspace/FunGAP/fungap.py \
    --output_dir fungap_out \
    --trans_read_1 sscita_1.fastq \
    --trans_read_2 sscita_2.fastq \
    --genome_assembly genome/pilon.fasta  \
    --augustus_species ustilago_maydis  \
    --sister_proteome sister_prot/prot_db.faa  \
    --num_cores 4
```

**note:** the parameters described in https://github.com/CompSynBioLab-KoreaUniv/FunGAP/wiki/Running-FunGAP#running-fungap do not work (--project_name, --org_id)

After a while fungap.py had an error running maker. It appears that conda does not install all its dependencies.

```
# maker error
Possible precedence issue with control flow operator at /opt/conda/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 845.
Can't locate object method "new" via package "Proc::ProcessTable" at /opt/conda/bin/../lib/Proc/ProcessTable_simple.pm line 23.
--> rank=NA, hostname=641b72f4ef74
Can't locate object method "new" via package "Proc::ProcessTable" at /opt/conda/bin/../lib/Proc/ProcessTable_simple.pm line 23.
--> rank=NA, hostname=641b72f4ef74
END failed--call queue aborted.
--> rank=NA, hostname=641b72f4ef74
```

I think it was fixed with `apt-get install -y postgresql postgresql-contrib`, but the apt command does not exit successfully... it installs fine only if it is executed before first `conda install`.

Then, again I executed fungap.py and it took several hours (hisat, trinity, maker) and then it stoped again. It seems similar to #5 .

Here are some outputs that could be useful:

```bash
Traceback (most recent call last):
  File "/workspace/FunGAP/run_maker.py", line 647, in <module>
    main(sys.argv[1:])
  File "/workspace/FunGAP/run_maker.py", line 245, in main
    collect_result_final(input_fasta, output_dir, est_prefix)
  File "/workspace/FunGAP/run_maker.py", line 556, in collect_result_final
    copyfile(merged_faa, output_faa)
  File "/opt/conda/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/work/fungap_out/maker_out/sscita/maker_run4/pilon.all.maker.proteins.fasta'
Traceback (most recent call last):
  File "/workspace/FunGAP/fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "/workspace/FunGAP/fungap.py", line 209, in main
    num_cores, repeat_model_file, trinity_asms, no_genemark_fungus
  File "/workspace/FunGAP/fungap.py", line 397, in run_maker
    check_call(command_args)
  File "/opt/conda/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/workspace/FunGAP/run_maker.py', '--input_fasta', '/work/genome/pilon.fasta', '--augustus_species', 'ustilago_maydis', '--protein_db_fasta', '/work/sister_prot/prot_db.faa', '--repeat_model', '/work/fungap_out/repeat_modeler_out/RM_9557.SatAug241525222019/consensi.fa.classified', '--est_files', '/work/fungap_out/trinity_out/trinity_sscita/Trinity_sscita.fasta', '--output_dir', '/work/fungap_out/maker_out', '--num_cores', '4', '--log_dir', '/work/fungap_out/logs', '--gmes_fungus']' returned non-zero exit status 1

# Verifying files
#------------------------
ls -lh fungap_out/maker_out/sscita/maker_*
-rw-r--r-- 1 root root   16 ago 25 09:13 fungap_out/maker_out/sscita/maker_sscita.gff3

fungap_out/maker_out/sscita/maker_run1:
total 55M
drwxr-xr-x 4 root root 4,0K ago 24 18:46 _Inline
-rw-r--r-- 1 root root 1,4K ago 24 18:46 maker_bopts.ctl
-rw-r--r-- 1 root root 1,2K ago 24 18:46 maker_exe.ctl
-rw-r--r-- 1 root root 3,8K ago 24 18:46 maker_opts.ctl
-rw-r--r-- 1 root root  55M ago 25 09:13 pilon.all.gff
drwxr-xr-x 4 root root 4,0K ago 24 21:21 pilon.maker.output
drwxr-xr-x 3 root root 4,0K ago 24 21:21 snp_training

fungap_out/maker_out/sscita/maker_run2:
total 58M
drwxr-xr-x 4 root root 4,0K ago 24 21:21 _Inline
-rw-r--r-- 1 root root 1,4K ago 24 21:21 maker_bopts.ctl
-rw-r--r-- 1 root root 1,2K ago 24 21:21 maker_exe.ctl
-rw-r--r-- 1 root root 3,8K ago 24 21:21 maker_opts.ctl
-rw-r--r-- 1 root root  58M ago 25 09:13 pilon.all.gff
drwxr-xr-x 4 root root 4,0K ago 24 21:43 pilon.maker.output
drwxr-xr-x 3 root root 4,0K ago 24 21:44 snp_training

fungap_out/maker_out/sscita/maker_run3:
total 58M
drwxr-xr-x 4 root root 4,0K ago 24 21:44 _Inline
-rw-r--r-- 1 root root 1,4K ago 24 21:44 maker_bopts.ctl
-rw-r--r-- 1 root root 1,2K ago 24 21:44 maker_exe.ctl
-rw-r--r-- 1 root root 3,8K ago 24 21:44 maker_opts.ctl
-rw-r--r-- 1 root root  58M ago 25 09:13 pilon.all.gff
drwxr-xr-x 4 root root 4,0K ago 24 22:06 pilon.maker.output
drwxr-xr-x 3 root root 4,0K ago 24 22:24 snp_training

fungap_out/maker_out/sscita/maker_run4:
total 872K
-rw------- 1 root root 218M ago 24 22:27 core
drwxr-xr-x 4 root root 4,0K ago 24 22:24 _Inline
-rw-r--r-- 1 root root 1,4K ago 25 09:13 maker_bopts.ctl
-rw-r--r-- 1 root root 1,2K ago 25 09:13 maker_exe.ctl
-rw-r--r-- 1 root root 3,8K ago 25 09:13 maker_opts.ctl
-rw-r--r-- 1 root root   16 ago 25 09:13 pilon.all.gff
drwxr-xr-x 4 root root 4,0K ago 25 09:13 pilon.maker.output

# Verifying log: fungap_out/logs/maker/maker_sscita_run4.log
#----------------------------------------------------------------------------
Possible precedence issue with control flow operator at /opt/conda/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 845.
STATUS: Parsing control files...
STATUS: Processing and indexing input FASTA files...
STATUS: Setting up database for any GFF3 input...
A data structure will be created for you at:
/work/fungap_out/maker_out/sscita/maker_run4/pilon.maker.output/pilon_datastore

To access files for individual sequences use the datastore index:
/work/fungap_out/maker_out/sscita/maker_run4/pilon.maker.output/pilon_master_datastore_index.log

STATUS: Now running MAKER...
examining contents of the fasta file and run log



--Next Contig--

Processing run.log file...
#---------------------------------------------------------------------
The contig failed 2 times!!
Maker will not try again!!
The contig will be stored in a fasta file that you can use for debugging.
SeqID: CP010913.1_pilon
Length: 2010175
FASTA: /work/fungap_out/maker_out/sscita/maker_run4/pilon.maker.output/pilon_datastore/04/F2/CP010913.1_pilon//CP010913%2E1_pilon.died.fasta
#---------------------------------------------------------------------

(lot of lines like this one)
```

Could anyone help me?

**Comment by mbnmbn00** [comment]
1) 
The latest installation and usage pages are here:
https://github.com/CompSynBioLab-KoreaUniv/FunGAP/blob/master/INSTALL.md
https://github.com/CompSynBioLab-KoreaUniv/FunGAP/blob/master/USAGE.md

Yes. I should have updated wiki, too. I will update very soon.

2)
Could you show me the more output of `fungap_out/logs/maker/maker_sscita_run4.log`?
Could you search for "error\c" where \c makes it ignore upper/lower cases.

It could be "Augustus" or "GeneMark" error because other three runs were fine.

3)
Could you show me the output of:

```
conda list
```

It should look like below. Note that all the channels end with `/label/cf201901`.

```
> conda list
# packages in environment at /home/mbnmbn00/anaconda2/envs/maker:
#
# Name                    Version                   Build  Channel
augustus                  3.3             pl526hcfae127_4    bioconda/label/cf201901
bamtools                  2.4.1                         1    bioconda/label/cf201901
binutils_impl_linux-64    2.28.1               had2808c_3  
binutils_linux-64         7.2.0               had2808c_27  
blas                      1.0                         mkl  
blast                     2.7.1                h4422958_6    bioconda/label/cf201901
boost                     1.67.0           py27h3e44d54_0    conda-forge/label/cf201901
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge/label/cf201901
bowtie                    1.2.2            py27h2d50403_1    bioconda/label/cf201901
bzip2                     1.0.6                h470a237_2    conda-forge/label/cf201901
ca-certificates           2018.11.29           ha4d7672_0    conda-forge/label/cf201901
cairo                     1.14.12              h276e583_5    conda-forge/label/cf201901
certifi                   2018.11.29            py27_1000    conda-forge/label/cf201901
clustalw                  2.1                  h2d50403_2    bioconda/label/cf201901
curl                      7.63.0               h74213dd_0    conda-forge/label/cf201901
exonerate                 2.4.0                         0    bioconda/label/cf201901
expat                     2.2.5                hfc679d8_2    conda-forge/label/cf201901
fontconfig                2.13.1               h65d0f4c_0    conda-forge/label/cf201901
freetype                  2.9.1                h6debe1e_4    conda-forge/label/cf201901
```

4) I got this error in Maker_run4 before. 

```
Widget::augustus:
/home/ubuntu/anaconda2/envs/fungap/bin/augustus --species=coprinus_cinereus --UTR=off /tmp/maker_gbofZM/GL377302%2E1.abinit_masked.0 > /tmp/maker_gbofZM/GL377302%2E1.abinit_masked.0.coprinus_cinereus.augustus
#-------------------------------#
Segmentation fault (core dumped)
Segmentation fault (core dumped)
ERROR: Augustus failed
--> rank=NA, hostname=ip-172-31-36-6
ERROR: Failed while preparing ab-inits
ERROR: Chunk failed at level:0, tier_type:2
FAILED CONTIG:GL377302.1

ERROR: Chunk failed at level:4, tier_type:0
FAILED CONTIG:GL377302.1
```
Here's my note to resolve this issue:

> I had to create new environment and put -c bioconda in the command.
> But I could not reproduce the problem anymore...... why...?
> The thing is i cannot see **py-boost package anymore from the conda list**
> Also I upgraded the conda by conda update conda
> But I really don't know what happened.

**Comment by mbnmbn00** [comment]
Hi,

I'm traveling now, but I found that it worked WITHOUT py-boost.

I will look into more and give detailed answer later today.

Byoungnam

**Comment by mbnmbn00** [comment]
I looked into the log files you sent, but maker_run4 looks fine?
```
$ tail maker_sscita_run4.log
```
_Maker is now finished!!!
Start_time: 1566735234
End_time:   1566735235
Elapsed:    1_

Can you tell me more about:
>I've tried today but had problems with samtools (something with libcrypto).

When I installed in fresh Ubuntu 18.04, I also had to install `build-essential`, but not `postgresql` and `postgresql-contrib`. Conda is supposed to take care of the module: `Proc::ProcessTable`. 

I may verify again in fresh Ubuntu again.

**Comment by lmtani** [comment]
Hi, thank you for the help.

All contigs failed during maker run4:

```
$ tail -n 20 logs/maker/maker_sscita_run4.log 
Processing run.log file...
#---------------------------------------------------------------------
The contig failed 2 times!!
Maker will not try again!!
The contig will be stored in a fasta file that you can use for debugging.
SeqID: CP010939.1_pilon
Length: 88018
FASTA: /work/fungap_out/maker_out/sscita/maker_run4/pilon.maker.output/pilon_datastore/A6/30/CP010939.1_pilon//CP010939%2E1_pilon.died.fasta
#---------------------------------------------------------------------

Maker is now finished!!!
Start_time: 1566735234
End_time:   1566735235
Elapsed:    1
```

To reproduce the failure I need to cd to `fungap_out/maker_out/sscita/maker_run4` and exec `/opt/conda/bin/maker -fix_nucleotides`.

About libcrypto... I was using an old version of miniconda. When I update it to 4.17.11 the problem with samtools was solved.

I've already tried:

- Execute the whole pipeline using a single thread (-c 1).
- Changed the `maker_opts.ctl` to tries=5, clean_try=1
- Got a docker image from docker hub with maker (lijingbu/maker2-annotation) and changed `maker_exe.ctl` to point to binaries in the image, and then executed `maker -fix_nucleotides`. Same error occurs.

I will retry fresh install using last version of miniconda without installing postgresql.

**Comment by mbnmbn00** [comment]
We could check several things:
1) Check if Augustus ran correctly.
2) Check if GMES ran correctly.
3) Check if `snap_hmm_v3.hmm` is empty.

Priority is in order.
Meanwhile, I will test the FunGAP myself.

**Comment by lmtani** [comment]
1. Augustus: found the error message you previously mentioned:

```
(...)
#--------- command -------------#
Widget::augustus:
/opt/conda/bin/augustus --species=ustilago_maydis --UTR=off /tmp/maker_EERLc9/chr1.abinit_masked.0 > /tmp/maker_EERLc9/chr1.abinit_masked.0.ustilago_maydis.augustus
#-------------------------------#
Segmentation fault (core dumped)
Segmentation fault (core dumped)
ERROR: Augustus failed
--> rank=NA, hostname=35986fd63cc8
ERROR: Failed while preparing ab-inits
ERROR: Chunk failed at level:0, tier_type:2
FAILED CONTIG:chr1

ERROR: Chunk failed at level:4, tier_type:0
FAILED CONTIG:chr1
(...)
```
[This is de conda env](https://storage.googleapis.com/misc-bioinformatics/env.txt) I ran the program.

My /tmp/ directory is almost empty and Py-boost is not listed in my conda env. 

In your note about this error mentioned:

> I had to create new environment and put -c bioconda in the command.

What did you ran? I've tried to ` conda create -n env2 -c bioconda maker` but FunGAP needs biopython, so I could not re-execute the pipeline. 

2. GMES seems to be ok. The log file (fungap_out/logs/maker/gmes.log) has 81 lines without any kind of warning message.

3. File fungap_out2/maker_out/sscita/maker_run3/snp_training/snap_hmm_v3.hmm has 45K.

**Comment by mbnmbn00** [comment]
I found that Augustus is the problem. When you type:
```
augustus --species=laccaria_bicolor <your_assembly_fasta>
```
You will get:
```
Segmentation fault
```

I could reproduce this problem by:
```
conda install maker trinity
```

Specifically I see `libboost                  1.67.0               h46d08c1_4` in `conda list` as in your conda environment.

I could run `augustus` by excluding `trinity` from the `conda install`. I.e.,
```
conda install augustus rmblast maker hisat2 braker busco blast pfam_scan
```

I don't see `libboost` from `conda list` anymore and Augustus ran fine.

Please try this and let me know!

I will update my installation step and also update some scripts (maybe this weekend).

**Comment by mbnmbn00** [comment]
What you have to do is:
1. Install Trinity manually
2. Add to the $PATH

**Comment by lmtani** [comment]
It worked now! Issue solved. Thank you.
