### ISSUE TITLE
cmake for Trinity

### ISSUE THREAD

**Issue by fungal-spore** [CompSynBioLab-KoreaUniv/FunGAP#23]
You need cmake installed for Trinity install, this should be added to install docs. Took me a while to figure out what the problem was, this will hopefully save someone else some time.

**Comment by mbnmbn00** [comment]
Thank you for the suggestion. Have you tried the "Docker" version of FunGAP?
I highly recommend it, especially when you didn't run FunGAP successfully yet.

But I will edit the doc right now. Thank you so much!

**Comment by fungal-spore** [comment]
I am working on hpc cluster, docker is apparently not an option at the moment.

**Comment by mbnmbn00** [comment]
I see. Please let me know if you need any help.
