### ISSUE TITLE
Augustus failed

### ISSUE THREAD

**Issue by fungal-spore** [CompSynBioLab-KoreaUniv/FunGAP#25]
Hello again,
During Maker run4, I checked log and see this type of message for all contigs (as far as I can tell):

Widget::augustus:
/home/miniconda3/envs/fungap/bin/augustus --species=botrytis_$
#-------------------------------#
sh: line 1: 162653 Segmentation fault      (core dumped) /home/$
sh: line 1: 162735 Segmentation fault      (core dumped) /home/$
ERROR: Augustus failed
--> rank=NA, hostname=biocomp-0-1.local
ERROR: Failed while preparing ab-inits
ERROR: Chunk failed at level:0, tier_type:2
FAILED CONTIG:contig00002

ERROR: Chunk failed at level:4, tier_type:0
FAILED CONTIG:contig00002

Any ideas why this is happening? I assume this will affect all processes downstream. MakerRun4 is still running, I did not kill. 
If I stop run, and troubleshoot issue, can I restart run and fungap will pickup where it left off? I'm not sure what intermediate files would need to be removed run4 starts over.
Thanks 

EDIT:
I am going through other log files and see contigs_master_datastore_index.log shows:
contig00001     contigs_datastore/2C/6A/contig00001/    STARTED
contig00001     contigs_datastore/2C/6A/contig00001/    FAILED
contig00002     contigs_datastore/E6/AC/contig00002/    STARTED
contig00002     contigs_datastore/E6/AC/contig00002/    FAILED
contig00003     contigs_datastore/B2/4E/contig00003/    STARTED
contig00003     contigs_datastore/B2/4E/contig00003/    FAILED
contig00004     contigs_datastore/EF/6B/contig00004/    STARTED
contig00004     contigs_datastore/EF/6B/contig00004/    FAILED
contig00005     contigs_datastore/F4/6B/contig00005/    STARTED
contig00005     contigs_datastore/F4/6B/contig00005/    FAILED
...

EDIT2:
in the contig_datastore dir, i navigated to one of the contigs (in this case 03870) and see in run.log:

<other stuff that looks like they were successful, they say FINISHED>
STARTED contigs.maker.output/contigs_datastore/00/2C/contig03870//theVoid.contig03870/contig03870.abinit_masked.0.botrytis_cinerea.augustus
DIED    RANK    0:4:0:0
DIED    COUNT   1
DIED    RANK    0
DIED    COUNT   1

**Comment by mbnmbn00** [comment]
That is a known bug.

Could you run Augustus (first few seconds) and see if it gives `Segmentation fault` or not?

If it is, Conda it the problem. Please see [this](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/issues/19#issuecomment-528597783).

Also, don't forget deleting `maker_run4` directory and run FunGAP again. It will recognize the last step and resume.

**Comment by fungal-spore** [comment]
Running augustus --species=laccaria_bicolor contigs.fa did indeed give segmentation fault.
I see libboost 1.67.0 h46d08c1_4 in conda list, how can I remove?
I did not install Trinity with conda, I installed manually it seemed to run ok, trinity log files look fine, so I assume it is already in $PATH.

**Comment by mbnmbn00** [comment]
You may create new conda environment (e.g., fungap2) and do
```
conda install augustus rmblast maker hisat2 braker busco blast pfam_scan
pip install biopython bcbio-gff networkx markdown2 matplotlib
cpanm Hash::Merge Logger::Simple Parallel::ForkManager YAML
```

You may check Augustus again before re-running. Good luck!!!

**Comment by fungal-spore** [comment]
It is looks like that has resolved issue, thanks for your help and quick response!

**Comment by mbnmbn00** [comment]
Good to hear that!
