### ISSUE TITLE
repeat-masking explanation

### ISSUE THREAD

**Issue by Caro-Ca** [CompSynBioLab-KoreaUniv/FunGAP#27]
Hey!
I want to perform an analysis based on the repeat-masked regions, but I don't understand the folders given. Could you explain it to me? 
By the way, thank you for your time.

**Comment by mbnmbn00** [comment]
FunGAP runs `RepeatModeler` and input `consensi.fa.classified` into Maker. Repeat-masking is done inside Maker. I recommend using `RepeatMasker` again with `consensi.fa.classified` for that purpose.

Example command:
```
'RepeatMasker \
  -xsmall \
  -dir repeat_masker_out \
  -s \
  -pa 10 \
  -lib consensi.fa.classified \
  <your_assembly_file>
```
where
     -xsmall          Returns repetitive regions in lowercase rather than masked
     -s                    Slow search;
