### ISSUE TITLE
Trinity Installation gives zlib.h missing error

### ISSUE THREAD

**Issue by ishanb42** [CompSynBioLab-KoreaUniv/FunGAP#28]
While trying to install Trinity, I consistently get:
fatal error: zlib.h: No such file or directory  #include <zlib.h>

I have installed zlib1g using sudo apt:get but continue to get the same error...

**Comment by mbnmbn00** [comment]
This would be helpful.
```
sudo apt-get install zlib1g-dev
```

If you are trying to install FunGAP for the first time, I strongly recommend using Docker.
https://gist.github.com/lmtani/d37343a40e143b59336e4606055d1723
