### ISSUE TITLE
Fungap_out nucleotide file?

### ISSUE THREAD

**Issue by fungal-spore** [CompSynBioLab-KoreaUniv/FunGAP#29]
Hi,
I have fungap running successfully, but I see that in the fungap_out directory gene calls are only in amino acid. Is there similar output in nucleotide? Would be very useful for downstream analysis.
Thanks!

**Comment by mbnmbn00** [comment]
Thank you for the suggestion!
In the code directory, there's a code `gff3_transcript.py` script.
Usage:
```
python3 $FUNGAP_DIR/gff3_transcript.py \
  -f <genome_assembly> \
  -g fungap_out.gff3
```

Note `out_transcript.fna` file contains CDS sequences while `out_gene.fna` file contains gene sequences including UTRs.

We will definitely consider generating these files as default in the next update.

**Comment by fungal-spore** [comment]
Thanks!
I got error:
File "gff3_transcript.py", line 41
    print 'ERROR: please provide INPUT FASTA'
                                            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('ERROR: please provide INPUT FASTA')?

I replaced all the parentheses in gff3_transcript print errors (-f, -g and -o were all missing) and it worked (though it doesn't have same detail in gene headers as the amino acid outputs). I also had to provide -o.

**Comment by mbnmbn00** [comment]
That is the issue of python2 and 3. Because conda installation forces us to install Python2, I wrote all the codes with Python2.
