### ISSUE TITLE
Problems with run_breaker1.py

### ISSUE THREAD

**Issue by reiverjohn** [CompSynBioLab-KoreaUniv/FunGAP#3]
Once we get to this step, we receive an error that augustus "cannot be executed on this machine".  Checking the paths, there does not seem to be a problem - AUGUSTUS_CONFIG_PATH is set and being picked up.

When we attempt to run the "breaker.pl" command directly which is generated by "run_breaker1.py" the step completes without error and an Augustus output directory is generated under config/species. So I think this error is misleading and is being caused by something else.

When running "run_breaker1.py" directly, we receive one other error which is (and I think this is the real problem): "list index out of range" that pertains to line 242 of the program.  Specifically the following code block:

            command2 = 'mv %s %s' % (
                glob(os.path.join(
                    output_dir, prefix, 'braker/*', 'augustus.gff3')
                )[0],
                os.path.join(
                    output_dir, prefix,
                    'braker1_%s.gff3' % (prefix)
                )

There is something it doesn't like about the index "[0]".

Do you have any insight on this?

**Comment by mbnmbn00** [comment]
Hi,

**Comment by mbnmbn00** [comment]
Hi,

Thanks for reporting this issue.
The error message says that you don't have the Braker1 output.
`glob()` function looks for Braker1 output (augustus.gff3) and FunGAP moves and renames it using `mv` command.

So you have to check it there is actually Braker1 output.
It should be located at 
`<output_dir>/<fastq_prefix>/braker/<fastq_prefix>/augustus.gff3`

- `<output_dir>` is the place where you set with --output_dir argument.
- `<fastq_prefix>` is the prefix of FASTQ files. That is <fastq_prefix>_1.fastq and <fastq_prefix>_2.fastq

Please also check the log file at
`logs/gpre_braker1` 
to see if Braker1 is successfully run.

Let me know if you have further problem! Thank you!

**Comment by reiverjohn** [comment]
We've gotten around this problem by running "run_braker.pl" directly, bypassing "run_braker.py". Once this step of the pipeline completes, we restart "fungap.py" and it proceeds normally on test data. There seems to be some issue with the calls between fungap.py and run_braker.py, or perhaps between run_braker.py and run_braker.pl.

**Comment by mbnmbn00** [comment]
After running `run_braker.pl`, FunGAP copy GFF3 and protein FASTA into `<output_dir>/gpre_braker1/`. We previously noticed that rerunning FunGAP without removing existing `gpre_braker1` directory causes a mess of output files and directories.

But it's good to hear that you anyway resolved the issue. We may improve our `run_braker.py` script to ensure deleting existing output directory.
