### ISSUE TITLE
Braker1 in Docker

### ISSUE THREAD

**Issue by hpajot** [CompSynBioLab-KoreaUniv/FunGAP#30]
Hi:
My name is Hipólito I am trying to run FunGAP in a docker container.
It seems to work properly but when it comes to run Bracker, i get this:

[12-01 12:11] START: wrapper_run_braker1
[Wrapper] python /workspace/FunGAP/run_braker1.py --masked_assembly /fungap_workspace/Triol1_anot/maker_out/masked_assembly.fasta --bam_files /fungap_workspace/Triol1_anot/hisat2_out/triol1_rna.bam --output_dir /fungap_workspace/Triol1_anot/braker1_out --log_dir /fungap_workspace/Triol1_anot/logs --num_cores 7 --fungus
[12-01 12:11] START: BRAKER1
[Run] /opt/conda/bin/braker.pl --fungus --softmasking --cores=7 --genome=/fungap_workspace/Triol1_anot/maker_out/masked_assembly.fasta --bam=/fungap_workspace/Triol1_anot/hisat2_out/triol1_rna.bam --species=triol1_rna --gff3 --AUGUSTUS_CONFIG_PATH=/opt/conda/bin/../config --BAMTOOLS_PATH=/opt/conda/bin --GENEMARK_PATH=/workspace/FunGAP/external/gm_et_linux_64 --SAMTOOLS_PATH=/opt/conda/bin --workingdir=/fungap_workspace/Triol1_anot/braker1_out/triol1_rna > /fungap_workspace/Triol1_anot/logs/braker1/braker1_triol1_rna.log 2>&1
Traceback (most recent call last):
  File "/workspace/FunGAP/run_braker1.py", line 197, in <module>
    main(sys.argv[1:])
  File "/workspace/FunGAP/run_braker1.py", line 91, in main
    masked_assembly, bam_files, output_dir, log_dir, num_cores, fungus_flag
  File "/workspace/FunGAP/run_braker1.py", line 171, in run_braker1
    )[0],
IndexError: list index out of range
Traceback (most recent call last):
  File "/workspace/FunGAP/fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "/workspace/FunGAP/fungap.py", line 223, in main
    masked_assembly, trans_bams, output_dir, num_cores, no_braker_fungus
  File "/workspace/FunGAP/fungap.py", line 446, in run_braker1
    check_call(command_args)
  File "/opt/conda/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/workspace/FunGAP/run_braker1.py', '--masked_assembly', '/fungap_workspace/Triol1_anot/maker_out/masked_assembly.fasta', '--bam_files', '/fungap_workspace/Triol1_anot/hisat2_out/triol1_rna.bam', '--output_dir', '/fungap_workspace/Triol1_anot/braker1_out', '--log_dir', '/fungap_workspace/Triol1_anot/logs', '--num_cores', '7', '--fungus']' returned non-zero exit status 1
(base) root@4c681b5d8b52:/fungap_workspace# 

I tryed to log myself into a docker group in order to avoid using "sudo" but it doesn work. 
Could you help me with this?

**Comment by mbnmbn00** [comment]
In most cases, Braker1 error is caused by the wrong RNA-seq file. For example,

- DNA-seq
- Wrong library of RNA-seq

I recommend checking read alignment using IGV.
Also, could you show me the content of 
```
/fungap_workspace/Triol1_anot/logs/braker1/braker1_triol1_rna.log
```
If the file size is large, you can upload the file.

Note when you re-run it, you can delete the `braker1_out` directory and run the same FunGAP command. It will recognize already finished steps.

**Comment by Tierprot** [comment]
Since i got issue with breaker too, i decided to write into this branch without opening new ticket:
/opt/conda/bin/braker.pl --fungus --softmasking --cores=5 --genome=/fungap_workspace/fungap_out_ganoderma/maker_out/masked_assembly.fasta --bam=/fungap_workspace/fungap_out_ganoderma/hisat2_out/SRR5261647.bam --species=SRR5261647_1 --gff3 --AUGUSTUS_CONFIG_PATH=/opt/conda/bin/../config --BAMTOOLS_PATH=/opt/conda/bin --GENEMARK_PATH=/workspace/FunGAP/external/gm_et_linux_64 --SAMTOOLS_PATH=/opt/conda/bin --workingdir=/fungap_workspace/fungap_out_ganoderma/braker1_out/SRR5261647 > /fungap_workspace/fungap_out_ganoderma/logs/braker1/braker1_SRR5261647.log 2>&1
Traceback (most recent call last):
  File "/workspace/FunGAP/run_braker1.py", line 197, in <module>
    main(sys.argv[1:])
  File "/workspace/FunGAP/run_braker1.py", line 91, in main
    masked_assembly, bam_files, output_dir, log_dir, num_cores, fungus_flag
  File "/workspace/FunGAP/run_braker1.py", line 171, in run_braker1
    )[0],
IndexError: list index out of range

I was trying to test pipeline combining different datasets (different RNA-seq and WGS experiments) and compare results with already know annotation. I`ve taken contigs from https://mycocosm.jgi.doe.gov/Gansp1/Gansp1.home.html and RNA-seq files were taken from project https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR5261647 

Therefore I have several questions - 1) is it applicable to use pipeline in such a manner (in a wgs experiment that we will perform RNA-seq data will be absent) 2) if RNA-seq data from outside experiment shouldn`t be mixed with own WGS data - are there easy ways to still use pipeline for gene annotation excluding Braker step (or exclude RNA-seq data at all, which is, ofcourse, is not desirable, since it could improve gene annotation)? Thanks for the answer in advance!

**Comment by hpajot** [comment]
I tried reinstalling everything from scratch. Some issues seem to be related to older installations of fungap on the same PC. I launched it a few minutes ago with suggested the S. cerevisiae data. I will let you know as soon it ends.
Thank you again.!

**Comment by hpajot** [comment]
**Ok:
It is me again. I run fungap, once more, inside docker. I used the DNa and RNAseq data recommended s examples. I get pretty much the same error. I will paste the error information and the content of the  log file you requested. I hope it could give you an idea of what is going wrong.
Thank you in advance **


Check input files...
TRANS_READ_FILES is ok...
GENOME_ASSEMBLY is ok...
SISTER_PROTEOME is ok...

[12-03 20:14] START: wrapper_run_hisat2
[Wrapper] python /workspace/FunGAP/run_hisat2.py --read_files SRR1198667_sampled_1.fastq SRR1198667_sampled_2.fastq --output_dir /fungap_workspace/cerevisiae_out/hisat2_out --log_dir /fungap_workspace/cerevisiae_out/logs --ref_fasta /fungap_workspace/cerevisiae.fas --num_cores 7 --max_intron 2000
[12-03 20:14] START: Hisat2
Running hisat2-build has already been finished
Ruuning Hisat2 has already been finished for SRR1198667_sampled
[12-03 20:14] DONE : Hisat2
[12-03 20:14] DONE : wrapper_run_hisat2

[12-03 20:14] START: wrapper_run_trinity
[Wrapper] python /workspace/FunGAP/run_trinity.py --bam_files /fungap_workspace/cerevisiae_out/hisat2_out/SRR1198667_sampled.bam --output_dir /fungap_workspace/cerevisiae_out/trinity_out --log_dir /fungap_workspace/cerevisiae_out/logs --num_cores 7 --max_intron 2000 --jaccard_clip
[12-03 20:14] START: Trinity for SRR1198667_sampled
Running Trinity has already been finished SRR1198667_sampled
[12-03 20:14] DONE : Trinity for SRR1198667_sampled
[12-03 20:14] DONE : wrapper_run_trinity

[12-03 20:14] START: wrapper_run_repeat_modeler
[Wrapper] python /workspace/FunGAP/run_repeat_modeler.py --genome_assembly /fungap_workspace/cerevisiae.fas --output_dir /fungap_workspace/cerevisiae_out/repeat_modeler_out --log_dir /fungap_workspace/cerevisiae_out/logs --num_cores 7
Running RepeatModeler has already been finished
[12-03 20:14] DONE : wrapper_run_repeat_modeler

[12-03 20:14] START: wrapper_run_maker
[Wrapper] python /workspace/FunGAP/run_maker.py --input_fasta /fungap_workspace/cerevisiae.fas --augustus_species saccharomyces_cerevisiae_S288C --protein_db_fasta /fungap_workspace/prot_db.faa --repeat_model /fungap_workspace/cerevisiae_out/repeat_modeler_out/RM_28549.TueDec31616522019/consensi.fa.classified --est_files /fungap_workspace/cerevisiae_out/trinity_out/trinity_SRR1198667_sampled/Trinity_SRR1198667_sampled.fasta --output_dir /fungap_workspace/cerevisiae_out/maker_out --num_cores 7 --log_dir /fungap_workspace/cerevisiae_out/logs --gmes_fungus
[12-03 20:14] START running Maker run1
Running Maker has already been finished
[12-03 20:14] DONE  running Maker run1
[Run] /opt/conda/bin/gff3_merge -d /fungap_workspace/cerevisiae_out/maker_out/SRR1198667_sampled/maker_run1/cerevisiae.maker.output/cerevisiae_master_datastore_index.log
[12-03 20:14] START training run1 & running maker run2
SNAP training has been alread finished for snap_hmm_v1.hmm
Running Maker has already been finished
[12-03 20:14] DONE  training run1 & running maker run2
[Run] /opt/conda/bin/gff3_merge -d /fungap_workspace/cerevisiae_out/maker_out/SRR1198667_sampled/maker_run2/cerevisiae.maker.output/cerevisiae_master_datastore_index.log
[12-03 20:14] START training run2 & running maker run3
SNAP training has been alread finished for snap_hmm_v2.hmm
Running Maker has already been finished
[12-03 20:14] DONE  training run2 & running maker run3
[Run] find /fungap_workspace/cerevisiae_out/maker_out/SRR1198667_sampled/maker_run3 -name "query.masked.fasta" | xargs cat > /fungap_workspace/cerevisiae_out/maker_out/masked_assembly.fasta
[12-03 20:14] START ruuning gmes to build hmm
GMES has already been finished
[12-03 20:14] DONE  running gmes to build hmm
[Run] /opt/conda/bin/gff3_merge -d /fungap_workspace/cerevisiae_out/maker_out/SRR1198667_sampled/maker_run3/cerevisiae.maker.output/cerevisiae_master_datastore_index.log
[12-03 20:14] START training run3 & running maker run4
SNAP training has been alread finished for snap_hmm_v3.hmm
Running Maker has already been finished
[12-03 20:14] DONE  training run3 & running maker run4
[Run] /opt/conda/bin/gff3_merge -g -n -d /fungap_workspace/cerevisiae_out/maker_out/SRR1198667_sampled/maker_run4/cerevisiae.maker.output/cerevisiae_master_datastore_index.log
[Run] /opt/conda/bin/fasta_merge -d /fungap_workspace/cerevisiae_out/maker_out/SRR1198667_sampled/maker_run4/cerevisiae.maker.output/cerevisiae_master_datastore_index.log
[Run] /opt/conda/bin/gff3_merge -d /fungap_workspace/cerevisiae_out/maker_out/SRR1198667_sampled/maker_run4/cerevisiae.maker.output/cerevisiae_master_datastore_index.log
[12-03 20:14] DONE : wrapper_run_maker

[12-03 20:14] START: wrapper_run_augustus
[Wrapper] python /workspace/FunGAP/run_augustus.py --masked_assembly /fungap_workspace/cerevisiae_out/maker_out/masked_assembly.fasta --species saccharomyces_cerevisiae_S288C --output_dir /fungap_workspace/cerevisiae_out/augustus_out --log_dir /fungap_workspace/cerevisiae_out/augustus_out/logs
[12-03 20:14] START: Augustus
Running Augustus has already been finished
[12-03 20:14] DONE : Augustus
[12-03 20:14] DONE : wrapper_run_augustus

[12-03 20:14] START: wrapper_run_braker1
[Wrapper] python /workspace/FunGAP/run_braker1.py --masked_assembly /fungap_workspace/cerevisiae_out/maker_out/masked_assembly.fasta --bam_files /fungap_workspace/cerevisiae_out/hisat2_out/SRR1198667_sampled.bam --output_dir /fungap_workspace/cerevisiae_out/braker1_out --log_dir /fungap_workspace/cerevisiae_out/logs --num_cores 7 --fungus
[12-03 20:14] START: BRAKER1
[Run] /opt/conda/bin/braker.pl --fungus --softmasking --cores=7 --genome=/fungap_workspace/cerevisiae_out/maker_out/masked_assembly.fasta --bam=/fungap_workspace/cerevisiae_out/hisat2_out/SRR1198667_sampled.bam --species=SRR1198667_sampled_1 --gff3 --AUGUSTUS_CONFIG_PATH=/opt/conda/bin/../config --BAMTOOLS_PATH=/opt/conda/bin --GENEMARK_PATH=/workspace/FunGAP/external/gm_et_linux_64 --SAMTOOLS_PATH=/opt/conda/bin --workingdir=/fungap_workspace/cerevisiae_out/braker1_out/SRR1198667_sampled > /fungap_workspace/cerevisiae_out/logs/braker1/braker1_SRR1198667_sampled.log 2>&1
Traceback (most recent call last):
  File "/workspace/FunGAP/run_braker1.py", line 197, in <module>
    main(sys.argv[1:])
  File "/workspace/FunGAP/run_braker1.py", line 91, in main
    masked_assembly, bam_files, output_dir, log_dir, num_cores, fungus_flag
  File "/workspace/FunGAP/run_braker1.py", line 171, in run_braker1
    )[0],
IndexError: list index out of range
Traceback (most recent call last):
  File "/workspace/FunGAP/fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "/workspace/FunGAP/fungap.py", line 223, in main
    masked_assembly, trans_bams, output_dir, num_cores, no_braker_fungus
  File "/workspace/FunGAP/fungap.py", line 446, in run_braker1
    check_call(command_args)
  File "/opt/conda/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/workspace/FunGAP/run_braker1.py', '--masked_assembly', '/fungap_workspace/cerevisiae_out/maker_out/masked_assembly.fasta', '--bam_files', '/fungap_workspace/cerevisiae_out/hisat2_out/SRR1198667_sampled.bam', '--output_dir', '/fungap_workspace/cerevisiae_out/braker1_out', '--log_dir', '/fungap_workspace/cerevisiae_out/logs', '--num_cores', '7', '--fungus']' returned non-zero exit status 1
(base) root@fc28d9e94ef7:/fungap_workspace# 

**I get this too, **/home/hpajot/cerevisiae/cerevisiae_out/logs/braker1/braker1_SRR1198667_sampled.log****
NEXT STEP: check files and settings
NEXT STEP: check options
... options check complete.
NEXT STEP: check fasta headers
fasta headers check complete.
NEXT STEP: create SAM header file /fungap_workspace/cerevisiae_out/braker1_out/SRR1198667_sampled/braker/SRR1198667_sampled_1/SRR1198667_sampled_header.sam.
SAM file /fungap_workspace/cerevisiae_out/braker1_out/SRR1198667_sampled/braker/SRR1198667_sampled_1/SRR1198667_sampled_header.sam complete.
NEXT STEP: check BAM headers
headers check for BAM file /fungap_workspace/cerevisiae_out/hisat2_out/SRR1198667_sampled.bam complete.
NEXT STEP: make hints from BAM file /fungap_workspace/cerevisiae_out/hisat2_out/SRR1198667_sampled.bam
Wait a moment, calculating maximum block size that needs to be allocated... .. done

hints from BAM file /fungap_workspace/cerevisiae_out/hisat2_out/SRR1198667_sampled.bam added.
NEXT STEP: sort hints
hints sorted.
NEXT STEP: summarize multiple identical hints to one
hints joined.
NEXT STEP: filter introns, find strand and change score to 'mult' entry
strands found and score changed.
hints file complete.
NEXT STEP: execute GeneMark-ET
GeneMark-ET finished.
NEXT STEP: convert GeneMark-ET to real gtf format
GeneMark-ET conversion.
NEXT STEP: create new species SRR1198667_sampled_1
Will create parameters for a EUKARYOTIC species!
creating directory /opt/conda/config/species/SRR1198667_sampled_1/ ...
creating /opt/conda/config/species/SRR1198667_sampled_1/SRR1198667_sampled_1_parameters.cfg ...
creating /opt/conda/config/species/SRR1198667_sampled_1/SRR1198667_sampled_1_weightmatrix.txt ...
creating /opt/conda/config/species/SRR1198667_sampled_1/SRR1198667_sampled_1_metapars.cfg ...
The necessary files for training SRR1198667_sampled_1 have been created.
Now, either run etraining or optimize_parameters.pl with --species=SRR1198667_sampled_1.
etraining quickly estimates the parameters from a file with training genes.
optimize_augustus.pl alternates running etraining and augustus to find optimal metaparameters.

NEXT STEP: get flanking DNA size
NEXT STEP: create genbank file
genbank file created.
NEXT STEP: filter genbank file
genbank file filtered.
NEXT STEP: split genbank file into train and test file
ERROR: Number of good genes is 0, so the parameters cannot be optimized. Recomended are at least 300 genes
WARNING: Number of good genes is low (0
). Recomended are at least 300 genes

**Comment by mbnmbn00** [comment]
I will try myself the example sample and let you know if it is a bug.

**Comment by mbnmbn00** [comment]
I could reproduce the problem. My versions are:

- GeneMark-ES Suite version 4.48_3.60_lic
- AUGUSTUS v3.3
- braker.pl 1.9

### Solution first
Edit `/opt/conda/bin/filterGenesIn_mRNAname.pl`
Add "?" at Line 27:
`            if($_ =~ m/transcript_id \"(.*)\"/) {`
to
`            if($_ =~ m/transcript_id \"(.*?)\"/) {`

### Problem
This is because recent GeneMark changed the format of
```
/fungap_workspace/fungap_out/braker1_out/SRR1198667_sampled/braker/SRR1198667_sampled/GeneMark-ET/genemark.f.good.gtf
```
In previous version:
```
NC_001147.6	GeneMark.hmm	stop_codon	711683	711685	.	-	0	gene_id "2_g"; transcript_id "2_t"; count "1_1";
NC_001147.6	GeneMark.hmm	CDS	711683	712543	.	-	0	gene_id "2_g"; transcript_id "2_t"; cds_type "Single"; count "1_1";
NC_001147.6	GeneMark.hmm	exon	711683	712543	0	-	.	gene_id "2_g"; transcript_id "2_t"; cds_type "Single"; count "1_1";
```

In the current version (4.48_3.60_lic):
```
NC_001136.10	GeneMark.hmm	start_codon	1102184	1102186	.	+	0	gene_id "1_g"; transcript_id "1_t";
NC_001136.10	GeneMark.hmm	CDS	1102184	1103428	.	+	0	gene_id "1_g"; transcript_id "1_t";
NC_001136.10	GeneMark.hmm	exon	1102184	1103428	0	+	.	gene_id "1_g"; transcript_id "1_t";
```

Notice the "cds_type" and "count" attributes. Regular expression to parse "transcript_id" was
```
transcript_id \"(.*)\"
```
So caught strings would be `2_g"; transcript_id "2_t"; cds_type "Single"; count "1_1`.
I may contact braker team to update this.

**Comment by mbnmbn00** [comment]
It was known issue!
https://github.com/Gaius-Augustus/BRAKER/issues/126

**Comment by mbnmbn00** [comment]
> 1) is it applicable to use pipeline in such a manner (in a wgs experiment that we will perform RNA-seq data will be absent)

Yes, it is possible. We tested with different similarity levels (same genus, same species, etc) and showed the result is not bad. Of course, there would be more errors than you use the RNA-seq from what you sequence for WGS. The benchmark test has been published. https://link.springer.com/protocol/10.1007/978-1-4939-9173-0_4

> 2) if RNA-seq data from outside experiment shouldn`t be mixed with own WGS data - are there easy ways to still use the pipeline for gene annotation excluding Braker step (or exclude RNA-seq data at all, which is, of course, is not desirable, since it could improve gene annotation)? Thanks for the answer in advance!

Currently, I have to say no. The only program that doesn't require RNA-seq is Augustus. Maker and Braker heavily rely on RNA-seq data. I was thinking to make FunGAP-denovo that implements BUSCO, Braker (with GeneMark-EP), Augustus, and Genewise. But I'm not sure when I can even start work.
Meanwhile, you may try solely Braker (with GeneMark-EP) for your experiments.

**Comment by Tierprot** [comment]
Rerun pipeline with suggested modification - worked like a charm, suggest to close ticket

**Comment by hpajot** [comment]
Sorry I was running it. Works nicely. Thanks a lot.
