### ISSUE TITLE
Fungap without mRNA reads

### ISSUE THREAD

**Issue by euduca** [CompSynBioLab-KoreaUniv/FunGAP#32]
Hi,

can I use Fungap without the Illumina paired-end mRNA reads files?

I have only the genome assembly.

Thanks.

**Comment by mbnmbn00** [comment]
I'm afraid to say that FunGAP doesn't support non-RNA-seq annotation in this moment.
For the accurate gene prediction, RNA-seq should be made and put in the pipeline.

NCBI SRA database (https://www.ncbi.nlm.nih.gov/sra) provides some transcriptomic data that you may want to try. Though, the data from the exact same strain is optimal.

I benchmarked this and published it in the recent book chapter.
https://link.springer.com/protocol/10.1007%2F978-1-4939-9173-0_4

> 4.1 Case 1—When RNA-Seq Reads Are Not Available
The sequencing of mature mRNA molecules provides direct evidence for exon–intron structure. Using RNA-seq reads data is most crucial for obtaining the high-quality gene prediction. If RNA-seq data are not available, one alternative option is using the available RNA-seq reads (a surrogate RNA-seq) from the most taxonomically close neighbor organism. The surrogate RNA-seq reads can be searched and downloaded from the NCBI Sequence Read Archive (https://www.ncbi.nlm.nih.gov/sra) or the MycoCosm database (https://genome.jgi.doe.gov/programs/fungi/index.jsf) [18]. To probe how much taxonomically distant species can be used, we benchmarked the N. crassa OR74A genome with various surrogate RNA-seq data. When the surrogate RNA-seq reads were obtained from same species and genus level (average nucleotide identity 96.0% and 92.7%), the prediction was quite good compared to the prediction from the original RNA-seq data, whereas the prediction quality dramatically decreased when the surrogate RNA-seq was obtained from the family level (Table 2). GeneMark-ES self-training gene prediction gave higher BUSCO completeness, but the lower number of matches to the reference than the prediction using the surrogate RNA-seq reads from the family level. Therefore, we recommend to use this alternative option only when the surrogate RNA-seq reads can be obtained from genus level or species level. However, for quick-and-dirty way of genome analysis, family-level relatives will also predict with some quality.
