### ISSUE TITLE
Busco database issue

### ISSUE THREAD

**Issue by shigdon** [CompSynBioLab-KoreaUniv/FunGAP#34]
Hi,

I've taken some time away from trying to use FunGAP to annotate my yeast genomes, but am now determined to pick things back up. I'm trying to get everything installed but am running into problems with the busco step. I've tried doing the installation manually through anaconda, and also using the docker image.

It appears to me that the links to download the busco databases are now broken. I presume that this could be due to the new release of busco v4. Is there a way to overcome this problem? 

I can't figure out how to download odb9 files, and exploring the ezlab website online I've only been able to find odb_V10 files.

I'm seeing ERROR 404: Not Found. when trying to download the busco databases.

Any guidance would be really appreciated!

Thanks!

**Comment by mbnmbn00** [comment]
Thank you so much for reporting this. While I check the overall installation, the proper links to download odb9 files are:

https://busco-archive.ezlab.org/v3/datasets/fungi_odb9.tar.gz
https://busco-archive.ezlab.org/v3/datasets/ascomycota_odb9.tar.gz
https://busco-archive.ezlab.org/v3/datasets/basidiomycota_odb9.tar.gz
https://busco-archive.ezlab.org/v3/datasets/saccharomycetales_odb9.tar.gz

You can find these links at:
https://busco-archive.ezlab.org/v3/

You may force the conda install BUSCO v3.0.2, not 4.0.0.
