### ISSUE TITLE
Stalls on wrapper_filter_gff3s

### ISSUE THREAD

**Issue by fungal-spore** [CompSynBioLab-KoreaUniv/FunGAP#35]
Hi,
Based on my other successful runs, filter_gff3s.py should finish quickly however its been stalled over night and appears to be using a tremendous amount of memory.
In the gene_filtering directory these files all appear complete:
augustus.blastn                busco_score.txt              nr_prot_mapping.txt
augustus_filtered.list         D_bad.p                      nr_prot.pfam_scan
bad_genes_stats.txt            gene_model_scores.txt        pfam_score.p
blastn_score.p                 maker_Ptr-veg.blastn         trinity_transcripts.fna
blastp_score.p                 maker_Ptr-veg_filtered.list  trinity_transcripts.fna.nhr
braker1_Ptr-veg.blastn         nr_prot.blastp               trinity_transcripts.fna.nin
braker1_Ptr-veg_filtered.list  nr_prot.faa                  trinity_transcripts.fna.nsq
busco_score.p                  nr_prot.faa_nonX

but directory appears to be missing:
filtered_1.gff3              
filtered_2.gff3              
filtered_prot.faa            
filtered_protnames.list

The filter_gff3s.log simply states
START: Filtering GFF3

It has not run into error but maybe caught in loop?
Any recommendation on what to do?
Thanks

**Comment by mbnmbn00** [comment]
What is the memory of your computer?
I think there is a **really big chunk** of the overlapping genes.

If you don't mind, can you send me "gene_filtering" directory and three GFF3 files?
augusuts.gff3 braker_<prefix>.gff3 maker_<prefix>.gff3

I have a high memory server so I can run that from here.
My E-mail address: mbnmbn00@gmail.com
If size is big, you can upload it to Google Drive and share it with me.

**Comment by fungal-spore** [comment]
I am on HPC cluster, node this is running on has 3TB ram, right now it is using about 1.5TB. I will get files to you shortly.

**Comment by mbnmbn00** [comment]
You have a high memory!
Then, can you also send me the assembly file?
I want to check what made such a big chunk.

**Comment by fungal-spore** [comment]
I have shared with above email, should have gene_filter dir, gff3 and contigs.fa

**Comment by fungal-spore** [comment]
I think process was killed

[01-22 23:19] START: wrapper_filter_gff3s
[Wrapper] python /home/userXX/FunGAP/filter_gff3s.py --genome_assembly /isilon/users/userXX/assembly/T181-1/contigs.fa --input_gff3s /isilon/users/userXX/predic/T181-1/spades_fungap/augustus_out/augustus.gff3 /isilon/users/userXX/predic/T181-1/spades_fungap/maker_out/Ptr-veg/maker_Ptr-veg.gff3 /isilon/users/userXX/predic/T181-1/spades_fungap/braker1_out/Ptr-veg/braker1_Ptr-veg.gff3 --mapping_file /isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering/nr_prot_mapping.txt --blastp_dict /isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering/blastp_score.p --busco_dict /isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering/busco_score.p --pfam_dict /isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering/pfam_score.p --blastn_dict /isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering/blastn_score.p --bad_dict /isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering/D_bad.p --nr_prot_file /isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering/nr_prot.faa --output_dir /isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering --log_dir /isilon/users/userXX/predic/T181-1/spades_fungap/logs
[01-22 23:19] START: Filtering GFF3
Traceback (most recent call last):
  File "/home/userXX/FunGAP/fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "/home/userXX/FunGAP/fungap.py", line 268, in main
    blastn_dict, bad_dict, nr_prot_file, nr_prot_mapping_file, output_dir
  File "/home/userXX/FunGAP/fungap.py", line 691, in filter_gff3s
    check_call(command_args)
  File "/home/userXX/miniconda3/envs/fungap2/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/home/userXX/FunGAP/filter_gff3s.py', '--genome_assembly', '/isilon/users/userXX/assembly/T181-1/contigs.fa', '--input_gff3s', '/isilon/users/userXX/predic/T181-1/spades_fungap/augustus_out/augustus.gff3', '/isilon/users/userXX/predic/T181-1/spades_fungap/maker_out/Ptr-veg/maker_Ptr-veg.gff3', '/isilon/users/userXX/predic/T181-1/spades_fungap/braker1_out/Ptr-veg/braker1_Ptr-veg.gff3', '--mapping_file', '/isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering/nr_prot_mapping.txt', '--blastp_dict', '/isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering/blastp_score.p', '--busco_dict', '/isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering/busco_score.p', '--pfam_dict', '/isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering/pfam_score.p', '--blastn_dict', '/isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering/blastn_score.p', '--bad_dict', '/isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering/D_bad.p', '--nr_prot_file', '/isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering/nr_prot.faa', '--output_dir', '/isilon/users/userXX/predic/T181-1/spades_fungap/gene_filtering', '--log_dir', '/isilon/users/userXX/predic/T181-1/spades_fungap/logs']' returned non-zero exit status -9

**Comment by mbnmbn00** [comment]
It seems that "your species" and the input "Augustus model" are different a lot.
Augustus predicted ridiculously long genes (~10 kbp) overall genome.

I deleted all the genes (but left one for parsing) from `augustus.gff3` and it ran nicely.
(I deleted the lines from 41 to the end)

I will consider an option to turn off Augustus when there is no proper "Augustus model".

**Comment by mbnmbn00** [comment]
You can run the FunGAP with the same command without deleting previously generated ones.
It will recognize the already finished steps. Good luck!!

**Comment by fungal-spore** [comment]
That is strange! Augustus is set to use same species for my other 39 isolates and they all finished without issue, my selection was done based on output from get_augustus_species.py as well. 
I removed genes from augustus.gff3 as you suggested and voila! Thanks very much for your quick response and help.

**Comment by mbnmbn00** [comment]
Glad it helped!

**Comment by nidhi-gohil** [comment]
I had to skip the Braker because of the unavailability of good RNA-Seq data for my sample.
So, I performed these steps to skip the Braker https://github.com/CompSynBioLab-KoreaUniv/FunGAP/issues/68#issuecomment-865380366

However, when it reaches to wrapper_filter_gff3 step, it looks for braker_SRR.gff3 file, but in my case it's empty.
What can be done?

```
05-01 14:41] START: wrapper_filter_gff3s
[Wrapper] /home/nidhi/FunGAP/filter_gff3s.py --genome_assembly /home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/ARE21-195-4528-PB_MGA_polished_assembly.fasta --input_gff3s /home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/augustus_out/augustus.gff3 /home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/maker_out/DRR101125/maker_DRR101125.gff3 /home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/braker_out/DRR101125/braker_DRR101125.gff3 --mapping_file /home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering/nr_prot_mapping.txt --blastp_dict /home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering/blastp_score.p --busco_dict /home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering/busco_score.p --pfam_dict /home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering/pfam_score.p --blastn_dict /home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering/blastn_score.p --bad_dict /home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering/d_bad.p --nr_prot_file /home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering/nr_prot.faa --output_dir /home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering --log_dir /home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/logs
[05-01 14:41] START: Filtering GFF3
Traceback (most recent call last):
  File "/home/nidhi/FunGAP/filter_gff3s.py", line 507, in <module>
    main()
  File "/home/nidhi/FunGAP/filter_gff3s.py", line 123, in main
    self_filtered = filtering(d_cds, d_cds_len, d_score)
  File "/home/nidhi/FunGAP/filter_gff3s.py", line 307, in filtering
    tmp_list = [d_cds_sorted[0][0]]  # Initialize
IndexError: list index out of range
Traceback (most recent call last):
  File "FunGAP/fungap.py", line 839, in <module>
    main()
  File "FunGAP/fungap.py", line 272, in main
    d_path, logger
  File "FunGAP/fungap.py", line 775, in filter_gff3s
    check_call(command_args)
  File "/home/nidhi/miniconda3/envs/fungap/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/nidhi/FunGAP/filter_gff3s.py', '--genome_assembly', '/home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/ARE21-195-4528-PB_MGA_polished_assembly.fasta', '--input_gff3s', '/home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/augustus_out/augustus.gff3', '/home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/maker_out/DRR101125/maker_DRR101125.gff3', '/home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/braker_out/DRR101125/braker_DRR101125.gff3', '--mapping_file', '/home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering/nr_prot_mapping.txt', '--blastp_dict', '/home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering/blastp_score.p', '--busco_dict', '/home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering/busco_score.p', '--pfam_dict', '/home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering/pfam_score.p', '--blastn_dict', '/home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering/blastn_score.p', '--bad_dict', '/home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering/d_bad.p', '--nr_prot_file', '/home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering/nr_prot.faa', '--output_dir', '/home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/gene_filtering', '--log_dir', '/home/nidhi/Ali_fungal_assemblies_annotation/ARE21-195/logs']' returned non-zero exit status 1.

```

**Comment by mbnmbn00** [comment]
Hello,
One workaround I can think of right now is to copy the output from MAKER or AUGUSTUS into the BRAKER GFF3 file.
They will be filtered out during the filtering process.
I will think of smarter way to do it in the future. Thank you!
