### ISSUE TITLE
maker problem

### ISSUE THREAD

**Issue by Hoberti** [CompSynBioLab-KoreaUniv/FunGAP#37]
Hi,
I try to run the fungap pipeline, but each time maker 4 runs fails.
I installed the new FunGAP version and I update conda, I remove fungap environment and re installed all dependencies but it keep running the same error. All dependencies were installed as solicitated in INSTALL.md

Could you help me?

[02-03 08:38] START running Maker run1
Possible precedence issue with control flow operator at /DATOS/hoberti/anaconda2/envs/fungap/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 845.
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/maker -fix_nucleotides > /DATOS/hoberti/U30_results/logs/maker/maker_U30_run1.log 2>&1
[02-03 08:55] DONE  running Maker run1
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/gff3_merge -d /DATOS/hoberti/U30_results/maker_out/U30/maker_run1/U30.maker.output/U30_master_datastore_index.log
[02-03 08:55] START training run1 & running maker run2
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/maker2zff -n /DATOS/hoberti/U30_results/maker_out/U30/maker_run1/U30.all.gff
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/fathom -categorize 1000 genome.ann genome.dna
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/fathom -export 1000 -plus uni.ann uni.dna
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/forge ../export.ann ../export.dna
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/hmm-assembler.pl snap_hmm_v1 parameters > snap_hmm_v1.hmm
Possible precedence issue with control flow operator at /DATOS/hoberti/anaconda2/envs/fungap/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 845.
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/maker -fix_nucleotides > /DATOS/hoberti/U30_results/logs/maker/maker_U30_run2.log 2>&1
[02-03 08:55] DONE  training run1 & running maker run2
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/gff3_merge -d /DATOS/hoberti/U30_results/maker_out/U30/maker_run2/U30.maker.output/U30_master_datastore_index.log
ERROR: The file '/DATOS/hoberti/U30_results/maker_out/U30/maker_run2/U30.maker.output/U30_master_datastore_index.log' does not exist
[02-03 08:55] START training run2 & running maker run3
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/maker2zff -n /DATOS/hoberti/U30_results/maker_out/U30/maker_run2/U30.all.gff
No such file or directory at /DATOS/hoberti/anaconda2/envs/fungap/bin/maker2zff line 106.
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/fathom -categorize 1000 genome.ann genome.dna
ZOE ERROR (from /DATOS/hoberti/anaconda2/envs/fungap/share/snap/bin/fathom): zoeOpenFile failed to open file (genome.dna)
ZOE library version 2013-02-16
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/fathom -export 1000 -plus uni.ann uni.dna
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/forge ../export.ann ../export.dna
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/hmm-assembler.pl snap_hmm_v2 parameters > snap_hmm_v2.hmm
Possible precedence issue with control flow operator at /DATOS/hoberti/anaconda2/envs/fungap/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 845.
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/maker -fix_nucleotides > /DATOS/hoberti/U30_results/logs/maker/maker_U30_run3.log 2>&1
[02-03 08:55] DONE  training run2 & running maker run3
[Run] find /DATOS/hoberti/U30_results/maker_out/U30/maker_run3 -name "query.masked.fasta" | xargs cat > /DATOS/hoberti/U30_results/maker_out/masked_assembly.fasta
[02-03 08:55] START ruuning gmes to build hmm
[Run] /DATOS/hoberti/Programas/FunGAP/external/gm_et_linux_64/gmes_petap.pl --ES --fungus --cores 12 --sequence /DATOS/hoberti/U30_results/maker_out/masked_assembly.fasta --soft_mask 1 > /DATOS/hoberti/U30_results/logs/maker/gmes.log 2>&1
[02-03 08:55] DONE  running gmes to build hmm
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/gff3_merge -d /DATOS/hoberti/U30_results/maker_out/U30/maker_run3/U30.maker.output/U30_master_datastore_index.log
ERROR: The file '/DATOS/hoberti/U30_results/maker_out/U30/maker_run3/U30.maker.output/U30_master_datastore_index.log' does not exist
[02-03 08:55] START training run3 & running maker run4
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/maker2zff -n /DATOS/hoberti/U30_results/maker_out/U30/maker_run3/U30.all.gff
No such file or directory at /DATOS/hoberti/anaconda2/envs/fungap/bin/maker2zff line 106.
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/fathom -categorize 1000 genome.ann genome.dna
ZOE ERROR (from /DATOS/hoberti/anaconda2/envs/fungap/share/snap/bin/fathom): zoeOpenFile failed to open file (genome.dna)
ZOE library version 2013-02-16
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/fathom -export 1000 -plus uni.ann uni.dna
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/forge ../export.ann ../export.dna
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/hmm-assembler.pl snap_hmm_v3 parameters > snap_hmm_v3.hmm
Possible precedence issue with control flow operator at /DATOS/hoberti/anaconda2/envs/fungap/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 845.
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/maker -fix_nucleotides > /DATOS/hoberti/U30_results/logs/maker/maker_U30_run4.log 2>&1
[02-03 08:55] DONE  training run3 & running maker run4
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/gff3_merge -g -n -d /DATOS/hoberti/U30_results/maker_out/U30/maker_run4/U30.maker.output/U30_master_datastore_index.log
ERROR: The file '/DATOS/hoberti/U30_results/maker_out/U30/maker_run4/U30.maker.output/U30_master_datastore_index.log' does not exist
[Run] /DATOS/hoberti/anaconda2/envs/fungap/bin/fasta_merge -d /DATOS/hoberti/U30_results/maker_out/U30/maker_run4/U30.maker.output/U30_master_datastore_index.log
ERROR: The file '/DATOS/hoberti/U30_results/maker_out/U30/maker_run4/U30.maker.output/U30_master_datastore_index.log' does not exist
Traceback (most recent call last):
  File "/DATOS/hoberti/Programas/FunGAP/run_maker.py", line 647, in <module>
    main(sys.argv[1:])
  File "/DATOS/hoberti/Programas/FunGAP/run_maker.py", line 245, in main
    collect_result_final(input_fasta, output_dir, est_prefix)
  File "/DATOS/hoberti/Programas/FunGAP/run_maker.py", line 555, in collect_result_final
    copyfile(merged_gff3, output_gff3)
  File "/DATOS/hoberti/anaconda2/envs/fungap/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/DATOS/hoberti/U30_results/maker_out/U30/maker_run4/U30.all.gff'
Traceback (most recent call last):
  File "/DATOS/hoberti/Programas/FunGAP/fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "/DATOS/hoberti/Programas/FunGAP/fungap.py", line 209, in main
    num_cores, repeat_model_file, trinity_asms, no_genemark_fungus
  File "/DATOS/hoberti/Programas/FunGAP/fungap.py", line 397, in run_maker
    check_call(command_args)
  File "/DATOS/hoberti/anaconda2/envs/fungap/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/DATOS/hoberti/Programas/FunGAP/run_maker.py', '--input_fasta', '/DATOS/hoberti/Claviceps_paspali/U30/U30.fasta', '--augustus_species', 'fusarium_graminearum', '--protein_db_fasta', '/DATOS/hoberti/Programas/FunGAP/sister_orgs/prot_db.faa', '--repeat_model', '/DATOS/hoberti/U30_results/repeat_modeler_out/RM_18759.SunFeb20022322020/consensi.fa.classified', '--est_files', '/DATOS/hoberti/U30_results/trinity_out/trinity_U30/Trinity_U30.fasta', '--output_dir', '/DATOS/hoberti/U30_results/maker_out', '--num_cores', '12', '--log_dir', '/DATOS/hoberti/U30_results/logs', '--gmes_fungus']' returned non-zero exit status 1

At logs/maker

gmes.log

error: no sequence to split
error on call: /DATOS/hoberti/Programas/FunGAP/external/gm_et_linux_64/probuild  --seq /DATOS/hoberti/U30_results/maker_out/genemark_out/data/dna.fna  --split dna.fa  --max_contig 5000000 --min_contig 50000 --letters_per_line 100 --split_at_n 5000 --split_at_x 5000 --allow_x --x_to_n  --trace ../../info/training.trace 

maker_U30_run2

Possible precedence issue with control flow operator at /DATOS/hoberti/anaconda2/envs/fungap/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 845.
STATUS: Parsing control files...
STATUS: Processing and indexing input FASTA files...
STATUS: Setting up database for any GFF3 input...
DBI connect('dbname=/DATOS/hoberti/U30_results/maker_out/U30/maker_run2/U30.maker.output/U30.db','',...) failed: unable to open database file at /DATOS/hoberti/anaconda2/envs/fungap/bin/../lib/GFFDB.pm line 107.
Can't call method "do" on an undefined value at /DATOS/hoberti/anaconda2/envs/fungap/bin/../lib/GFFDB.pm line 108.
--> rank=NA, hostname=centos

maker_U30_run3

Possible precedence issue with control flow operator at /DATOS/hoberti/anaconda2/envs/fungap/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 845.
STATUS: Parsing control files...
ERROR: The 'maker_gff' file[s] /DATOS/hoberti/U30_results/maker_out/U30/maker_run2/U30.all.gff do not exist.
Please check settings in the control files.

--> rank=NA, hostname=centos

maker_U30_run4

Possible precedence issue with control flow operator at /DATOS/hoberti/anaconda2/envs/fungap/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 845.
STATUS: Parsing control files...
ERROR: The 'maker_gff' file[s] /DATOS/hoberti/U30_results/maker_out/U30/maker_run3/U30.all.gff do not exist.
Please check settings in the control files.

ERROR: The HMM file[s] provided for gmhmm do not exist:
	/DATOS/hoberti/U30_results/maker_out/genemark_out/output/gmhmm.mod

--> rank=NA, hostname=centos

Thanks in advance,

Héctor

**Comment by mbnmbn00** [comment]
Hi, Based on your log, maker_run2 already failed.
```
ERROR: The file '/DATOS/hoberti/U30_results/maker_out/U30/maker_run2/U30.maker.output/U30_master_datastore_index.log' does not exist
```
Could you attach `maker_run1.log` and `maker_run2.log`?

**Comment by Hoberti** [comment]
Hi I am attaching requested logs

Thanks in advance,

Héctor

[maker_U30.zip](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/4152923/maker_U30.zip)

**Comment by mbnmbn00** [comment]
The key error message is:
```
DBI connect('dbname=/DATOS/hoberti/U30_results/maker_out/U30/maker_run1/U30.maker.output/U30.db','',...) failed: unable to open database file at /DATOS/hoberti/anaconda2/envs/fungap/bin/../lib/GFFDB.pm line 107.
Can't call method "do" on an undefined value at /DATOS/hoberti/anaconda2/envs/fungap/bin/../lib/GFFDB.pm line 108.
```

My successful output is like:
```
#--------- command -------------#
Widget::RepeatMasker:
cd /tmp/maker_qJobbS; /opt/conda/bin/RepeatMasker /fungap_workspace/fungap_out/maker_out/SRR1198667_sampled/maker_run1/GCF_000146045.2_R64_genomic.maker.output/GCF_000146045.2_R64_genomic_datastore/7B/05/NC_001133.9//theVoid.NC_001133.9/0/NC_001133%2E9.0.consensi%2Efa%2Eclassified.specific -dir /fungap_workspace/fungap_out/maker_out/SRR1198667_sampled/maker_run1/GCF_000146045.2_R64_genomic.maker.output/GCF_000146045.2_R64_genomic_datastore/7B/05/NC_001133.9//theVoid.NC_001133.9/0 -pa 8 -lib /fungap_workspace/fungap_out/repeat_modeler_out/RM_32253.FriSep201744292019/consensi.fa.classified
```

You may check if the file exists and is correct:
```
/DATOS/hoberti/U30_results/maker_out/U30/maker_run1/U30.maker.output/U30.db
```

You might run the test dataset to see if the installation was correct.
```
# Download RNA-seq reads using SRA toolkit (https://www.ncbi.nlm.nih.gov/sra/docs/toolkitsoft/)
fastq-dump -I --split-files SRR1198667
head -n 12000000 SRR1198667_1.fastq > SRR1198667_sampled_1.fastq
head -n 12000000 SRR1198667_2.fastq > SRR1198667_sampled_2.fastq

# Download assembly
wget ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/146/045/GCF_000146045.2_R64/GCF_000146045.2_R64_genomic.fna.gz
```

Have you considered using **Docker** to install the FunGAP?
It would be more stable than installing dependencies separately.

**Comment by mbnmbn00** [comment]
In case you want to check it fast, I attach RepeatModeler and Trinity output.

```
python /workspace/FunGAP/run_maker.py \
  --input_fasta GCF_000146045.2_R64_genomic.fna \
  --augustus_species saccharomyces_cerevisiae_S288C \
  --protein_db_fasta prot_db.faa \
  --repeat_model consensi.fa.classified \
  --est_files Trinity_SRR1198667_sampled.fasta \
  --output_dir maker_out \
  --num_cores 8 \
  --log_dir logs \
  --gmes_fungus
```
[Archive.zip](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/4157038/Archive.zip)
