### ISSUE TITLE
Alternative yeast genetic code

### ISSUE THREAD

**Issue by adarmitage** [CompSynBioLab-KoreaUniv/FunGAP#39]
I am currently annotating the genome from the CUG clade of ascomycetous yeasts. Following FunGAP prediction my gene models are output using the standard genetic code. Is there a recommended way for FunGAP to output proteins using the Alternative yeast nuclear code (code 12 - CUG encodes S rather than L)?

**Comment by mbnmbn00** [comment]
That is an interesting request! I have to update the FunGAP code for that. Since I have to test from the installation and test run, it will take some time. I will let you know when it's finished. Meanwhile, I attach a script that takes assembly and GFF3 files and translates it given a translation table. 

```
gff3_translation.py \
  --asm_file assembly.fasta \
  --gff3_file fungap_out.gff3 \
  --translation_table 12 \
  --output_file fungap_out.faa
  --
```

I hope it helps!
 
[gff3_translation.py.gz](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/4581174/gff3_translation.py.gz)

**Comment by adarmitage** [comment]
Thanks for getting back to me and looking into it, greatly appreciated.

**Comment by mbnmbn00** [comment]
I was working on this over the last several months (sorry I was busy).
It turned out that it's not that simple! I had to move on to BRAKER2 which conflicts every bit of dependencies installed via conda.

I might transit into Python3-based FunGAP which will be a major upgrade.

**Comment by adarmitage** [comment]
Thanks for your efforts. I look forward to seeing BRAKER2 in the next release.

**Comment by mbnmbn00** [comment]
FunGAP has been updated into v1.1.0 and now it supports the `--translation_table` option.

1) Augustus and Braker take the `--tranlsation_table`

 - The gene predictions are exactly the same in Augustus (only translation is different)
 - The gene predictions are different in Braker, but it seems it uses some random seed for gene prediction. I.e., even the same `translation_table` they produce a different result when I ran again. So it seems `translation_table` doesn't affect gene prediction itself.

2) The maker doesn't support `--translation_table`.

 - FunGAP produces GFF3 first and translate it with the given `translation_table`

3) I tested with _Candida albicans_ and it worked fine.

4) Example command

```
$FUNGAP_DIR/fungap.py \
  --output_dir fungap_out \
  --trans_read_1 SRR11596199_val_1.fq \
  --trans_read_2 SRR11596199_val_2.fq \
  --genome_assembly GCF_000182965.3_ASM18296v3_genomic.fna \
  --augustus_species candida_albicans \
  --sister_proteome prot_db.faa \
  --busco_dataset saccharomycetes_odb10 \
  --num_cores 8 \
  --translation_table 12
```

Hope it helps. Let me know if it doesn't work or you have any questions.
Could you click the "star" button if you don't mind?

**Comment by mbnmbn00** [comment]
I'm closing it for now. Please re-open whenever you want!
