### ISSUE TITLE
Copy of Genemark that is distributed with FunGAP

### ISSUE THREAD

**Issue by robinengler** [CompSynBioLab-KoreaUniv/FunGAP#4]
Hello,

I did some test run with FunGAP but eventually it crashed, apparently because the copy of Genemark that is distributed with FunGAP is a demo version with an expired license. Here is the error message:

```
GeneMark.hmm 400-day license.
Your 400-day license period has ended. We hope that you found this
software useful. If you would like to renew this license,
please contact GeneProbe, Inc. at custserv@genepro.com
```

My understanding is that GeneMark is a commercial software, so are users of FunGAP supposed to buy a license for GeneMark and then use it to run FunGAP ?

**Comment by mbnmbn00** [comment]
I'm sorry for the inconvenience using FunGAP.

I believe that GeneMark is available for non-commercial users for 400 days.
Can you manually install GeneMark and locate your own `gm_key` to your home directory?

That will resolve your issue.

**Comment by robinengler** [comment]
Thank you for your reply.
OK so I understand how it work. Maybe this information could be added to the README file for fungap so that future users know it does require a separate license for GeneMark.

If I were you I would also remove the GeneMark key you have from the git repository, as I'm not sure you are supposed to distribute it like that ;-)  (but I might be wrong, I haven't read the details of the GeneMark license terms).

Best regards,
Robin

**Comment by mbnmbn00** [comment]
Yes. I agree with you. I was just trying to reduce dependencies to be manually installed for users' convenience. I will may extract GeneMark from the package and leave it to users.

Thanks for the kind advice.
