### ISSUE TITLE
gmes_petap.pl

### ISSUE THREAD

**Issue by fungal-spore** [CompSynBioLab-KoreaUniv/FunGAP#40]
Hi,
This is just to inform you that GeneMark directory name has changed and no longer match your conda install instructions.
My license expired so I re-installed and then I kept getting errors and was so confused!
Finally saw the name difference, my solution was to rename directory to match your install label which appears to have worked.

Instruction label: gm_et_linux_64
New name: gmes_linux_64

Adding something like below would solve
mv gmes_linux_64 gm_et_linux_64

**Comment by mbnmbn00** [comment]
Thank you for the comment!
I will update the manual very soon (I need to test, though).
