### ISSUE TITLE
Error during FunGap docker image building

### ISSUE THREAD

**Issue by sajjadasaf** [CompSynBioLab-KoreaUniv/FunGAP#41]
Hello,
I need your help please.
I have run FunGAP two time before for some fungi annotation.
However, Now when want to run it i faced the following problem.
after the following command
docker build -t fungap .
All the downloading completed but at the end this error occur.
I am using linux mint please help me to solve this problem.

perl-yaml-1.27       | 40 KB     | ########## | 100% 
perl-digest-sha1-2.1 | 18 KB     | ########## | 100% 
perl-error-0.17027   | 20 KB     | ########## | 100% 
libgd-2.2.5          | 265 KB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting biopython
  Downloading https://files.pythonhosted.org/packages/3d/2f/d9df24de05d651c5e686ee8fea3afe3985c03ef9ca02f4cc1e7ea10aa31e/biopython-1.77.tar.gz (16.8MB)
    Complete output from command python setup.py egg_info:
    Biopython requires Python 3.6 or later. Python 2.7 detected.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cpiGuT/biopython/
The command '/bin/sh -c conda config --add channels bioconda/label/cf201901     && conda config --add channels conda-forge/label/cf201901     && conda install augustus rmblast maker hisat2 braker busco=3.0.2 blast pfam_scan     && pip install biopython bcbio-gff networkx markdown2 matplotlib     && cpanm Hash::Merge Logger::Simple Parallel::ForkManager YAML' returned a non-zero code: 1

**Comment by mbnmbn00** [comment]
Thank you for reporting this. I also recently realized the issue.
I will get back with the updated Docker build file. Thank you!

**Comment by sajjadasaf** [comment]
Thank you very much for your prompt reply.  I will be waiting for updated Docker build file.
Best Wishes

**Comment by shigdon** [comment]
Hello,

I am also interested in running Fungap with your docker image and experienced the same issue with the build. Just to get an idea on the time it will take for a fix and get an idea of what's going on, is the python 2.7 deprecation conflict with Biopython causing major issues with the majority of the scripts or are there specific steps or programs in the workflow that are written in python 2?

Thanks for your help!

**Comment by mbnmbn00** [comment]
Thank you for the report and comment!

Yes. FunGAP sticks to Python 2 (although I want to move on to 3) because `Maker` and `Hisat2` conflicts with Python 3. 

The good news is I found a way to bypass it. If you install Biopython via conda it will be installed.
```
conda install augustus rmblast busco=3.0.2 blast pfam_scan bowtie2 jellyfish salmon maker hisat2 biopython
```

Note I'm preparing for the new version of FunGAP which now can handle `--translation_table`, so BRAKER1 won't work, but BRAKER2 will. I am testing it right now.

**Comment by shigdon** [comment]
Absolutely! Thank you for the explanation of the existing conflicts you seem to have found a solution for.

If I understand correctly, are you suggesting to modify line 9 of the Dockerfile:

```
&& conda install augustus rmblast maker hisat2 braker busco=3.0.2 blast pfam_scan \
```

with the suggested `conda install` command you provided?

```
conda install augustus rmblast busco=3.0.2 blast pfam_scan bowtie2 jellyfish salmon maker hisat2 biopython
```

**Comment by mbnmbn00** [comment]
What you have to do for an easy fix is to delete `biopython` from pip and put it in a conda install line. I think that's the only thing you should do. 

Note I'm upgrading FunGAP so it uses BRAKER2, not 1.
Installing BRAKER2 via conda was another pain. The new version of FunGAP will not work with BRAKER1.
Docker and installation guide will be updated very soon (within this week).

If you install it by today, it should be fine. Otherwise, please wait until I get back with the update!

**Comment by choilab** [comment]
Dr. Min, you may have to manage the version control (in that you can store older version in a folder rather than overwriting the old version). That will protect the users of the older versions. What do you think?

**Comment by mbnmbn00** [comment]
Dear Prof. Choi,
Thank you for the comment!
In GitHub, that can be done by the "Release". I have been released stable versions of packages at
https://github.com/CompSynBioLab-KoreaUniv/FunGAP/releases

I might overwrite this version because it does not work anymore.
All the Best, Byoungnam

**Comment by mbnmbn00** [comment]
`Dockerfile` has been updated. Please download the most recent commit and try again!
The install and test-run have been done.
