### ISSUE TITLE
Can we use FunGAP for plant annotaion

### ISSUE THREAD

**Issue by sajjadasaf** [CompSynBioLab-KoreaUniv/FunGAP#43]
Dear mbnmbn00,
Can we use FunGAP for plant genome annotaion?
The second query is when the speceis is not available in augustus and it shows the following error
"We did not find any augustus species for the input" how can we solve this in the first step of docker.

Thank you for you help and support.

**Comment by mbnmbn00** [comment]
1)
The FunGAP has been intensely tested with fungal genomes. To be honest, I have zero experience with plant genomes.
But the scheme of FunGAP is to run Augustus, Braker, and Maker and integrate the gene models, so I think it should be okay with plant genomes because all three programs are designed for eukaryotic gene prediction.

You may put `--no_braker_fungus`, `--no_jaccard_clip`, and `--no_genemark_fungus` options and change `--max_intron` into the proper value (the default is 2000 bp).

Also, you may consider looking at each gene prediction from Augustus, Braker, and Maker, which will be located at `augustus_out`, `braker_out`, and `maker_out` directories respectively.

2)
There are several plant models in Augustus. You can use the closest one to your species.
Unfortunately, there's no option to turn off Augustus yet.

You may discuss with me if you want to exclude Augustus output from the filtering after running FunGAP with the closest species.
(Basically, we will make empty files of `augustus.gff3` and `augustus.faa` and FunGAP will use only Braker and Maker outputs for filtering.

Let me know if you have further questions! Please click the star button :)

**Comment by sajjadasaf** [comment]
Thank you very much for your kind reply. 
When i try to use closest plant species at the beginning step it shows the following error.

command:
/fungap_workspace# python /workspace/FunGAP/get_augustus_species.py   --genus_name "arabidopsis"   --email_address sajad..........@gmail.com

Out put:

Taxon: arabidopsis
Rank: genus
Lineage: cellular organisms; Eukaryota; Viridiplantae; Streptophyta; Streptophytina; Embryophyta; Tracheophyta; Euphyllophyta; Spermatophyta; Magnoliopsida; Mesangiospermae; eudicotyledons; Gunneridae; Pentapetalae; rosids; malvids; Brassicales; Brassicaceae; Camelineae
===
Suggestions:
We did not find any augustus species for the input "arabidopsis"

Yes, you are right if closest species not available at augustus  it will be great to run FunGAP with only Braker and Maker outputs.
I need your help in this regard and how may  i discuss with you here or through email ?

Once again thank you for your guidance.

**Comment by mbnmbn00** [comment]
Oh, I didn't put non-fungus species in the `get_augustus_species.py`. Is your species _Arabidopsis_?
Then, you can put `arabidopsis` in `--augustus_species`. In other words, you don't need to run `get_augustus_species.py`.

Here's a full list of Augustus species. http://augustus.gobics.de/binaries/README.TXT

```
identifier                               | species
-----------------------------------------|----------------------
human                                    | Homo sapiens
fly                                      | Drosophila melanogaster
arabidopsis                              | Arabidopsis thaliana
brugia                                   | Brugia malayi
aedes                                    | Aedes aegypti
tribolium                                | Tribolium castaneum
schistosoma                              | Schistosoma mansoni
tetrahymena                              | Tetrahymena thermophila
galdieria                                | Galdieria sulphuraria
maize                                    | Zea mays
toxoplasma                               | Toxoplasma gondii
caenorhabditis                           | Caenorhabditis elegans
(elegans)                                | Caenorhabditis elegans 
aspergillus_fumigatus                    | Aspergillus fumigatus
aspergillus_nidulans                     | Aspergillus nidulans
(anidulans)                              | Aspergillus nidulans
aspergillus_oryzae                       | Aspergillus oryzae
aspergillus_terreus                      | Aspergillus terreus
botrytis_cinerea                         | Botrytis cinerea
candida_albicans                         | Candida albicans
candida_guilliermondii                   | Candida guilliermondii
candida_tropicalis                       | Candida tropicalis
chaetomium_globosum                      | Chaetomium globosum
coccidioides_immitis                     | Coccidioides immitis
coprinus                                 | Coprinus cinereus
coprinus_cinereus                        | Coprinus cinereus
cryptococcus_neoformans_gattii           | Cryptococcus neoformans gattii
cryptococcus_neoformans_neoformans_B     | Cryptococcus neoformans neoformans
cryptococcus_neoformans_neoformans_JEC21 | Cryptococcus neoformans neoformans
(cryptococcus)                           | Cryptococcus neoformans
debaryomyces_hansenii                    | Debaryomyces hansenii
encephalitozoon_cuniculi_GB              | Encephalitozoon cuniculi
eremothecium_gossypii                    | Eremothecium gossypii
fusarium_graminearum                     | Fusarium graminearum
(fusarium)                               | Fusarium graminearium
histoplasma_capsulatum                   | Histoplasma capsulatum
(histoplasma)                            | Histoplasma capsulatum
kluyveromyces_lactis                     | Kluyveromyces lactis
laccaria_bicolor                         | Laccaria bicolor
lamprey                                  | Petromyzon marinus
leishmania_tarentolae                    | Leishmania tarentolae
lodderomyces_elongisporus                | Lodderomyces elongisporus
magnaporthe_grisea                       | Magnaporthe grisea
neurospora_crassa                        | Neurospora crassa
(neurospora)                             | Neurospora crassa
phanerochaete_chrysosporium              | Phanerochaete chrysosporium
(pchrysosporium)                         | Phanerochaete chrysosporium
pichia_stipitis                          | Pichia stipitis
rhizopus_oryzae                          | Rhizopus oryzae
saccharomyces_cerevisiae_S288C           | Saccharomyces cerevisiae
saccharomyces_cerevisiae_rm11-1a_1       | Saccharomyces cerevisiae
(saccharomyces)                          | Saccharomyces cerevisiae
schizosaccharomyces_pombe                | Schizosaccharomyces pombe
trichinella                              | Trichinella spiralis
ustilago_maydis                          | Ustilago maydis
(ustilago)                               | Ustilago maydis
yarrowia_lipolytica                      | Yarrowia lipolytica
nasonia                                  | Nasonia vitripennis
tomato                                   | Solanum lycopersicum
chlamydomonas                            | Chlamydomonas reinhardtii
amphimedon                               | Amphimedon queenslandica
pneumocystis                             | Pneumocystis jirovecii
```

**Comment by sajjadasaf** [comment]
Thank you very much for your help.
