### ISSUE TITLE
The final version of biopython supporting python 2.7 is 1.76 which should be specified when installing

### ISSUE THREAD

**Issue by dynamo07** [CompSynBioLab-KoreaUniv/FunGAP#45]
In the instruction, 
"pip install biopython bcbio-gff networkx markdown2 matplotlib" can be updated to
"pip install biopython==1.76 bcbio-gff networkx markdown2 matplotlib"

**Comment by mbnmbn00** [comment]
Oh. wow. I didn't know that!
I will update as you suggest. Thank you so much!!
