### ISSUE TITLE
RepeatModeler has finished abnormally. There is no consensi.fa.classified file.

### ISSUE THREAD

**Issue by sajjadasaf** [CompSynBioLab-KoreaUniv/FunGAP#46]
I have downloaded new docker version and run it successfully but at repeat modeler stage i am facing the below problem.

[07-22 02:23] DONE  running RepeatModeler
[ERROR] RepeatModeler has finished abnormally. There is no consensi.fa.classified file.
Traceback (most recent call last):
  File "/workspace/FunGAP/fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "/workspace/FunGAP/fungap.py", line 205, in main
    genome_assembly, output_dir, num_cores
  File "/workspace/FunGAP/fungap.py", line 367, in run_repeat_modeler
    check_call(command_args)
  File "/opt/conda/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/workspace/FunGAP/run_repeat_modeler.py', '--genome_assembly', '/fungap_workspace/K2_S20.fas', '--output_dir', '/fungap_workspace/fungap_out/repeat_modeler_out', '--log_dir', '/fungap_workspace/fungap_out/logs', '--num_cores', '8']' returned non-zero exit status 2

**Comment by mbnmbn00** [comment]
Can you show me the log file? it should be
`/fungap_workspace/fungap_out/logs/repeat_modeler/repeat_modeler`
If it is too long, you can attach the file, too!

**Comment by sajjadasaf** [comment]
Sorry  for late reply i rerun and found the same problem,
i am attaching file
[repeat_modeler.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/5017160/repeat_modeler.log)
[repeat_modeler.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/5017163/repeat_modeler.log)

**Comment by mbnmbn00** [comment]
They give exactly the same error which is:

```
ERROR from search engine (2)
       54% completed,  18:49:37 (hh:mm:ss) est. time remaining.
       54% completed,  18:49:36 (hh:mm:ss) est. time remaining.

ERROR from search engine (2)
       54% completed,ERROR from search engine (2)
```

The search engine we use is `RMBlast` so we can try the latest version of it.
You can download the program at http://www.repeatmasker.org/RMBlast.html

```
wget http://www.repeatmasker.org/rmblast-2.10.0+-x64-linux.tar.gz
tar -zxvf rmblast-2.10.0+-x64-linux.tar.gz
```

And configure again with this version.
Meanwhile, can you send me your FASTA file? I would like to test it myself, too.
mbnmbn00@gmail.com

**Comment by sajjadasaf** [comment]
I have sent you fasta file by email. 
please check it.

**Comment by mbnmbn00** [comment]
I ran RepeatModeler independently (outside FunGAP).
It also failed in the 4th round, so I made a consensi.fa.classified file using 3rd round output.

You can unzip this file and locate at repeat_modeler_out/RM*/
FunGAP will recognize the file and skip running RepeatModeler.

I notice that your assembly is very fragmented (~1.5 million scaffolds).
I strongly recommend using>1 kbp scaffolds which will be 90,401 scaffolds with 372 Mbp size.

Most eukaryotic genes are longer than 1 kbp so there's not much meaning in predicting genes on those short scaffolds.
Also, I think those scaffolds interfere with gene prediction as well as repeat-masking that you are experiencing now.

**Comment by mbnmbn00** [comment]
I will close this issue for now. Please feel free to re-open if necessary.
