### ISSUE TITLE
Error when installing funGAP

### ISSUE THREAD

**Issue by edward7498** [CompSynBioLab-KoreaUniv/FunGAP#47]
Hello, I am having some problem when installing funGAP. I get an error and the error said:

Reading package lists... Error!
E: Problem parsing dependency 21 of libmodule-build-tiny-perl:all=0.039-1
E: Error occurred while processing libmodule-build-tiny-perl (NewVersion2)
E: Problem with MergeList /var/lib/apt/lists/id.archive.ubuntu.com_ubuntu_dists_focal_universe_binary-i386_Packages
E: The package lists or status file could not be parsed or opened.

I am a very beginner linux user and I need help for this so I can install funGAP.

**Comment by mbnmbn00** [comment]
1) What command did you use when you got that error?

2) Do you use Ubuntu 18.04 LTS? or else?

3) Do you have a superuser privilege on your server? In other words, can you do `sudo` command?

**Comment by edward7498** [comment]
1. I am using this command:
![Screenshot from 2020-07-25 07-54-39](https://user-images.githubusercontent.com/68693662/88445381-6ffe6200-ce4c-11ea-872f-14ad19840204.png)

am I using a wrong command?

2. I use ubuntu 20.04

3. actually I can do sudo command but not for update and install things. Beside installing funGAP, I cannot update my ubuntu. The program will give me the same error when I try to update my ubuntu.

**Comment by mbnmbn00** [comment]
You need `git` first. I thought it's the default program when you install Ubuntu.
I see this post:
https://itsfoss.com/how-to-fix-problem-with-mergelist/

suggesting
```
sudo rm -r /var/lib/apt/lists/*
sudo apt-get clean && sudo apt-get update
```

After that,
```
sudo apt-get install git
```

or as what you did,
```
sudo apt install git
```

Then,
```
git clone https://github.com/CompSynBioLab-KoreaUniv/FunGAP.git
```

Also, check out the Docker version of FunGAP. Especially when you are a Linux beginner.
https://github.com/CompSynBioLab-KoreaUniv/FunGAP/blob/master/docker/Dockerfile

Please click the "star" button if it helped! :)

**Comment by edward7498** [comment]
I am very sorry for the late reply. 

Thank you so much for solving my problem with mergelist. 

Now I think I am going to use fungap from docker. but can you tell me what is the meaning of "workspaces are not available for Docker"?

And I also do not understand about "if was not for that I could have push FunGAP docker image ready for use in DockerHub". can you tell me more about it?

**Comment by mbnmbn00** [comment]
Is it the error message you got from building the Docker image?
@lmtani Hey Lucas, are you familiar with "workspaces are not available for Docker"?

For DockerHub, we couldn't upload the image into the DockerHub because of **GeneMark** which requires a license. You have to download the program with a proper license. That's why users should build the image themselves.

**Comment by lmtani** [comment]
Hello! I never saw this message about workspaces. I Googled it, and nothing showed up.. strange.

To install docker you can follow instructions on the official docs (https://docs.docker.com/get-docker/)

Or, if you just want to test it and are using Ubuntu, I think the fastest way to get it working is:

`sudo apt update && sudo apt install docker.io`

You can test if docker is running with `sudo docker ps`. If you see no error message then it is ok.

Then go to `docker` directory of this repository ([following this instructions to clone](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/issues/47#issuecomment-663789954)) and download the [GeneMark files](http://topaz.gatech.edu/GeneMark/license_download.cgi) (binary and key of the `GeneMark-ES/ET/EP ver 4.59_lic` option). After that you can build the image with:

`sudo docker build -t name-you-want-for-fungap-image:latest .`

To use the image with your files you could follow the instructions of this link:

https://github.com/CompSynBioLab-KoreaUniv/FunGAP/tree/master/docker#enter-docker-image-and-execute-fungap-pipeline

Please let me know if you have problems building the Docker image. It can take some time to configure all dependencies, but you'll have to build it just once. With my internet conection, it took about 25 minutes.

**Comment by edward7498** [comment]
@mbnmbn00 I am sorry for the misunderstanding. It is not an error that I get when installing funGAP in my ubuntu. What I mean is I do not understand about the message "Although we recommend using Docker, some workspaces are not available for Docker (e.g., HPC)". Is that means it will be better to use funGAP in anaconda environment rather than in docker? 

@lmtani Thank you so much for the instruction. I will try it and once I encounter an error I will tell you. But I have got a question. I saw that if I want to install GeneMark, I need to register myself (like "name", "institution", etc). Once I finished, I will get "gmes_linux_64.tar.gz and gm_key_64.gz" right? And is the genemark free to download?

**Comment by edward7498** [comment]
I am sorry for giving another reply. I am trying to install git but I got another problem like this.
![Screenshot from 2020-07-29 17-08-01](https://user-images.githubusercontent.com/68693662/88788012-f5707200-d1be-11ea-8fa6-d9e416bf5170.png)

Any idea to solve this?

**Comment by edward7498** [comment]
I am sorry for replying again. I am having a problem in making the image in docker. I got a problem like this.
![Screenshot from 2020-07-29 17-48-10](https://user-images.githubusercontent.com/68693662/88791624-4040b880-d1c4-11ea-8697-bf87e9ee6402.png)
![Screenshot from 2020-07-29 17-48-13](https://user-images.githubusercontent.com/68693662/88791629-4171e580-d1c4-11ea-9fe6-bb7f723f9b18.png)

Any idea about this?

**Comment by lmtani** [comment]
@edward7498 in your docker command you forgot "." at the end. It is necessary.

`sudo docker build -t name-you-want-for-fungap-image:latest .`

Sudo is not necessary only if you have followed the post-installation instructions from the docker documentation.

**Comment by edward7498** [comment]
@lmtani Thank you so much for the help. the fungap image in docker is ready but I am getting confuse because while I am running the docker build command, suddenly the program update the anaconda environment so it takes longer time. Is it okay? can I still running funGAP in docker?

and can you tell me where I can download FASTQ files for running funGAP?

**Comment by mbnmbn00** [comment]
That's normal to see the anaconda environment! It takes time, yes. But the only first time of the build (you don't need to build again).

Here's how to download a test dataset.

5. Test dataset
You can download yeast (_S. cerevisiae_) genome assembly (FASTA) and RNA-seq reads (two FASTQs) from NCBI for testing FunGAP.

# Download RNA-seq reads using SRA toolkit (https://www.ncbi.nlm.nih.gov/sra/docs/toolkitsoft/)
# Parameter -X indicates that we only need <int> pairs from the dataset.
fastq-dump -X 3000000 -I --split-files SRR1198667

# Download assembly
wget ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/146/045/GCF_000146045.2_R64/GCF_000146045.2_R64_genomic.fna.gz
It took about 9 hours by dual Intel(R) Xeon(R) CPU E5-2670 v3 with 40 CPU cores.

**Comment by mbnmbn00** [comment]
I close it for now. But feel free to reopen and ask questions.
