### ISSUE TITLE
maker run4 fails

### ISSUE THREAD

**Issue by qhelleu** [CompSynBioLab-KoreaUniv/FunGAP#5]
Hi,
I try to run the fungap pipeline, but each time the fourth maker run fails.
I get the following error message:
[10-22 07:42] DONE  training run3 & running maker run4
[Run] /software/SequenceAnalysis/GenePrediction/maker/2.31.9/bin/gff3_merge -g -n -d /scratch/local/yearly/qhelleu/annotation/Sb_fungap/Out_Annot/gpre_maker/paired/maker_run4/Sinv_smallb.maker.output/Sinv_smallb_master_datastore_index.log
[Run] /software/SequenceAnalysis/GenePrediction/maker/2.31.9/bin/fasta_merge -d /scratch/local/yearly/qhelleu/annotation/Sb_fungap/Out_Annot/gpre_maker/paired/maker_run4/Sinv_smallb.maker.output/Sinv_smallb_master_datastore_index.log
Traceback (most recent call last):
  File "/software/UHTS/Analysis/fungap/1.0/bin/run_maker.py", line 755, in <module>
    main(sys.argv[1:])
  File "/software/UHTS/Analysis/fungap/1.0/bin/run_maker.py", line 307, in main
    maker_bin
  File "/software/UHTS/Analysis/fungap/1.0/bin/run_maker.py", line 667, in collect_result_final
    copyfile(merged_faa, output_faa)
  File "/software/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/scratch/local/yearly/qhelleu/annotation/Sb_fungap/Out_Annot/gpre_maker/paired/maker_run4/Sinv_smallb.all.maker.proteins.fasta'
Traceback (most recent call last):
  File "/software/UHTS/Analysis/fungap/1.0/bin/fungap.py", line 815, in <module>
    main(sys.argv[1:])
  File "/software/UHTS/Analysis/fungap/1.0/bin/fungap.py", line 300, in main
    trinity_asms, config_file, no_genemark_fungus
  File "/software/UHTS/Analysis/fungap/1.0/bin/fungap.py", line 514, in run_maker
    check_call(command_args)
  File "/software/lib64/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/software/UHTS/Analysis/fungap/1.0/bin/run_maker.py', '-i', '/scratch/local/yearly/qhelleu/annotation/Sb_fungap/Sinv_smallb.fasta', '-r', '/scratch/local/yearly/qhelleu/annotation/Sb_fungap/Out_Annot', '-a', 'camponotus_floridanus', '-p', 'smallb_annot', '-P', '/scratch/local/yearly/qhelleu/annotation/Sb_fungap/seq_dir/prot_db.faa', '-c', '24', '-R', '/scratch/local/yearly/qhelleu/annotation/Sb_fungap/Out_Annot/repeat_modeler/RM_43026.ThuOct41759492018/consensi.fa.classified', '-e', '/scratch/local/yearly/qhelleu/annotation/Sb_fungap/Out_Annot/trans_trinity/trinity_paired/Trinity_paired.fasta', '-C', '/scratch/local/yearly/qhelleu/annotation/Sb_fungap/Out_Annot/fungap_exe.config']' returned non-zero exit status 1

How can I solve this issue?
Thanks.

**Comment by mbnmbn00** [comment]
Can you show me the content of logs/maker_PREFIX/maker_PREFIX_run4.log?

**Comment by qhelleu** [comment]
Hi,
In fact all the maker runs but the first fail. I think It is connected with snap.
Here a sample of the log from one of the three failed runs:

Argument "2.56_01" isn't numeric in numeric ge (>=) at /software/lib64/perl5/vendor_perl/forks.pm line 1570.
STATUS: Parsing control files...
STATUS: Processing and indexing input FASTA files...
STATUS: Setting up database for any GFF3 input...
A data structure will be created for you at:
/scratch/local/yearly/qhelleu/annotation/Sb_fungap/Out_Annot/gpre_maker/paired/maker_run2/Sinv_smallb.maker.output/Sinv_smallb_datastore
To access files for individual sequences use the datastore index:
/scratch/local/yearly/qhelleu/annotation/Sb_fungap/Out_Annot/gpre_maker/paired/maker_run2/Sinv_smallb.maker.output/Sinv_smallb_master_datastore_index.log
STATUS: Now running MAKER...
examining contents of the fasta file and run log
--Next Contig--
#---------------------------------------------------------------------
Now starting the contig!!
SeqID: chr1
Length: 28460331
#---------------------------------------------------------------------
setting up GFF3 output and fasta chunks
doing repeat masking
collecting blastx repeatmasking
processing all repeats
in cluster::shadow_cluster...
...finished clustering.
...
...
preparing masked sequence
preparing ab-inits
running  snap.
#--------- command -------------#
Widget::snap:
/software/SequenceAnalysis/GenePrediction/snap/2013.11.29/bin/snap /scratch/local/yearly/qhelleu/annotation/Sb_fungap/Out_Annot/gpre_maker/paired/maker_run1/snp_training/snap_hmm_v1.hmm /tmp/maker_FPKK7y/chr1.abinit_masked.0 > /tmp/maker_FPKK7y/chr1.abinit_masked.0.snap_hmm_v1%2Ehmm.snap
#-------------------------------#
ZOE ERROR (from /software/SequenceAnalysis/GenePrediction/snap/2013.11.29/bin/snap): error checking HMM file
ZOE library version 2017-03-01
ERROR: Snap failed
--> rank=NA, hostname=dee-serv08.vital-it.ch
ERROR: Failed while preparing ab-inits
ERROR: Chunk failed at level:0, tier_type:2
FAILED CONTIG:chr1
ERROR: Chunk failed at level:4, tier_type:0
FAILED CONTIG:chr1
examining contents of the fasta file and run log

Apparently snap can't find the HMM file. Do you know how I can solve that?
Thanks.

**Comment by mbnmbn00** [comment]
I think it is related with SNAP installation. It seems that you installed SNAP separately.
The easiest way to solve this is that install SNAP with Maker.

This may help you install SNAP with Maker.
```
cd $HOME/FunGAP/external/maker/src
sudo apt-get install libpq-dev
perl Build.PL
sudo ./Build installdeps
./Build installexes
./Build install
```

Also, make sure that you are using SNAP installed by Maker, not your own one.
You can check this by:
```which snap```

**Comment by robinengler** [comment]
Hi @mbnmbn00,
I'm working with @qhelleu trying to get FunGAP to run on our compute cluster. I read your last post about using SNAP that comes with FunGAP, but there is no "external/maker" repository when I clone the current FunGAP project ?
Could you let me know what I'm missing here ?
Thanks.

**Comment by mbnmbn00** [comment]
Maker program is a license-protected software, so I couldn't include this in `external/`. Users should install separately. Also, FunGAP expects snap is installed inside `exe/` directory of Maker.

I believe you installed the Maker separately. Then can you check if there is snap directory within $MAKER_PATH/exe? If there isn't, check your snap in $PATH environment by typing `which snap`, if something appears, please unlink that snap and do above steps for snap to be installed within `$MAKER_PATH/exe` directory. Please let me know if you need any help.

**Comment by mbnmbn00** [comment]
I have a plan to develop a new version of FunGAP based on Anaconda environment. Current program needs a lot of dependencies that sometimes bother users to use.

**Comment by robinengler** [comment]
Hi @mbnmbn00,
Sorry I'm back ;-)
I still couldn't get FunGAP to work, although I feel like I made some progress.
What I did so far is to use the SNAP version that is found here (https://github.com/KorfLab/SNAP), and I modified the paths in "run_maker.py" for fathom_bin, forge_bin and hmm_assembler_bin so that they point to the correct location where I have these SNAP binaries. 
The executable are now found, but I'm still getting an error:

```
ZOE ERROR:
error checking HMM file
```

In your previous message you mentioned that I should use the version of SNAP that comes with Maker. I have Maker version 2.31.9 installed (taken from http://www.yandell-lab.org/software/maker.html), but I don't see that it contains any of the ```fathom```, ```forge``` or ```hmm-assembler``` binaries.

Could you tell me which version of Maker are you using ? Do you have to do something special during the build to get the ```fathom```, ```forge``` and ```hmm-assembler``` binaries ?

As always you help with this is much appreciated. Thanks,
Robin

**Comment by mbnmbn00** [comment]
I'm using Maker 2.31.8 version. The installation of Maker doesn't bring SNAP automatically.
SNAP will be installed by following procedure:

```
cd $HOME/FunGAP/external/maker/src
sudo apt-get install libpq-dev
perl Build.PL
sudo ./Build installdeps
./Build installexes
./Build install
```

But I think if you already have SNAP in the $PATH, this doesn't install SNAP on your `$MAKER/exe/`.
Please detach `snap` from your $PATH and do the above commands. And make sure SNAP in `ext/` directory of the Maker.

**Comment by robinengler** [comment]
Hi @mbnmbn00,
Sorry I'm back ;-)
I still couldn't get FunGAP to work, although I feel like I made some progress.
What I did so far is to use the SNAP version that is found here (https://github.com/KorfLab/SNAP), and I modified the paths in "run_maker.py" for fathom_bin, forge_bin and hmm_assembler_bin so that they point to the correct location where I have these SNAP binaries. 
The executable are now found, but I'm still getting an error:

```
ZOE ERROR:
error checking HMM file
```

In your previous message you mentioned that I should use the version of SNAP that comes with Maker. I have Maker version 2.31.9 installed (taken from http://www.yandell-lab.org/software/maker.html), but I don't see that it contains any of the ```fathom```, ```forge``` or ```hmm-assembler``` binaries.

Could you tell me which version of Maker are you using ? Do you have to do something special during the build to get the ```fathom```, ```forge``` and ```hmm-assembler``` binaries ?

As always you help with this is much appreciated. Thanks,
Robin

**Comment by mbnmbn00** [comment]
I upgraded the FunGAP to v1.1.0. In this version users will install dependencies via **Anaconda** as much as possible so as to reduce installation problems. Can you try the new version and let me know if you have further issues?

https://github.com/CompSynBioLab-KoreaUniv/FunGAP/blob/master/INSTALL.md
