### ISSUE TITLE
docker installation error 137 

### ISSUE THREAD

**Issue by swelbo** [CompSynBioLab-KoreaUniv/FunGAP#50]
Hello, 

Using your instructions to build the FunGAP docker image

```
# 4. Build the image
docker build -t fungap .
```
Returns this error: 
```
repeatmasker-4.0.7   | 202.3 MB  | #########9 | 100% Killed
The command '/bin/sh -c conda config --add channels bioconda/label/cf201901     && conda config --add channels conda-forge/label/cf201901     && conda install augustus rmblast maker hisat2 braker busco=3.0.2 blast pfam_scan biopython     && pip install bcbio-gff networkx markdown2 matplotlib     && cpanm Hash::Merge Logger::Simple Parallel::ForkManager YAML' returned a non-zero code: 137
```

Have you seen this error before and do you have a way of circumnavigating it? 

Many thanks, 

Thomas

**Comment by mbnmbn00** [comment]
I just launched Amazon EC2 (i.e., fresh Ubuntu) and tested the installation. It ran fine.

One thing I notice is `Killed`. I think it was killed from outside. Do you think it's possible somebody can kill your job?
Or, you may not have enough space.

Please build again and see if it happens at the same place. You may test with another machine if you have.

Let me know what you think!

**Comment by swelbo** [comment]
Thanks for the reply. I re-ran and the same thing happened. I will try another machine and get back to you.

**Comment by swelbo** [comment]
Hey - I've installed on our HPC via anaconda as per your guidelines in INSTALL.MD. The installation was fine and it is now running on our HPC via qsub. I have a separate question about Augustus species for non-model but will contact you directly regarding that if that is OK. 

Could the docker error I mentioned before be due to me using macOS?

**Comment by mbnmbn00** [comment]
Sure. Send me an e-mail at mbnmbn00@gmail.com
I will test at macOS and let you know how it goes!

**Comment by mbnmbn00** [comment]
I couldn't test it because I do not have enough Internet access.
@lmtani, do you have any idea about this? The Docker version of FunGAP seems not to work in Mac OS X.

If you can confirm, we may mention it in the `README.md`.

**Comment by lmtani** [comment]
@mbnmbn00 I do not have a Mac OS X to test it but I'll make a try on Windows 10.

**Comment by mbnmbn00** [comment]
@lmtani Thanks! Whenever I can get back to work (it will be next year, though), I will test it myself.
