### ISSUE TITLE
Error in maker step

### ISSUE THREAD

**Issue by swelbo** [CompSynBioLab-KoreaUniv/FunGAP#51]
Hi 

I'm getting an error in the maker step

my datastore_index.log file reads - 

```
Supercontig_1.1 species_1_supercontigs_datastore/65/0C/Supercontig_1.1/  STARTED
Supercontig_1.1         FAILED
Supercontig_1.2 species_1_supercontigs_datastore/A1/AD/Supercontig_1.2/  STARTED
Supercontig_1.2         FAILED
etc... 

```
- and continuously cycles through the job until the job is killed due to walltime.

Attached is the maker log file. 
[maker_reads_run1.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/5182899/maker_reads_run1.log)

Can you identify an issue here? 

Cheers 

Thomas

**Comment by swelbo** [comment]
Just to add to this. When I run FunGAP without submitting to the cluster, this is the maker_reads_run1.log output 

`Possible precedence issue with control flow operator at /rds/general/user/tsewell/home/anaconda2/envs/fungap3/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 845.
STATUS: Parsing control files...
ERROR: Temporary directory set to an NFS location.
TMP=/rds/general/ephemeral/user/tsewell/ephemeral
The temporary directory in MAKER is specifically for
operations that are not NFS-safe. You must set TMP
to a locally mounted directory such as /tmp or add
--ignore_nfs_tmp to the maker command line to
override this error message.

--> rank=NA, hostname=login-7
maker_reads_run1.log (END)`

**Comment by mbnmbn00** [comment]
Hi, I'm not sure how many options we have, but when I type the following command,
```
> echo $TMPDIR
/tmp
```

I got `/tmp`. I assume that you will get `/rds/general/ephemeral/user/tsewell/ephemeral`.
So you might change the `TMPDIR` variable by typing,
```
export TMPDIR=/whereever/not/nfs/location
```

Let me know if it doesn't work.

**Comment by mbnmbn00** [comment]
I'm closing this issue. Please re-open whenever you want!
