### ISSUE TITLE
[ERROR] Invalid BUSCO DATASET

### ISSUE THREAD

**Issue by sajjadasaf** [CompSynBioLab-KoreaUniv/FunGAP#56]
I installed Fungap conda version and try to run the example but it shows the following error.

/FunGAP$ python fungap.py   --genome_assembly GCF_000146045.2_R64_genomic.fna   --trans_read_1 SRR1198667_1.fastq   --trans_read_2 SRR1198667_2.fastq   --augustus_species saccharomyces_cerevisiae_S288C   --busco_dataset fungi_odb10   --sister_proteome prot_db.faa   --num_cores 8

============ New Run 2020-11-06 01:55:11.619562 ============
Check input files...
TRANS_READ_FILES is ok...
GENOME_ASSEMBLY is ok...
SISTER_PROTEOME is ok...
[ERROR] Invalid BUSCO DATASET: fungi_odb10. Run busco --list-datasets to get a full list available datasets

**Comment by mbnmbn00** [comment]
Hello,

Can you show me the output of:
```
busco --list-datasets
```
It is possible the BUSCO hasn't been installed properly yet.
Can you also show me the output of:
```
> conda list | grep busco
# packages in environment at /global/projectb/scratch/mbnmbn00/tools/conda/busco:
busco                     4.1.2                 py37r40_0    bioconda
```
4.1.2 is a stable version tested several times by myself.

**Comment by sajjadasaf** [comment]
Thank you for your reply.
I have solved the problem by installing Busco.

**Comment by mbnmbn00** [comment]
Glad to hear that! :)
