### ISSUE TITLE
Contributing with singularity container

### ISSUE THREAD

**Issue by nathaliagg** [CompSynBioLab-KoreaUniv/FunGAP#59]
Hello! I'd like to make a contribution. I use FunGAP on an HPC, so I can't use docker. I wrote a singularity recipe file that works just like your current Dockerfile. I think this might be useful for people working on a HPC. Would you be okay with my contribution? If so, would a PR be ok, or do you have another preferred way?

**Comment by mbnmbn00** [comment]
Pull Requests will work perfectly!
Thanks for the contribution :)
