### ISSUE TITLE
get_augustus_species.py not downloading anything.

### ISSUE THREAD

**Issue by Lamm-a** [CompSynBioLab-KoreaUniv/FunGAP#61]
When giving the `get_augustus_species.py` script either the genus of my genome or the closest Augustus model nothing gets downloaded and i get this as output:
```

get_augustus_species.py --genus_name termitomyces --email_address <some_email>

Validating input genus name...

===
Taxon: termitomyces
Rank: genus
Lineage: cellular organisms; Eukaryota; Opisthokonta; Fungi; Dikarya; Basidiomycota; Agaricomycotina; Agaricomycetes; Agaricomycetidae; Agaricales; Lyophyllaceae
===

Suggestions:
We found them in order level: Agaricales
coprinus_cinereus
laccaria_bicolor
```

Am I doing something wrong here?

**Comment by mbnmbn00** [comment]
Hello,

That's expected behavior!! It doesn't download anything but suggests which Augustus parameter you will use.
So you will put either "coprinus_cinereus" or "laccaria_bicolor" in your parameter.
