### ISSUE TITLE
Braker failing 

### ISSUE THREAD

**Issue by swelbo** [CompSynBioLab-KoreaUniv/FunGAP#63]
Hello (again..) 

Revisiting this after sometime out and the Braker step is failing. 

fungap_out/logs/braker_SRR3707957.logs reads: 

```
# Thu Feb 18 07:53:46 2021: Log information is stored in file /home/thomas/Documents/fungap/test/fungap_out/braker_out/SRR3707957/braker.log
ln: failed to create symbolic link '/home/thomas/Documents/fungap/test/fungap_out/braker_out/SRR3707957/traingenes.gtf': File exists
ERROR in file /home/thomas/anaconda3/envs/fungap/bin/braker.pl at line 6918
failed to execute: ln -s /home/thomas/Documents/fungap/test/fungap_out/braker_out/SRR3707957/GeneMark-ET/genemark.gtf /home/thomas/Documents/fungap/test/fungap_out/braker_out/SRR3707957/traingenes.gtf!
```

the last line in  braker_out/SRR3707957/braker.log reads: 

```
#                               TRAIN AUGUSTUS                                     
#**********************************************************************************
# Thu Feb 18 08:29:34 2021: training AUGUSTUS
# Thu Feb 18 08:29:34 2021: creating softlink from /home/thomas/Documents/fungap/test/fungap_out/braker_out/SRR3707957/GeneMark-ET/genemark.gtf to /home/thomas/Documents/fungap/test/fungap_out/braker_out/SRR3707957/traingenes.gtf.
ln -s /home/thomas/Documents/fungap/test/fungap_out/braker_out/SRR3707957/GeneMark-ET/genemark.gtf /home/thomas/Documents/fungap/test/fungap_out/braker_out/SRR3707957/traingenes.gtf
```

Any idea what the issue is here? It worked fine a few months back, and i haven't changed anything (installed on its own VM)

Cheers 

Thomas
[braker_SRR3707957.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/6001408/braker_SRR3707957.log)
[braker.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/6001409/braker.log)
[fungap.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/6001411/fungap.log)

**Comment by mbnmbn00** [comment]
Hello,

How did you run the FunGAP? Did you run on existing directories?
Because the error message complains about an existing file:
```
/home/thomas/Documents/fungap/test/fungap_out/braker_out/SRR3707957/traingenes.gtf
```

You may delete the Braker directory and run it again.
```
rm -r /home/thomas/Documents/fungap/test/fungap_out/braker_out/
```

Let me know if you have any further questions!

**Comment by swelbo** [comment]
Thanks for the reply. 

Sorry, annoyingly i did on this occasion. It did not work before however when i deleted braker_out to re run. I will delete the folder and reproduce the error and get back to you. 

Cheers

**Comment by mbnmbn00** [comment]
Sounds good!! Let me know how it goes!

**Comment by swelbo** [comment]
So it seems to get stuck at: fixing AUGUSTUS genes with in frame stop codons. Attached are the logs.

[braker_SRR3707957.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/6008522/braker_SRR3707957.log)
[braker.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/6008526/braker.log)

**Comment by mbnmbn00** [comment]
I found this site:
https://github.com/Gaius-Augustus/Augustus/issues/82

It seems it's related to Augustus version. What Augustus version are you using?

**Comment by swelbo** [comment]
OK - Its version 3.3.3. That seems to be the version they had issue with.

**Comment by mbnmbn00** [comment]
Okay. Augustus 3.4.0 conda version is available.
https://anaconda.org/bioconda/augustus

1)
Could you try the 3.4.0 version?
(Sorry I'm so busy for now, but I will test myself and fix the manual as soon as possible)

2)
Or, you could install the GitHub version of the Augustus and point the configure to the new installation.
In the FunGAP directory, there's a file named `fungap.conf` that you can edit the paths.

Let me know if these don't work!

**Comment by swelbo** [comment]
No worries! Thanks for you help :).

I updated to Augustus 3.4.0 using the conda link you provided. It updated a bunch of other dependencies but didn't keep track of those. 

FunGAP ran without error. I'll run with my actual de novo assemblies now.

Thanks again!

**Comment by swelbo** [comment]
Hey -

 I'm getting this error when trying to generate the config file : - 

``[ERROR] Augustus version is not 3.3.3. Check with "/rds/general/user/tsewell/home/anaconda3/envs/fungap/bin/augustus --version"``

output 

AUGUSTUS (3.4.0) is a gene prediction tool.
Sources and documentation at https://github.com/Gaius-Augustus/Augustus

**Comment by mbnmbn00** [comment]
Oh, sorry for the super late reply.
FunGAP has been updated in May 2021.
Please try installing the FunGAP again!

**Comment by swelbo** [comment]
Sorry i did get this working but have been side tracked with another
project! I will return to FunGAP soon :)
