### ISSUE TITLE
BRAKER error

### ISSUE THREAD

**Issue by sajjadasaf** [CompSynBioLab-KoreaUniv/FunGAP#68]
Could you kindly resolve the following issue.

[06-10 07:52] START: wrapper_run_augustus
[Wrapper] /workspace/FunGAP/run_augustus.py --masked_assembly /fungap_workspace/fungap_out/maker_out/masked_assembly.fasta --species aspergillus_oryzae --output_dir /fungap_workspace/fungap_out/augustus_out --log_dir /fungap_workspace/fungap_out/augustus_out/logs
[06-10 07:52] START: Augustus
[Run] /opt/conda/bin/augustus --uniqueGeneId=true --singlestrand=true --gff3=on /fungap_workspace/fungap_out/maker_out/masked_assembly.fasta --species=aspergillus_oryzae --stopCodonExcludedFromCDS=false --softmasking=1 > /fungap_workspace/fungap_out/augustus_out/augustus.gff3
[06-10 08:27] DONE : Augustus
[06-10 08:27] DONE : wrapper_run_augustus

[06-10 08:27] START: wrapper_run_braker
[Wrapper] /workspace/FunGAP/run_braker.py --masked_assembly /fungap_workspace/fungap_out/maker_out/masked_assembly.fasta --bam_files /fungap_workspace/fungap_out/hisat2_out/SRR12647642.bam --output_dir /fungap_workspace/fungap_out/braker_out --log_dir /fungap_workspace/fungap_out/logs --num_cores 1 --fungus
[06-10 08:27] START: BRAKER
[Run] /opt/conda/bin/braker.pl --fungus --softmasking --cores=1 --genome=/fungap_workspace/fungap_out/maker_out/masked_assembly.fasta.adjusted --bam=/fungap_workspace/fungap_out/hisat2_out/SRR12647642.bam --species=SRR12647642 --gff3 --AUGUSTUS_CONFIG_PATH=/opt/conda/bin/../config --BAMTOOLS_PATH=/opt/conda/bin --GENEMARK_PATH=/workspace/FunGAP/external/gmes_linux_64 --SAMTOOLS_PATH=/opt/conda/bin --workingdir=/fungap_workspace/fungap_out/braker_out/SRR12647642  --translation_table=1 --AUGUSTUS_BIN_PATH=/opt/conda/bin > /fungap_workspace/fungap_out/logs/braker_SRR12647642.log 2>&1
[Run] mv /fungap_workspace/fungap_out/braker_out/SRR12647642/braker.gff3 /fungap_workspace/fungap_out/braker_out/SRR12647642/braker_SRR12647642.gff3
mv: cannot stat '/fungap_workspace/fungap_out/braker_out/SRR12647642/braker.gff3': No such file or directory
[Run] /opt/conda/bin/getAnnoFastaFromJoingenes.py -g /fungap_workspace/fungap_out/maker_out/masked_assembly.fasta.adjusted -o /fungap_workspace/fungap_out/braker_out/SRR12647642/braker_SRR12647642 -t 1 -3 /fungap_workspace/fungap_out/braker_out/SRR12647642/braker_SRR12647642.gff3
Traceback (most recent call last):
  File "/opt/conda/bin/getAnnoFastaFromJoingenes.py", line 121, in <module>
    with open(args.gff3, "r") as gff3_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/fungap_workspace/fungap_out/braker_out/SRR12647642/braker_SRR12647642.gff3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/getAnnoFastaFromJoingenes.py", line 137, in <module>
    print("Error: Failed to open file " + args.gtf + "!")
TypeError: can only concatenate str (not "NoneType") to str
[Run] mv /fungap_workspace/fungap_out/braker_out/SRR12647642/braker_SRR12647642.aa /fungap_workspace/fungap_out/braker_out/SRR12647642/braker_SRR12647642.faa
mv: cannot stat '/fungap_workspace/fungap_out/braker_out/SRR12647642/braker_SRR12647642.aa': No such file or directory
[ERROR] Braker failed. Check the log: /fungap_workspace/fungap_out/logs/braker_SRR12647642.log
Traceback (most recent call last):
  File "/workspace/FunGAP/fungap.py", line 826, in <module>
    main()
  File "/workspace/FunGAP/fungap.py", line 205, in main
    d_path, logger
  File "/workspace/FunGAP/fungap.py", line 496, in run_braker
    check_call(command_args)
  File "/opt/conda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/workspace/FunGAP/run_braker.py', '--masked_assembly', '/fungap_workspace/fungap_out/maker_out/masked_assembly.fasta', '--bam_files', '/fungap_workspace/fungap_out/hisat2_out/SRR12647642.bam', '--output_dir', '/fungap_workspace/fungap_out/braker_out', '--log_dir', '/fungap_workspace/fungap_out/logs', '--num_cores', '1', '--fungus']' returned non-zero exit status 1.
root@ec1a72019399:/fungap_workspace# 

[braker_SRR12647642.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/6629992/braker_SRR12647642.log)
[run_braker.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/6629994/run_braker.log)
[fungap.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/6629996/fungap.log)

**Comment by mbnmbn00** [comment]
The important message is: `$AUGUSTUS_SCRIPTS_PATH not set!`
It seems you are using Docker version of FunGAP. Can you tell me when you installed the FunGAP?
We have a recent update (v1.1.1). Anyway, I will try to reproduce the error this weekend and let's see how it goes.

@lmtani Do you recognize this error??

**Comment by lmtani** [comment]
It is not familiar...  I'll also look into it.

**Comment by sajjadasaf** [comment]
Please check this error I reinstall the new version but still showing the same error.

**Comment by lmtani** [comment]
I just checked and could not find the problem. I rebuild my FunGAP Docker image and ran the example. The pipeline ended without errors.

@sajjadasaf , is your fungap.conf the same as the one included in the docker directory?

https://github.com/CompSynBioLab-KoreaUniv/FunGAP/blob/62403c58ae61ea644d089f028100b990a85f64d4/docker/fungap.conf#L25

In your braker log, there is this path for augustus scripts: `--AUGUSTUS_CONFIG_PATH=/opt/conda/bin/../config`

But inspecting FunGAP code I think it should be `/opt/conda/bin` 

https://github.com/CompSynBioLab-KoreaUniv/FunGAP/blob/7c2d945ba2733d799e82f48c08f60873a4067919/run_braker.py#L143

**Comment by mbnmbn00** [comment]
I installed a Docker version of FunGAP in a fresh Ubuntu and ran successfully without issues.
And the path was as Lucas said,
```
# echo $AUGUSTUS_SCRIPTS_PATH
/opt/conda/bin/
```

Hope it helps to resolve your issue.

**Comment by sajjadasaf** [comment]
I reinstall Fungap and still showing same error. I Downlaoded new genmark keys and uninstall anaconda3 from my system. I am using LInux Mint 20 base on ubuntue 20. Is it possible that docker fungap faced problem with anaconda or miniconda install on system? I have confirmed that augustus location was same as you mentioned above.


[Run] /opt/conda/bin/braker.pl --fungus --softmasking --cores=8 --genome=/fungap_workspace/fungap_out/maker_out/masked_assembly.fasta.adjusted --bam=/fungap_workspace/fungap_out/hisat2_out/SRR12647642.bam --species=SRR12647642 --gff3 --AUGUSTUS_CONFIG_PATH=/opt/conda/bin/../config --BAMTOOLS_PATH=/opt/conda/bin --GENEMARK_PATH=/workspace/FunGAP/external/gmes_linux_64 --SAMTOOLS_PATH=/opt/conda/bin --workingdir=/fungap_workspace/fungap_out/braker_out/SRR12647642  --translation_table=1 --AUGUSTUS_BIN_PATH=/opt/conda/bin > /fungap_workspace/fungap_out/logs/braker_SRR12647642.log 2>&1
[Run] mv /fungap_workspace/fungap_out/braker_out/SRR12647642/braker.gff3 /fungap_workspace/fungap_out/braker_out/SRR12647642/braker_SRR12647642.gff3
mv: cannot stat '/fungap_workspace/fungap_out/braker_out/SRR12647642/braker.gff3': No such file or directory
[Run] /opt/conda/bin/getAnnoFastaFromJoingenes.py -g /fungap_workspace/fungap_out/maker_out/masked_assembly.fasta.adjusted -o /fungap_workspace/fungap_out/braker_out/SRR12647642/braker_SRR12647642 -t 1 -3 /fungap_workspace/fungap_out/braker_out/SRR12647642/braker_SRR12647642.gff3
Traceback (most recent call last):
  File "/opt/conda/bin/getAnnoFastaFromJoingenes.py", line 120, in <module>
    with open(args.gff3, "r") as gff3_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/fungap_workspace/fungap_out/braker_out/SRR12647642/braker_SRR12647642.gff3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/getAnnoFastaFromJoingenes.py", line 136, in <module>
    print("Error: Failed to open file " + args.gtf + "!")
TypeError: can only concatenate str (not "NoneType") to str
[Run] mv /fungap_workspace/fungap_out/braker_out/SRR12647642/braker_SRR12647642.aa /fungap_workspace/fungap_out/braker_out/SRR12647642/braker_SRR12647642.faa
mv: cannot stat '/fungap_workspace/fungap_out/braker_out/SRR12647642/braker_SRR12647642.aa': No such file or directory
[ERROR] Braker failed. Check the log: /fungap_workspace/fungap_out/logs/braker_SRR12647642.log
Traceback (most recent call last):
  File "/workspace/FunGAP/fungap.py", line 839, in <module>
    main()
  File "/workspace/FunGAP/fungap.py", line 212, in main
    braker_gff3s, braker_faas = run_braker(
  File "/workspace/FunGAP/fungap.py", line 509, in run_braker
    check_call(command_args)
  File "/opt/conda/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/workspace/FunGAP/run_braker.py', '--masked_assembly', '/fungap_workspace/fungap_out/maker_out/masked_assembly.fasta', '--bam_files', '/fungap_workspace/fungap_out/hisat2_out/SRR12647642.bam', '--output_dir', '/fungap_workspace/fungap_out/braker_out', '--translation_table', '1', '--log_dir', '/fungap_workspace/fungap_out/logs', '--num_cores', '8', '--fungus']' returned non-zero exit status 1.
(base) root@451c7d8bc04c:/fungap_workspace# 


[braker_SRR12647642.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/6653459/braker_SRR12647642.log)
[gmes.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/6653461/gmes.log)
[fungap.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/6653464/fungap.log)

**Comment by mbnmbn00** [comment]
Hello,

I see different messages from `braker_SRR1264642.log`.

```
# WARNING:
# The hints file(s) for GeneMark-EX contain less than 150 introns with multiplicity >= 10! (In total, 1 unique introns are contained. 0 have a multiplicity >= 10.) Possibly, you are trying to run braker.pl on data that does not provide sufficient multiplicity information. This will e.g. happen if you try to use introns generated from assembled RNA-Seq transcripts; or if you try to run braker.pl in epmode with mappings from proteins without sufficient hits per locus. Or if you use the example data set (orthodb_small.fa).
# A low number of intron hints with sufficient multiplicity may result in a crash of GeneMark-EX (it should not crash with the example data set).
```

It looks like there are not enough hints. If you don't mind could you try test run (_S. cerevisiae_) to see if the installation is the problem?

## Test run

1. Download test dataset

You can download yeast (_Saccharomyces cerevisiae_) genome assembly (FASTA) and RNA-seq reads (two FASTQs) from NCBI for testing FunGAP.

```
# Download RNA-seq reads using SRA toolkit (https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit)
# Parameter -X indicates the number of read pairs you want to download
fastq-dump -X 1000000 -I --split-files SRR1198667

# Download assembly
wget ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/146/045/GCF_000146045.2_R64/GCF_000146045.2_R64_genomic.fna.gz
gunzip GCF_000146045.2_R64_genomic.fna.gz
```

2. Download protein sequences of related species

```
$FUNGAP_DIR/download_sister_orgs.py \
  --taxon "Saccharomyces cerevisiae" \
  --email_address <YOUR_EMAIL_ADDRESS> \
  --num_sisters 1
zcat sister_orgs/*faa.gz > prot_db.faa
```

3. Get Augustus species

```
$FUNGAP_DIR/get_augustus_species.py \
  --genus_name "Saccharomyces" \
  --email_address byoungnammin@lbl.gov
saccharomyces_cerevisiae_S288C
```

4. Run FunGAP

```
$FUNGAP_DIR/fungap.py \
  --genome_assembly /fungap_workspace/GCF_000146045.2_R64_genomic.fna \
  --trans_read_1 /fungap_workspace/SRR1198667_1.fastq \
  --trans_read_2 /fungap_workspace/SRR1198667_2.fastq \
  --augustus_species saccharomyces_cerevisiae_S288C \
  --busco_dataset ascomycota_odb10 \
  --sister_proteome prot_db.faa \
  --num_cores 8
```

You also can run only the Braker to see what happens.

```
/workspace/FunGAP/run_hisat2.py \
  --read_files /fungap_workspace/SRR1198667_1.fastq /fungap_workspace/SRR1198667_2.fastq \
  --output_dir /fungap_workspace/fungap_out/hisat2_out \
  --log_dir /fungap_workspace/fungap_out/logs \
  --ref_fasta /fungap_workspace/GCF_000146045.2_R64_genomic.fna \
  --num_cores 8 \
  --max_intron 2000

/workspace/FunGAP/run_braker.py \
  --masked_assembly /fungap_workspace/GCF_000146045.2_R64_genomic.fna \
  --bam_files /fungap_workspace/fungap_out/hisat2_out/SRR12647642.bam \
  --output_dir /fungap_workspace/fungap_out/braker_out \
  --log_dir /fungap_workspace/fungap_out/logs \
  --num_cores 8 \
  --fungus
```

I will help you as much as I can. Thanks for your patience. Hope you can finish the job soon.

**Comment by sajjadasaf** [comment]
Dear @mbnmbn00 and @lmtani,
Thank you for your help.
I have observed one more error in fungap in my system. When enter the following command
docker run -it -w /fungap_workspace --rm -v $(pwd):/fungap_workspace fungap bash
It gives me the following location as normal fungap terminal.
(base) root@2d23010232d7:/fungap_workspace# 
However, the error the following error come in maker when i use the same terminal with (base) 

Possible precedence issue with control flow operator at /opt/conda/envs/maker/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
STATUS: Parsing control files...
WARNING: Could not get initialization lock. Trying Again...
WARNING: Could not get initialization lock. Trying Again...
WARNING: Could not get initialization lock. Trying Again...
WARNING: Could not get initialization lock. Trying Again...
ERROR: Cannot get initialization lock.
If you are running maker in parallel or via MPI
You may be facing a race condition.
--> rank=NA, hostname=2d23010232d7

But when I deactivate conda and make it without base (root@2d23010232d7:/fungap_workspace# ) it completed successfully without error upto maker stages and then show problem in brakers (As i mentioned above).

Do you have any solution for this why it happens? and how to avoid it?

**Comment by lmtani** [comment]
@sajjadasaf , Could you inspect your `fungap-base` image version? It should be the same as the "RepoDigests":

```bash
~$ docker inspect taniguti/fungap-base:v1.1.1
[
    {
        "Id": "sha256:<this-can-change>",
        "RepoTags": [
            "taniguti/fungap-base:v1.1.1"
        ],
        "RepoDigests": [
            "taniguti/fungap-base@sha256:b84460e6c8b3b2feda78014a8e4e6a9e224599163fdc70e4c09ba58303312cd7"
        ],
        (...)
```

**Comment by sajjadasaf** [comment]
@lmtani  Yes i have the same docker version.
@mbnmbn00  
Interestingly the fungap completed successfully with example data but when using our own data it shows same problem. we have used different raw reads as well but same results. 
Is there any way to skip brakers and use maker and Augustus results to get final fungap annotation files? or is there any way to skip the following error.

Run] mv /fungap_workspace/fungap_out/braker_out/SRR6705586/braker.gff3 /fungap_workspace/fungap_out/braker_out/SRR6705586/braker_SRR6705586.gff3
mv: cannot stat '/fungap_workspace/fungap_out/braker_out/SRR6705586/braker.gff3': No such file or directory
[Run] /opt/conda/bin/getAnnoFastaFromJoingenes.py -g /fungap_workspace/fungap_out/maker_out/masked_assembly.fasta.adjusted -o /fungap_workspace/fungap_out/braker_out/SRR6705586/braker_SRR6705586 -t 1 -3 /fungap_workspace/fungap_out/braker_out/SRR6705586/braker_SRR6705586.gff3
Traceback (most recent call last):
  File "/opt/conda/bin/getAnnoFastaFromJoingenes.py", line 120, in <module>
    with open(args.gff3, "r") as gff3_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/fungap_workspace/fungap_out/braker_out/SRR6705586/braker_SRR6705586.gff3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/getAnnoFastaFromJoingenes.py", line 136, in <module>
    print("Error: Failed to open file " + args.gtf + "!")
TypeError: can only concatenate str (not "NoneType") to str
[Run] mv /fungap_workspace/fungap_out/braker_out/SRR6705586/braker_SRR6705586.aa /fungap_workspace/fungap_out/braker_out/SRR6705586/braker_SRR6705586.faa
mv: cannot stat '/fungap_workspace/fungap_out/braker_out/SRR6705586/braker_SRR6705586.aa': No such file or directory
[ERROR] Braker failed. Check the log: /fungap_workspace/fungap_out/logs/braker_SRR6705586.log
Traceback (most recent call last):
  File "/workspace/FunGAP/fungap.py", line 839, in <module>
    main()
  File "/workspace/FunGAP/fungap.py", line 212, in main
    braker_gff3s, braker_faas = run_braker(
  File "/workspace/FunGAP/fungap.py", line 509, in run_braker
    check_call(command_args)
  File "/opt/conda/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/workspace/FunGAP/run_braker.py', '--masked_assembly', '/fungap_workspace/fungap_out/maker_out/masked_assembly.fasta', '--bam_files', '/fungap_workspace/fungap_out/hisat2_out/SRR6705586.bam', '--output_dir', '/fungap_workspace/fungap_out/braker_out', '--translation_table', '1', '--log_dir', '/fungap_workspace/fungap_out/logs', '--num_cores', '8', '--fungus']' returned non-zero exit status 1.
(base) root@b4215bdca105:/fungap_workspace# 
[braker_SRR6705586.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/6685485/braker_SRR6705586.log)

**Comment by mbnmbn00** [comment]
Thank you for sharing this. 

I think you need to check your `.bam` file.

1) Check the alignment rate

```
cat /fungap_workspace/fungap_out/logs/hisat2_*.log
```

- It should be >90%

2) Check the actual alignments

Install Integrated Genomics Viewer (IGV).
https://software.broadinstitute.org/software/igv/

And load the `.bam` file and see if introns are correctly recognized.

3) Skip the Braker

At this point, I want to check the RNA-seq data first. If you can provide me with your assembly (mbnmbn00@gmail.com), I will happily investigate the assembly and may find proper RNA-seq for you.

**Comment by sajjadasaf** [comment]
Thank you for you kind reply.
Yes, you are right. There is problem in alignment.
I am sending you assembly file by you email.
Always appreciate your help and support.
