### ISSUE TITLE
Braker error

### ISSUE THREAD

**Issue by Hua-CM** [CompSynBioLab-KoreaUniv/FunGAP#69]
I have met a problem when run braker and this is my fungap_out/logs/braker_MHJ1.log

~~~shell
# Mon Jun 21 13:51:56 2021: Log information is stored in file /home/assembly/MHJ/annotation/fungap_out/braker_out/MHJ1/braker.log
# Mon Jun 21 14:10:58 2021: ERROR: in file /home/assembly/tools/BRAKER-2.1.5/scripts/braker.pl at line 7099
Training gene file in genbank format /home/assembly/MHJ/annotation/fungap_out/braker_out/MHJ1/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.
# Mon Jun 21 14:10:58 2021: ERROR: in file /home/assembly/tools/BRAKER-2.1.5/scripts/braker.pl at line 7099
Training gene file in genbank format /home/assembly/MHJ/annotation/fungap_out/braker_out/MHJ1/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.
~~~

I have read #68 and checked my bam file. Theres is 88.03% overall alignment rate, which less than 90%. Is this the cause? For now, I just skip the BRAKER as you mentioned in #68. Any other suggestions?

Looking forward to your reply.

**Comment by mbnmbn00** [comment]
88.03% sounds not bad. Have you checked read alignments in IGV?
It is possible that your RNA-seq data is composed of rRNA, rather than mRNA.
Could you check if you sequenced poly-A captured RNA? not whole RNA?

It should look like this:

![image](https://user-images.githubusercontent.com/14007210/122971648-1d6f4380-d344-11eb-9b04-a7283146351d.png)

**Comment by Hua-CM** [comment]
sorry for late reply. I have checked my bam file. And the mapping seems right(as following). Any other suggestions? By the way, my genome for annotation contains 241 contigs, will it affect the results? If necessary, I could provide my genome file and RNA-seq file.
[![RMFMIH.md.png](https://z3.ax1x.com/2021/06/24/RMFMIH.md.png)](https://imgtu.com/i/RMFMIH)
[![RMFKde.md.png](https://z3.ax1x.com/2021/06/24/RMFKde.md.png)](https://imgtu.com/i/RMFKde)

**Comment by mbnmbn00** [comment]
Yes! I would like to try and see what happened.
mbnmbn00@gmail.com
Here!

**Comment by mbnmbn00** [comment]
Your error is somewhat different from #68.

I think it's related to this:
https://github.com/Gaius-Augustus/BRAKER/issues/196

The solution would be getting the latest version of Augustus.
(Not sure which version you are using)

If you think you fix the issue, you can delete only the `braker_out` directory, and re-run the FunGAP with the same command. It will recognize finished jobs.

**Comment by Hua-CM** [comment]
Thank you for your quickly reply. Acutually, I downloaded the Augustus 3.4.0 at first and encounter the same error in #63 
~~~shell
[ERROR] Augustus version is not 3.3.3. Check with "/rds/general/user/tsewell/home/anaconda3/envs/fungap/bin/augustus --version"
~~~
So I turned back to the 3.3.3. 

I'll try advice in BRAKER#196 and tell you results.

**Comment by mbnmbn00** [comment]
Oh, I am so sorry. The `set_dependencies.py` has been updated in v1.1.1.
https://github.com/CompSynBioLab-KoreaUniv/FunGAP/blob/master/set_dependencies.py

3.4.0 is now a requirement.
You can `git clone https://github.com/CompSynBioLab-KoreaUniv/FunGAP.git` to install the latest version.
And run `set_dependencies.py` again.

Glad it's not your RNA-seq that caused the issue.
Let me know how it goes!

**Comment by Hua-CM** [comment]
I'm glad to tell you that after following the advice in BRAKER#196, my FunGAP project has completed successfully and the results seems correct accoding to previous reports. Thank you very much!

ps: An advice for make_transcripts.py. Might you consider using Biopython to generate fasta dictionary? Since I encountered another error during this step, and after checking my file and source code, I found that my fasta file header was dirty, e.g. ">AAA species=BBB balabala=CCC", which leads to the return of None when mapping to the gff3 dictionary. I think using "id" attribute in Bio.SeqRecord object may help avoid this problem.

**Comment by mbnmbn00** [comment]
Oh, thanks for the advice. I guess the space between `>AAA` and `species=BBB` is a tab?
I considered when it's space, but not a tab.

Now I fixed the issue by splitting the line with any white spaces, not a space.
```
d_fasta = defaultdict(str)
for line in fasta:
    if re.search(r'^>', line):
        scaffold_id = line.split(' ')[0].replace('>', '')
        continue
    d_fasta[scaffold_id] += line
```

to

```
d_fasta = defaultdict(str)
for line in fasta:
    if re.search(r'^>', line):
        scaffold_id = line.split()[0].replace('>', '')
        continue
    d_fasta[scaffold_id] += line
```

If I encounter another error, I will change it into `Bio.SeqRecord` as you suggested! Thanks!
