### ISSUE TITLE
RECON failure

### ISSUE THREAD

**Issue by jmonroynieto** [CompSynBioLab-KoreaUniv/FunGAP#7]
Failure at Repeat modeler stage when doing a test run over _Cryptococcus neoformans_  H99 data after installing.

```
[12-11 19:41] DONE  running RepeatModeler
[12-11 19:41] DONE : wrapper_run_repeat_modeler

Check input files...
TRANS_READ_FILES is ok...
GENOME_ASSEMBLY is ok...
SISTER_PROTEOME is ok...

Traceback (most recent call last):
  File "/packages/FunGAP/fungap.py", line 950, in <module>
    main(sys.argv[1:])
  File "/packages/FunGAP/fungap.py", line 348, in main
    genome_assembly, output_dir, project_name, num_cores, config_file
  File "/packages/FunGAP/fungap.py", line 580, in run_repeat_modeler
    )[0]
IndexError: list index out of range
```
TheRepeat modeler logs point to a failure of the script eleredef in RECON_1.08

```
 - RECON: Running re-definition of elements ( eleredef )..
eleredef failed. Exit code 768
```

Forums [one](https://www.biostars.org/p/5839/) and [two](http://seqanswers.com/forums/showthread.php?t=50696)  identify the issue with for RECON_1.05 and claim to solve it by compiling the new version 1.08 distributed by the [RM](http://www.repeatmasker.org/) team. I did not find the logs associated with this script as clamed by [this](https://www.biostars.org/p/5839/#140464) comment. 

I am running the latest version of RECON (2014) included in the externals.

**Comment by mbnmbn00** [comment]
Let's try to install from scratch.

### 1. Check perl version.

```$ perl -v```

It should be > 5.8.8

### 2. Install RECON 1.08

```
$ wget http://www.repeatmasker.org/RepeatModeler/RECON-1.08.tar.gz
$ tar -zxvf RECON-1.08.tar.gz
$ cd RECON-1.08/src/
$ make
$ make install
```

### 3. Install RepeatScout 1.0.5

```
$ wget http://www.repeatmasker.org/RepeatScout-1.0.5.tar.gz
$ tar -zxvf RepeatScout-1.0.5.tar.gz 
$ cd RepeatScout-1
$ make
```

### 4. Download TRF 4.09

Go to this site and download the proper file for your system.
https://tandem.bu.edu/trf/trf409.linux64.download.html

You may change the permission of the file and make symbolic link.
```
$ chmod +x trf409.linux64  # Give a permission for execution
$ ln -s trf409.linux64 trf  # RepeatMasker recognizes trf
```

### 5. Install RMBlast 2.2.28

```
wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/rmblast/LATEST//ncbi-rmblastn-2.2.28-x64-linux.tar.gz
tar -zxvf ncbi-rmblastn-2.2.28-x64-linux.tar.gz
```

### 6. Install NSEG

```
$ wget --recursive --no-parent ftp://ftp.ncbi.nih.gov/pub/seg/nseg/
$ cd tools/ftp.ncbi.nih.gov/pub/seg
$ mv nseg ../../../
$ rm -r ftp.ncbi.nih.gov
$ cd nseg
$ make
```

### 7. Install RepeatModeler 1.0.11

```
$ wget http://www.repeatmasker.org/RepeatModeler/RepeatModeler-open-1.0.11.tar.gz
$ tar -zxvf tar -zxvf RepeatModeler-open-1.0.11.tar.gz
$ cd RepeatModeler-open-1.0.11/
$ perl ./configure
```

And configure the paths of pre-requisites. 

### 8. Check the installation

```
$ BuildDatabase --help
$ RepeatModeler --help
```

Your issue might be originated from the incompatible versions of pre-requisites. Hope you can install with above instruction and finally use the FunGAP!

**Comment by jmonroynieto** [comment]
Thank you for your answer.

I've reinstalled the program as indicated. My new installation also fails at RepeatModeler stage for a different reason. The indexing is failing when looking for the xni file. The xnd, xns, xnt files exist but the xni file does not.

build_database.log shows no issues.
Error output from the pipeline shows the same `IndexError` as before.

**Comment by mbnmbn00** [comment]
I upgraded the FunGAP to v1.1.0. In this version users will install dependencies via **Anaconda** as much as possible so as to reduce installation problems. Can you try the new version and let me know if you have further issues?

https://github.com/CompSynBioLab-KoreaUniv/FunGAP/blob/master/INSTALL.md
