### ISSUE TITLE
about fungap running

### ISSUE THREAD

**Issue by gyudae** [CompSynBioLab-KoreaUniv/FunGAP#72]
hi, everyone. i have one question about running fungap.
i followed the instruction at github for running fungap, and get some errors below:

ERROR: The file '/$PWD/fungi_annotation/maker_out/SRR13961797/maker_run4/assembly.maker.output/assembly_master_datastore_index.log' does not exist
Traceback (most recent call last):
  File "/$PWD/FunGAP/run_maker.py", line 676, in <module>
    main()
  File "/$PWD/FunGAP/run_maker.py", line 246, in main
    collect_result_final(
  File "/$PWD/FunGAP/run_maker.py", line 556, in collect_result_final
    copyfile(merged_gff3, output_gff3)
  File "/$PWD/anaconda3/envs/fungap/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/$PWD/fungi_annotation/maker_out/SRR13961797/maker_run4/assembly.all.gff'
Traceback (most recent call last):
  File "./fungap.py", line 839, in <module>
    main()
  File "./fungap.py", line 195, in main
    maker_gff3s, maker_faas = run_maker(
  File "./fungap.py", line 453, in run_maker
    check_call(command_args)
  File "/$PWD/anaconda3/envs/fungap/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/$PWD/FunGAP/run_maker.py', '--input_fasta', '/$PWD/assembly.fasta', '--augustus_species', 'fusarium_graminearum', '--protein_db_fasta', '/$PWD/sister_orgs/prot_db.faa', '--repeat_model', '/$PWD/fungi_annotation/repeat_modeler_out/RM_3959124.MonSep61646492021/consensi.fa.classified', '--est_files', '/$PWD/fungi_annotation/trinity_out/trinity_SRR13961797/Trinity_SRR13961797.fasta', '--output_dir', '/$PWD/fungi_annotation/maker_out', '--num_cores', '72', '--translation_table', '1', '--log_dir', '/$PWD/fungi_annotation/logs', '--gmes_fungus']' returned non-zero exit status 1.

i can't find what's the problem...
anyone can help?? :(

**Comment by mbnmbn00** [comment]
I think your fourth run of the Maker failed somehow.
Could you send me the log files at `/$PWD/fungi_annotation/logs`?
You can compress them into a zip file and upload it.

**Comment by gyudae** [comment]
[logs.zip](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/7118699/logs.zip)
thank you very much! here is a log file :)

**Comment by mbnmbn00** [comment]
I found an error message in the `gmes.log` file, saying
```
error, check  mask margin and mask soft values
error on call: /home/dlrbeo3025/FunGAP/external/gmes_linux_64/probuild --reformat_fasta --uppercase --allow_x --letters_per_line 60 --out data/dna.fna --label _dna --trace info/dna.trace --in /home/dlrbeo3025/fungi_annotation/maker_out/masked_assembly.fasta  --mask_soft 1 --mask_margin 10 --low2gff data/in_mask.gff
```

I have never seen this error before. Here's the GeneMark manual.
```
  --mask_soft <i> optional int, mask lowcase letters if lowcase sub-string is longer than specified length; zero value - no masking
  --mask_margin <i> optional int, apply margin to --mask_soft option
```
Your command above looks right to me. One thing we can do it to check if below file exists and is correct.
```
/home/dlrbeo3025/fungi_annotation/maker_out/masked_assembly.fasta
```

Can you look at this file and see if it looks okay? Another way is to run the erroneous command again to see if it gives any further information. In other words, run:
```
/home/dlrbeo3025/FunGAP/external/gmes_linux_64/probuild --reformat_fasta --uppercase --allow_x --letters_per_line 60 --out data/dna.fna --label _dna --trace info/dna.trace --in /home/dlrbeo3025/fungi_annotation/maker_out/masked_assembly.fasta  --mask_soft 1 --mask_margin 10 --low2gff data/in_mask.gff
```

Note you have to run this command after changing directory to `genemark_out` where `info`, `data` directories are located.

**Comment by mbnmbn00** [comment]
It has been resolved. I changed the code from `--soft_mask 1` to `--soft_mask auto`. It seems a recently introduced bug in GeneMark.
