### ISSUE TITLE
error while testing

### ISSUE THREAD

**Issue by a-milano** [CompSynBioLab-KoreaUniv/FunGAP#73]
hi all,
following steps to running for the first time, got an error on the final step (Test run step4: https://github.com/CompSynBioLab-KoreaUniv/FunGAP/blob/master/INSTALL.md#4-run-fungap).
After some minutes running, detects a missing file:

ERROR: The file '/my_working_dir/fungap_out/maker_out/SRR1198667/maker_run4/GCF_000146045.2_R64_genomic.maker.output/GCF_000146                                                        045.2_R64_genomic_master_datastore_index.log' does not exist

In folder maker_run3, ls returns:
GCF_000146045.2_R64_genomic.all.gff       maker_bopts.ctl  maker_exe.ctl   snp_training
GCF_000146045.2_R64_genomic.maker.output  maker_evm.ctl    maker_opts.ctl

In folder maker_run4, ls returns:
maker_bopts.ctl  maker_evm.ctl  maker_exe.ctl  maker_opts.ctl

Thanks very much for any help

**Comment by mbnmbn00** [comment]
The error that occurred in `maker_run4` is usually related to `GeneMark` running.
In the `logs` directory, you can see and send me the `gmes.log` file.

If you are not unsure, you can upload the whole `logs` directory as a `zip` file.

**Comment by a-milano** [comment]
ok, thanks. Here is the logs.zip file
[logs.zip](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/7157522/logs.zip)

**Comment by mbnmbn00** [comment]
Okay. I see this error:
```
error, check  mask margin and mask soft values
error on call: /home/dlrbeo3025/FunGAP/external/gmes_linux_64/probuild --reformat_fasta --uppercase --allow_x --letters_per_line 60 --out data/dna.fna --label _dna --trace info/dna.trace --in /home/dlrbeo3025/fungi_annotation/maker_out/masked_assembly.fasta  --mask_soft 1 --mask_margin 10 --low2gff data/in_mask.gff
```

You are the second person who reported the same error message recently.
I will download the GeneMark and test it myself. Meanwhile, can you let me know which version did you use??

**Comment by mbnmbn00** [comment]
Oh wait, you are the same person :)

**Comment by a-milano** [comment]
jejee
the version used is GeneMark-ES/ET/EP ver 4.68_lic, downloaded from http://topaz.gatech.edu/GeneMark/license_download.cgi

If it helps, I got an other error on a previous step (4.2. Change the perl path): error, required file not found: hmm_to_gtf.pl
That script is actually missing, but I don't know if this is the problem, or maybe it will cause some error later...

**Comment by mbnmbn00** [comment]
Okay. That sounds like a clue.
Can you re-install the `GeneMark`? That `hmm_to_gtf.pl` file should in `gmes_linux_64/other` directory.

I will these the GeneMark myself anyway and let you know if it's GeneMark's error or not.

**Comment by mbnmbn00** [comment]
Hello,
I could reproduce the error! `--soft_mask 1` was the problem that didn't cause the error before.
I changed it into `--soft_mask auto` and it worked.

I changed the code. Please go to the `FunGAP` directory and type:
```
git pull
```
If it doesn't work, open the `run_maker.py` file and change `--soft_mask 1` to `--soft_mask auto` at line 335.
Hope it works!

**Comment by a-milano** [comment]
hi, bad news...

first, hmm_to_gtf.pl file is in gmes_linux_64/other directory, but the script: perl change_path_in_perl_scripts.pl "/usr/bin/env perl" seems not able to find it.
Second, I ran test again (after pulling project, and checking --soft_mask auto at line 335, but still same error:

ERROR: The file '/media/Disco7/AndresMilano/hongos/pruebas_fungap/fungap_out/maker_out/SRR1198667/maker_run4/GCF_000146045.2_R64_genomic.maker.output/GCF_000146045.2_R64_genomic_master_datastore_index.log' does not exist

In fact, inside maker_run4 there are only the same 4 files I described on first post.

Please, could you check this one more time?
thanks very much

**Comment by mbnmbn00** [comment]
Could you send me the `logs` directory one more time? Or `gmes.log` file.

**Comment by a-milano** [comment]
ok, sure. Here it is...I can see there are some problems here. Thanks in advance
[gmes.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/7164761/gmes.log)

**Comment by mbnmbn00** [comment]
```
Can't locate Clone/Choose.pm in @INC (you may need to install the Clone::Choose module)
```
It is saying that you don't have the `Clone::Choose` perl module.

1. You may double-check if you activated `fungap` conda module. `conda activate fungap`
2. Now you may only run GeneMark until it runs correctly.

```
mkdir genemark_out
cd genemark_out
$FUNGAP_DIR/external/gmes_linux_64/gmes_petap.pl \
  --ES --fungus --cores 4 --sequence ../GCF_000146045.2_R64_genomic.fna --soft_mask auto > gmes.log 2>&1
```

I started the test 5 minutes ago, and it's running without errors so far.

For the error `hmm_to_gtf.pl`, you may change `change_path_in_perl_scripts.pl` file from
```
"hmm_to_gtf.pl",
```
to
```
"other/hmm_to_gtf.pl",
```
Then run `change_path_in_perl_scripts.pl` again.

**Comment by a-milano** [comment]
it worked! I fixed change_path_in_perl_scripts.pl in order to find the missing script, ran it again, and it seems to find perl library missing from the error bellow (Clone/Choose.pm). This is what I deduce, since I haven´t installed this library explicitly in this procedure.
Thanks very much for your help.

**Comment by mbnmbn00** [comment]
Glad it worked! I will report the bug to the GeneMark authors. 
By the way, could you click the star for this package if you don't mind? 🙇‍♂️
