### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by shaobinzhong** [CompSynBioLab-KoreaUniv/FunGAP#74]
Hello there,

Thanks for developing this program. I want to use it to annotate a fungal genome. However, when I tried to test the program with the example you provided for Saccharomyces cerevisiae, the program run terminated after a few minutes. The log contained the error message "OSError: [Errno 2] No such file or directory". Can you help me to fig out what is wrong with it? The command and log file are attached at the end of this message. Thanks. Shaobin

The pbs file:

(fungap) [shaobin.zhong@login0001 FUNGAP_DIR]$ more fungap_job.pbs
#!/bin/bash
#PBS -q bigmem
#PBS -N FunGAP_test2
#PBS -j oe
#PBS -l select=1:ncpus=12:mem=400GB
#PBS -l walltime=96:00:00
#PBS -m abe
#PBS -M shaobin.zhong@ndsu.edu
#PBS -W group_list=x-ccast-prj-zhong

cd $PBS_O_WORKDIR
source /gpfs1/projects/shaobin.zhong/anaconda3/bin/activate fungap
python2 $FUNGAP_DIR/fungap.py \
  --output_dir fungap_output_directory_2 \
  --trans_read_1 SRR1198667_sampled_1.fastq \
  --trans_read_2 SRR1198667_sampled_2.fastq \
  --genome_assembly GCF_000146045.2_R64_genomic.fna \
  --augustus_species saccharomyces_cerevisiae_S288C \
  --sister_proteome prot_db.faa \
  --num_cores 12

The log file: 

(fungap) [shaobin.zhong@login0001 FUNGAP_DIR]$ more FunGAP_test2.o1067324

============ New Run 2021-10-06 12:26:48.850160 ============
[10-06 12:26] START: wrapper_run_hisat2
[Wrapper] python /gpfs1/projects/shaobin.zhong/FunGAP/run_hisat2.py --read_files SRR1198667_sampled_1.fastq SRR1198667_sampled_2.fastq --output_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/hisat2
_out --log_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs --ref_fasta /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/GCF_000146045.2_R64_genomic.fna --num_cores 12 --max_intron 2000
[10-06 12:26] START: Hisat2
Running hisat2-build has already been finished
Ruuning Hisat2 has already been finished for SRR1198667_sampled
[10-06 12:26] DONE : Hisat2
[10-06 12:26] DONE : wrapper_run_hisat2

[10-06 12:26] START: wrapper_run_trinity
[Wrapper] python /gpfs1/projects/shaobin.zhong/FunGAP/run_trinity.py --bam_files /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/hisat2_out/SRR1198667_sampled.bam --output_dir /gpfs1/scratch/shaobin.zho
ng/FUNGAP_DIR/fungap_output_directory_2/trinity_out --log_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs --num_cores 12 --max_intron 2000 --jaccard_clip
[10-06 12:26] START: Trinity for SRR1198667_sampled
[Run] /gpfs1/projects/shaobin.zhong/FunGAP/external/trinityrnaseq-v2.9.0/Trinity --jaccard_clip --genome_guided_bam /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/hisat2_out/SRR1198667_sampled.bam --ge
nome_guided_max_intron 2000 --max_memory 10G --CPU 12 --output /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/trinity_out/trinity_SRR1198667_sampled > /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_out
put_directory_2/logs/trinity/trinity_SRR1198667_sampled.log 2>&1
Traceback (most recent call last):
  File "/gpfs1/projects/shaobin.zhong/FunGAP/run_trinity.py", line 169, in <module>
    main(sys.argv[1:])
  File "/gpfs1/projects/shaobin.zhong/FunGAP/run_trinity.py", line 102, in main
    bam_files, output_dir, log_dir, num_cores, max_intron, jaccard_clip_flag
  File "/gpfs1/projects/shaobin.zhong/FunGAP/run_trinity.py", line 158, in run_trinity
    os.rename(trinity_output, new_output)
OSError: [Errno 2] No such file or directory
Check input files...
TRANS_READ_FILES is ok...
GENOME_ASSEMBLY is ok...
SISTER_PROTEOME is ok...

Traceback (most recent call last):
  File "/gpfs1/projects/shaobin.zhong/FunGAP/fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "/gpfs1/projects/shaobin.zhong/FunGAP/fungap.py", line 202, in main
    trans_bams, output_dir, num_cores, no_jaccard_clip, max_intron
  File "/gpfs1/projects/shaobin.zhong/FunGAP/fungap.py", line 342, in run_trinity
    check_call(command_args)
  File "/gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/gpfs1/projects/shaobin.zhong/FunGAP/run_trinity.py', '--bam_files', '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/hisat2_out/SRR1198667_sampled.ba
m', '--output_dir', '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/trinity_out', '--log_dir', '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs', '--num_cores', '12', '--max_intr
on', '2000', '--jaccard_clip']' returned non-zero exit status 1

**Comment by mbnmbn00** [comment]
Hello, it seems the `Trinity` didn't finish well.
Can you show me what `logs/trinity_SRR1198667.log` says?

**Comment by mbnmbn00** [comment]
Thanks, it complains that you don't have the `samtools`.

Can you type these commands and post what you get?
```
which samtools
samtools -v
```

**Comment by mbnmbn00** [comment]
That sounds great!! If you didn't use `conda install`, you may encounter more errors later.
Feel free to let me know when you get any errors.
