### ISSUE TITLE
ERROR: The HMM file[s] provided for gmhmm do not exist

### ISSUE THREAD

**Issue by shaobinzhong** [CompSynBioLab-KoreaUniv/FunGAP#75]
Dear Dr. Min,

After 4 hours of run, I encountered another problem. This time, the issue is with maker run4:

============ New Run 2021-10-06 13:27:35.274623 ============
[10-06 13:27] START: wrapper_run_hisat2
[Wrapper] python /gpfs1/projects/shaobin.zhong/FunGAP/run_hisat2.py --read_files SRR1198667_sampled_1.fastq SRR1198667_sampled_2.fastq --output_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_D
IR/fungap_output_directory_2/hisat2_out --log_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs --ref_fasta /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/GCF_00014604
5.2_R64_genomic.fna --num_cores 12 --max_intron 2000
[10-06 13:27] START: Hisat2
Running hisat2-build has already been finished
Ruuning Hisat2 has already been finished for SRR1198667_sampled
[10-06 13:27] DONE : Hisat2
[10-06 13:27] DONE : wrapper_run_hisat2

[10-06 13:27] START: wrapper_run_trinity
[Wrapper] python /gpfs1/projects/shaobin.zhong/FunGAP/run_trinity.py --bam_files /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/hisat2_out/SRR1198667_sampled.bam --ou
tput_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/trinity_out --log_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs --num_cores 12 --
max_intron 2000 --jaccard_clip
[10-06 13:27] START: Trinity for SRR1198667_sampled
[Run] /gpfs1/projects/shaobin.zhong/FunGAP/external/trinityrnaseq-v2.9.0/Trinity --jaccard_clip --genome_guided_bam /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/his
at2_out/SRR1198667_sampled.bam --genome_guided_max_intron 2000 --max_memory 10G --CPU 12 --output /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/trinity_out/trinity_S
RR1198667_sampled > /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs/trinity/trinity_SRR1198667_sampled.log 2>&1
[10-06 14:49] DONE : Trinity for SRR1198667_sampled
[10-06 14:49] DONE : wrapper_run_trinity

[10-06 14:49] START: wrapper_run_repeat_modeler
[Wrapper] python /gpfs1/projects/shaobin.zhong/FunGAP/run_repeat_modeler.py --genome_assembly /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/GCF_000146045.2_R64_genomic.fna --output_dir /gpfs1
/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/repeat_modeler_out --log_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs --num_cores 12
[10-06 14:49] START running RepeatModeler
[Run] /gpfs1/projects/shaobin.zhong/FunGAP/external/RepeatModeler-open-1.0.11/BuildDatabase -name /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/GCF_000146045.2_R64_genomic.fna /gpfs1/scratch/
shaobin.zhong/FUNGAP_DIR/GCF_000146045.2_R64_genomic.fna > /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs/repeat_modeler/build_database.log 2>&1
[Run] /gpfs1/projects/shaobin.zhong/FunGAP/external/RepeatModeler-open-1.0.11/RepeatModeler -database /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/GCF_000146045.2_R64_genomic.fna -pa 12 > /g
pfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs/repeat_modeler/repeat_modeler.log 2>&1
[10-06 15:25] DONE  running RepeatModeler
[10-06 15:25] DONE : wrapper_run_repeat_modeler

[10-06 15:25] START: wrapper_run_maker
[Wrapper] python /gpfs1/projects/shaobin.zhong/FunGAP/run_maker.py --input_fasta /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/GCF_000146045.2_R64_genomic.fna --augustus_species saccharomyces
_cerevisiae_S288C --protein_db_fasta /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/prot_db.faa --repeat_model /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/repeat_modeler_
out/RM_77759.WedOct61449142021/consensi.fa.classified --est_files /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/trinity_out/trinity_SRR1198667_sampled/Trinity_SRR119
8667_sampled.fasta --output_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out --num_cores 12 --log_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_outpu
t_directory_2/logs --gmes_fungus
[10-06 15:25] START running Maker run1
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/maker -fix_nucleotides > /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs/maker/maker_SRR1198667_samp
led_run1.log 2>&1
[10-06 17:41] DONE  running Maker run1
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/gff3_merge -d /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out/SRR1198667_sampled/maker_run1/GCF
_000146045.2_R64_genomic.maker.output/GCF_000146045.2_R64_genomic_master_datastore_index.log
[10-06 17:41] START training run1 & running maker run2
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/maker2zff -n /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out/SRR1198667_sampled/maker_run1/GCF_
000146045.2_R64_genomic.all.gff
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/fathom -categorize 1000 genome.ann genome.dna
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/fathom -export 1000 -plus uni.ann uni.dna
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/forge ../export.ann ../export.dna
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/hmm-assembler.pl snap_hmm_v1 parameters > snap_hmm_v1.hmm
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/maker -fix_nucleotides > /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs/maker/maker_SRR1198667_samp
led_run2.log 2>&1
[10-06 17:57] DONE  training run1 & running maker run2
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/gff3_merge -d /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out/SRR1198667_sampled/maker_run2/GCF
_000146045.2_R64_genomic.maker.output/GCF_000146045.2_R64_genomic_master_datastore_index.log
[10-06 17:57] START training run2 & running maker run3
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/maker2zff -n /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out/SRR1198667_sampled/maker_run2/GCF_
000146045.2_R64_genomic.all.gff
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/fathom -categorize 1000 genome.ann genome.dna
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/fathom -export 1000 -plus uni.ann uni.dna
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/forge ../export.ann ../export.dna
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/hmm-assembler.pl snap_hmm_v2 parameters > snap_hmm_v2.hmm
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/maker -fix_nucleotides > /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs/maker/maker_SRR1198667_samp
led_run3.log 2>&1
[10-06 18:13] DONE  training run2 & running maker run3
[Run] find /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out/SRR1198667_sampled/maker_run3 -name "query.masked.fasta" | xargs cat > /gpfs1/scratch/shaobin.zhon
g/FUNGAP_DIR/fungap_output_directory_2/maker_out/masked_assembly.fasta
[10-06 18:13] START ruuning gmes to build hmm
[Run] /gpfs1/projects/shaobin.zhong/FunGAP/external/gm_et_linux_64/gmes_petap.pl --ES --fungus --cores 12 --sequence /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/ma
ker_out/masked_assembly.fasta --soft_mask 1 > /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs/maker/gmes.log 2>&1
[10-06 18:13] DONE  running gmes to build hmm
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/gff3_merge -d /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out/SRR1198667_sampled/maker_run3/GCF
_000146045.2_R64_genomic.maker.output/GCF_000146045.2_R64_genomic_master_datastore_index.log
[10-06 18:13] START training run3 & running maker run4
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/maker2zff -n /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out/SRR1198667_sampled/maker_run3/GCF_
000146045.2_R64_genomic.all.gff
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/fathom -categorize 1000 genome.ann genome.dna
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/fathom -export 1000 -plus uni.ann uni.dna
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/forge ../export.ann ../export.dna
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/hmm-assembler.pl snap_hmm_v3 parameters > snap_hmm_v3.hmm
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/maker -fix_nucleotides > /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs/maker/maker_SRR1198667_samp
led_run4.log 2>&1
[10-06 18:13] DONE  training run3 & running maker run4
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/gff3_merge -g -n -d /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out/SRR1198667_sampled/maker_ru
n4/GCF_000146045.2_R64_genomic.maker.output/GCF_000146045.2_R64_genomic_master_datastore_index.log
ERROR: The file '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out/SRR1198667_sampled/maker_run4/GCF_000146045.2_R64_genomic.maker.output/GCF_000146045.2_R64_g
enomic_master_datastore_index.log' does not exist
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/fasta_merge -d /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out/SRR1198667_sampled/maker_run4/GC
F_000146045.2_R64_genomic.maker.output/GCF_000146045.2_R64_genomic_master_datastore_index.log
ERROR: The file '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out/SRR1198667_sampled/maker_run4/GCF_000146045.2_R64_genomic.maker.output/GCF_000146045.2_R64_g
enomic_master_datastore_index.log' does not exist
Traceback (most recent call last):
  File "/gpfs1/projects/shaobin.zhong/FunGAP/run_maker.py", line 647, in <module>
    main(sys.argv[1:])
  File "/gpfs1/projects/shaobin.zhong/FunGAP/run_maker.py", line 245, in main
    collect_result_final(input_fasta, output_dir, est_prefix)
  File "/gpfs1/projects/shaobin.zhong/FunGAP/run_maker.py", line 555, in collect_result_final
    copyfile(merged_gff3, output_gff3)
  File "/gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out/SRR1198667_sampled/maker_run4/GCF_000146045.2_R64_genomic.all.
gff'
Check input files...
TRANS_READ_FILES is ok...
GENOME_ASSEMBLY is ok...
SISTER_PROTEOME is ok...

Traceback (most recent call last):
  File "/gpfs1/projects/shaobin.zhong/FunGAP/fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "/gpfs1/projects/shaobin.zhong/FunGAP/fungap.py", line 209, in main
    num_cores, repeat_model_file, trinity_asms, no_genemark_fungus
  File "/gpfs1/projects/shaobin.zhong/FunGAP/fungap.py", line 397, in run_maker
    check_call(command_args)
  File "/gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/gpfs1/projects/shaobin.zhong/FunGAP/run_maker.py', '--input_fasta', '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/GCF_000146045.2_R64_gen
omic.fna', '--augustus_species', 'saccharomyces_cerevisiae_S288C', '--protein_db_fasta', '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/prot_db.faa', '--repeat_model', '/gpfs1/scratch/shaobin
.zhong/FUNGAP_DIR/fungap_output_directory_2/repeat_modeler_out/RM_77759.WedOct61449142021/consensi.fa.classified', '--est_files', '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_
directory_2/trinity_out/trinity_SRR1198667_sampled/Trinity_SRR1198667_sampled.fasta', '--output_dir', '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out', '--n
um_cores', '12', '--log_dir', '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/logs', '--gmes_fungus']' returned non-zero exit status 1

I checked the maker_SRR1198667_sampled_run4.log, and got the following error message:

(base) [shaobin.zhong@login0001 maker]$ more  maker_SRR1198667_sampled_run4.log
STATUS: Parsing control files...
ERROR: The HMM file[s] provided for gmhmm do not exist:
        /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_2/maker_out/genemark_out/output/gmhmm.mod

--> rank=NA, hostname=node0062

What should I do to fix the problem?

Thanks.

Shaobin

**Comment by shaobinzhong** [comment]
Here is the gmes.log file:
[gmes.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/7298296/gmes.log)

**Comment by mbnmbn00** [comment]
Sorry, Your license for `GeneMark` has expired. I'm not sure you should install the `GeneMark` again.

Follow these steps:

1. Go to the below site and download GeneMark-ES/ET. http://topaz.gatech.edu/GeneMark/license_download.cgi Don't forget to download the key, too.
2. Uncompress downloaded files
```
mkdir $FUNGAP_DIR/external/
mv gmes_linux_64.tar.gz gm_key_64.gz $FUNGAP_DIR/external/  # Move your downloaded files to this directory
cd $FUNGAP_DIR/external/
tar -zxvf gmes_linux_64.tar.gz
gunzip gm_key_64.gz
cp gm_key_64 ~/.gm_key
```
