### ISSUE TITLE
commands in file: [FailedCommands] failed

### ISSUE THREAD

**Issue by shaobinzhong** [CompSynBioLab-KoreaUniv/FunGAP#76]
Hello Dr. Min,

The first run was finished with your help in resolving the issues. Then I tried to repeat the run with the same pbs file. However, I encountered another issue with trinity. Here is the run.log:

 ============ New Run 2021-10-08 12:53:43.347364 ============
[10-08 12:53] START: wrapper_run_hisat2
[Wrapper] python /gpfs1/projects/shaobin.zhong/FunGAP/run_hisat2.py --read_files SRR1198667_sampled_1.fastq SRR1198667_sampled_2.fastq --output_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_D
IR/fungap_output_directory_3/hisat2_out --log_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_3/logs --ref_fasta /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/GCF_00014604
5.2_R64_genomic.fna --num_cores 12 --max_intron 2000
[10-08 12:53] START: Hisat2
Running hisat2-build has already been finished
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/hisat2 --max-intronlen 2000 -p 12 -x /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/GCF_000146045.2_R64_genomic.fna -1 /gpfs1/scra
tch/shaobin.zhong/FUNGAP_DIR/SRR1198667_sampled_1.fastq -2 /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/SRR1198667_sampled_2.fastq 2> /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_di
rectory_3/logs/hisat2/hisat2_SRR1198667_sampled.log | /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/samtools view -bSF4 - | /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap
/bin/samtools sort - -o /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_3/hisat2_out/SRR1198667_sampled.bam
[bam_sort_core] merging from 2 files and 1 in-memory blocks...
[10-08 12:56] DONE : Hisat2
[10-08 12:56] DONE : wrapper_run_hisat2

[10-08 12:56] START: wrapper_run_trinity
[Wrapper] python /gpfs1/projects/shaobin.zhong/FunGAP/run_trinity.py --bam_files /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_3/hisat2_out/SRR1198667_sampled.bam --ou
tput_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_3/trinity_out --log_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_3/logs --num_cores 12 --
max_intron 2000 --jaccard_clip
[10-08 12:56] START: Trinity for SRR1198667_sampled
[Run] /gpfs1/projects/shaobin.zhong/FunGAP/external/trinityrnaseq-v2.9.0/Trinity --jaccard_clip --genome_guided_bam /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_3/his
at2_out/SRR1198667_sampled.bam --genome_guided_max_intron 2000 --max_memory 10G --CPU 12 --output /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_3/trinity_out/trinity_S
RR1198667_sampled > /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_3/logs/trinity/trinity_SRR1198667_sampled.log 2>&1
Traceback (most recent call last):
  File "/gpfs1/projects/shaobin.zhong/FunGAP/run_trinity.py", line 169, in <module>
    main(sys.argv[1:])
  File "/gpfs1/projects/shaobin.zhong/FunGAP/run_trinity.py", line 102, in main
    bam_files, output_dir, log_dir, num_cores, max_intron, jaccard_clip_flag
  File "/gpfs1/projects/shaobin.zhong/FunGAP/run_trinity.py", line 158, in run_trinity
    os.rename(trinity_output, new_output)
OSError: [Errno 2] No such file or directory
Check input files...
TRANS_READ_FILES is ok...
GENOME_ASSEMBLY is ok...
SISTER_PROTEOME is ok...

Traceback (most recent call last):
  File "/gpfs1/projects/shaobin.zhong/FunGAP/fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "/gpfs1/projects/shaobin.zhong/FunGAP/fungap.py", line 202, in main
    trans_bams, output_dir, num_cores, no_jaccard_clip, max_intron
  File "/gpfs1/projects/shaobin.zhong/FunGAP/fungap.py", line 342, in run_trinity
    check_call(command_args)
  File "/gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/gpfs1/projects/shaobin.zhong/FunGAP/run_trinity.py', '--bam_files', '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory
_3/hisat2_out/SRR1198667_sampled.bam', '--output_dir', '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_3/trinity_out', '--log_dir', '/gpfs1/scratch/shaobin.zhong/FUNGAP
_DIR/fungap_output_directory_3/logs', '--num_cores', '12', '--max_intron', '2000', '--jaccard_clip']' returned non-zero exit status 1

**Comment by shaobinzhong** [comment]
I tried to load the trinity_SRR1198667_sampled.log file, but it doesn't allow me to do so. I copy and pasted the end of the log file here:

(prokka) [shaobin.zhong@login0001 trinity]$ tail trinity_SRR1198667_sampled.log
[2233000 lines read]  scaff:a9;33 lend:43  rend:103     CMD: /gpfs1/projects/shaobin.zhong/FunGAP/external/trinityrnaseq-v2.9.0/util/support_scripts/jaccard_wig_clipper.pl --jaccard_wig bowtie_alignments.for_jaccard.bam.J100.wig --coverage_wig bowtie_alignments.for_jaccard.bam.frag_coords.wig  > bowtie_alignments.for_jaccard.bam.J100.wig.clips
CMD: /gpfs1/projects/shaobin.zhong/FunGAP/external/trinityrnaseq-v2.9.0/util/support_scripts/jaccard_fasta_clipper.pl /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_3/trinity_out/trinity_SRR1198667_sampled/Dir_SRR1198667_sampled.bam.minC1.gff/NC_001140.6/2/448284_453714.trinity.reads.out/inchworm.DS.fa  bowtie_alignments.for_jaccard.bam.J100.wig.clips > /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_directory_3/trinity_out/trinity_SRR1198667_sampled/Dir_SRR1198667_sampled.bam.minC1.gff/NC_001140.6/2/448284_453714.trinity.reads.out/inchworm.DS.fa.clipped.fa
succeeded(4785), failed(9)   100% completed.

We are sorry, commands in file: [FailedCommands] failed.  :-(

Error, cmd: /gpfs1/projects/shaobin.zhong/FunGAP/external/trinityrnaseq-v2.9.0/trinity-plugins/BIN/ParaFly -c trinity_GG.cmds -CPU 12 -v -shuffle  died with ret 256 at /gpfs1/projects/shaobin.zhong/FunGAP/external/trinityrnaseq-v2.9.0/Trinity line 2811.
        main::process_cmd("/gpfs1/projects/shaobin.zhong/FunGAP/external/trinityrnaseq-v"...) called at /gpfs1/projects/shaobin.zhong/FunGAP/external/trinityrnaseq-v2.9.0/Trinity line 3480
        main::run_partitioned_cmds("trinity_GG.cmds") called at /gpfs1/projects/shaobin.zhong/FunGAP/external/trinityrnaseq-v2.9.0/Trinity line 3438
        main::run_genome_guided_Trinity() called at /gpfs1/projects/shaobin.zhong/FunGAP/external/trinityrnaseq-v2.9.0/Trinity line 1381

**Comment by mbnmbn00** [comment]
Sorry, I forgot to answer.
How about running the Trinity again? You may delete the `trinity_out` directory beforehand.
I have never seen this error, hopefully, it's just a hiccup of your server.
