### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by shaobinzhong** [CompSynBioLab-KoreaUniv/FunGAP#78]
Hello,

I run the following pbs job:

#!/bin/bash
#PBS -q bigmem
#PBS -N FunGAP_CocheC5
#PBS -j oe
#PBS -l select=1:ncpus=12:mem=400GB
#PBS -l walltime=168:00:00
#PBS -m abe
#PBS -M shaobin.zhong@ndsu.edu
#PBS -W group_list=x-ccast-prj-zhong

cd $PBS_O_WORKDIR
source /gpfs1/projects/shaobin.zhong/anaconda3/bin/activate fungap
module load SAMtools/1.6-gcc
python $FUNGAP_DIR/fungap.py \
  --output_dir fungap_output_CocheC5_AN \
  --trans_read_1 CocheC5_EST_all_1.fastq \
  --trans_read_2 CocheC5_EST_all_2.fastq \
  --genome_assembly Cochliobolus_heterostrophus_C5.fasta \
  --augustus_species aspergillus_nidulans \
  --sister_proteome Coch_ca_lu_sa_vi_proteins.aa.fasta \
  --num_cores 12

But the run terminated with the following message, can you please let me know how I can fix the issue? Thanks.

Shaobin
============ New Run 2021-10-18 15:11:04.472041 ============
[10-18 15:11] START: wrapper_run_hisat2
[Wrapper] python /gpfs1/projects/shaobin.zhong/FunGAP/run_hisat2.py --read_files CocheC5_EST_all_1.fastq CocheC5_EST_all_2.fastq --output_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_C
ocheC5_AN/hisat2_out --log_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/logs --ref_fasta /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/Cochliobolus_heterostrophus_C5.fasta --num_c
ores 12 --max_intron 2000
[10-18 15:11] START: Hisat2
Running hisat2-build has already been finished
Ruuning Hisat2 has already been finished for CocheC5_EST_all
[10-18 15:11] DONE : Hisat2
[10-18 15:11] DONE : wrapper_run_hisat2

[10-18 15:11] START: wrapper_run_trinity
[Wrapper] python /gpfs1/projects/shaobin.zhong/FunGAP/run_trinity.py --bam_files /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/hisat2_out/CocheC5_EST_all.bam --output_dir /gpfs1/
scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/trinity_out --log_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/logs --num_cores 12 --max_intron 2000 --jaccard_clip
[10-18 15:11] START: Trinity for CocheC5_EST_all
Running Trinity has already been finished CocheC5_EST_all
[10-18 15:11] DONE : Trinity for CocheC5_EST_all
[10-18 15:11] DONE : wrapper_run_trinity

[10-18 15:11] START: wrapper_run_repeat_modeler
[Wrapper] python /gpfs1/projects/shaobin.zhong/FunGAP/run_repeat_modeler.py --genome_assembly /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/Cochliobolus_heterostrophus_C5.fasta --output_dir /gpfs1/scratc
h/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/repeat_modeler_out --log_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/logs --num_cores 12
Running RepeatModeler has already been finished
[10-18 15:11] DONE : wrapper_run_repeat_modeler

[10-18 15:11] START: wrapper_run_maker
[Wrapper] python /gpfs1/projects/shaobin.zhong/FunGAP/run_maker.py --input_fasta /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/Cochliobolus_heterostrophus_C5.fasta --augustus_species aspergillus_nidulans
 --protein_db_fasta /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/Coch_ca_lu_sa_vi_proteins.aa.fasta --repeat_model /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/repeat_modeler_out/RM_
27122.ThuOct140939192021/consensi.fa.classified --est_files /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/trinity_out/trinity_CocheC5_EST_all/Trinity_CocheC5_EST_all.fasta --outp
ut_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/maker_out --num_cores 12 --log_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/logs --gmes_fungus
[10-18 15:11] START running Maker run1
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/maker -fix_nucleotides > /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/logs/maker/maker_CocheC5_EST_all_run1.log 2>&
1
[10-18 15:11] DONE  running Maker run1
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/gff3_merge -d /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/maker_out/CocheC5_EST_all/maker_run1/Cochliobolus_hetero
strophus_C5.maker.output/Cochliobolus_heterostrophus_C5_master_datastore_index.log
[10-18 15:11] START training run1 & running maker run2
SNAP training has been alread finished for snap_hmm_v1.hmm
Running Maker has already been finished
[10-18 15:11] DONE  training run1 & running maker run2
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/gff3_merge -d /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/maker_out/CocheC5_EST_all/maker_run2/Cochliobolus_hetero
strophus_C5.maker.output/Cochliobolus_heterostrophus_C5_master_datastore_index.log
[10-18 15:11] START training run2 & running maker run3
SNAP training has been alread finished for snap_hmm_v2.hmm
Running Maker has already been finished
[10-18 15:11] DONE  training run2 & running maker run3
[Run] find /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/maker_out/CocheC5_EST_all/maker_run3 -name "query.masked.fasta" | xargs cat > /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fun
gap_output_CocheC5_AN/maker_out/masked_assembly.fasta
[10-18 15:12] START ruuning gmes to build hmm
GMES has already been finished
[10-18 15:12] DONE  running gmes to build hmm
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/gff3_merge -d /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/maker_out/CocheC5_EST_all/maker_run3/Cochliobolus_hetero
strophus_C5.maker.output/Cochliobolus_heterostrophus_C5_master_datastore_index.log
[10-18 15:12] START training run3 & running maker run4
SNAP training has been alread finished for snap_hmm_v3.hmm
Running Maker has already been finished
[10-18 15:12] DONE  training run3 & running maker run4
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/gff3_merge -g -n -d /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/maker_out/CocheC5_EST_all/maker_run4/Cochliobolus_
heterostrophus_C5.maker.output/Cochliobolus_heterostrophus_C5_master_datastore_index.log
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/fasta_merge -d /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/maker_out/CocheC5_EST_all/maker_run4/Cochliobolus_heter
ostrophus_C5.maker.output/Cochliobolus_heterostrophus_C5_master_datastore_index.log
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/gff3_merge -d /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/maker_out/CocheC5_EST_all/maker_run4/Cochliobolus_hetero
strophus_C5.maker.output/Cochliobolus_heterostrophus_C5_master_datastore_index.log
[10-18 15:12] DONE : wrapper_run_maker

[10-18 15:12] START: wrapper_run_augustus
[Wrapper] python /gpfs1/projects/shaobin.zhong/FunGAP/run_augustus.py --masked_assembly /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/maker_out/masked_assembly.fasta --species as
pergillus_nidulans --output_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/augustus_out --log_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/augustus_out
/logs
[10-18 15:12] START: Augustus
Running Augustus has already been finished
[10-18 15:12] DONE : Augustus
[10-18 15:13] DONE : wrapper_run_augustus

[10-18 15:13] START: wrapper_run_braker1
[Wrapper] python /gpfs1/projects/shaobin.zhong/FunGAP/run_braker1.py --masked_assembly /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/maker_out/masked_assembly.fasta --bam_files /
gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/hisat2_out/CocheC5_EST_all.bam --output_dir /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/braker1_out --log_dir /g
pfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/logs --num_cores 12 --fungus
[10-18 15:13] START: BRAKER1
[Run] /gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/braker.pl --fungus --softmasking --cores=12 --genome=/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/maker_out/masked_
assembly.fasta --bam=/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/hisat2_out/CocheC5_EST_all.bam --species=CocheC5_EST_all_4 --gff3 --AUGUSTUS_CONFIG_PATH=/gpfs1/projects/shaobi
n.zhong/anaconda3/envs/fungap/bin/../config --BAMTOOLS_PATH=/gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin --GENEMARK_PATH=/gpfs1/projects/shaobin.zhong/FunGAP/external/gm_et_linux_64 --SA
MTOOLS_PATH=/gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin --workingdir=/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/braker1_out/CocheC5_EST_all > /gpfs1/scratch/shaobi
n.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/logs/braker1/braker1_CocheC5_EST_all.log 2>&1
Traceback (most recent call last):
  File "/gpfs1/projects/shaobin.zhong/FunGAP/run_braker1.py", line 197, in <module>
    main(sys.argv[1:])
  File "/gpfs1/projects/shaobin.zhong/FunGAP/run_braker1.py", line 91, in main
    masked_assembly, bam_files, output_dir, log_dir, num_cores, fungus_flag
  File "/gpfs1/projects/shaobin.zhong/FunGAP/run_braker1.py", line 171, in run_braker1
    )[0],
IndexError: list index out of range
Check input files...
TRANS_READ_FILES is ok...
GENOME_ASSEMBLY is ok...
SISTER_PROTEOME is ok...

Traceback (most recent call last):
  File "/gpfs1/projects/shaobin.zhong/FunGAP/fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "/gpfs1/projects/shaobin.zhong/FunGAP/fungap.py", line 223, in main
    masked_assembly, trans_bams, output_dir, num_cores, no_braker_fungus
  File "/gpfs1/projects/shaobin.zhong/FunGAP/fungap.py", line 446, in run_braker1
    check_call(command_args)
  File "/gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/gpfs1/projects/shaobin.zhong/FunGAP/run_braker1.py', '--masked_assembly', '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/make
r_out/masked_assembly.fasta', '--bam_files', '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/hisat2_out/CocheC5_EST_all.bam', '--output_dir', '/gpfs1/scratch/shaobin.zhong/FUNGAP_
DIR/fungap_output_CocheC5_AN/braker1_out', '--log_dir', '/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/logs', '--num_cores', '12', '--fungus']' returned non-zero exit status 1

**Comment by mbnmbn00** [comment]
It seems that the `Braker` has failed for some reason.
Can you send me the file
```
/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/logs/braker1/braker1_CocheC5_EST_all.log
```
You can paste the log here if it's short, else you can upload the file also.

**Comment by mbnmbn00** [comment]
Could you upload the whole log file?
It seems there's more message below that you sent.

**Comment by shaobinzhong** [comment]
Here attached is the file. Thanks. Shaobin
________________________________

**Comment by mbnmbn00** [comment]
Sorry, I don't see the file. Could you upload the file via GitHub, not e-mail?

**Comment by mbnmbn00** [comment]
Okay. There's not much clue in the log.
Could you delete the `braker_out` directory and run the below?
```
/gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin/braker.pl --fungus --softmasking --cores=12 --genome=/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/maker_out/masked_
assembly.fasta --bam=/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/hisat2_out/CocheC5_EST_all.bam --species=CocheC5_EST_all_4 --gff3 --AUGUSTUS_CONFIG_PATH=/gpfs1/projects/shaobi
n.zhong/anaconda3/envs/fungap/bin/../config --BAMTOOLS_PATH=/gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin --GENEMARK_PATH=/gpfs1/projects/shaobin.zhong/FunGAP/external/gm_et_linux_64 --SA
MTOOLS_PATH=/gpfs1/projects/shaobin.zhong/anaconda3/envs/fungap/bin --workingdir=/gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/braker1_out/CocheC5_EST_all > /gpfs1/scratch/shaobin.zhong/FUNGAP_DIR/fungap_output_CocheC5_AN/logs/braker1/braker1_CocheC5_EST_all.log 2>&1
```

**Comment by shaobinzhong** [comment]
I used the following command lines before and I didn't have a problem:

cd $PBS_O_WORKDIR
source /gpfs1/projects/shaobin.zhong/anaconda3/bin/activate fungap
module load SAMtools/1.6-gcc
python $FUNGAP_DIR/fungap.py
--output_dir fungap_output_CocheC5_AN
--trans_read_1 CocheC5_EST_all_1.fastq
--trans_read_2 CocheC5_EST_all_2.fastq
--genome_assembly Cochliobolus_heterostrophus_C5.fasta
--augustus_species botrytis_cinerea
--sister_proteome Coch_ca_lu_sa_vi_proteins.aa.fasta
--num_cores 12

However, after I changed "--augustus_species botrytis_cinerea" to "--augustus_species aspergillus_nidulans", I had the problem

**Comment by shaobinzhong** [comment]
I will run it again with the correct command.

**Comment by shaobinzhong** [comment]
[repeat_modeler.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/7377150/repeat_modeler.log)

**Comment by shaobinzhong** [comment]
I should let you know that this is a new run from the beginning...

**Comment by shaobinzhong** [comment]
I just wanted to test the pipeline with the same command line and same data again

**Comment by shaobinzhong** [comment]
Once this works. I will run the pipeline for gene annotation with another genome assembly

**Comment by mbnmbn00** [comment]
Okay. If it ran okay in the past run, can you delete the `repeat_modeler` directory and run again?

I found this post that has the same issue with you.
https://github.com/Dfam-consortium/RepeatModeler/issues/110

It says:
> Can you post the contents of RM_<date>/round-1/repeatscout.log? That file might have enough details to troubleshoot the problem further.

**Comment by mbnmbn00** [comment]
Hope you got through the issue.
I'm closing the issue for now, but feel free to re-open it.

**Comment by mbnmbn00** [comment]
Glad to hear that!!!
