### ISSUE TITLE
include license

### ISSUE THREAD

**Issue by colinbrislawn** [CompSynBioLab-KoreaUniv/FunGAP#8]
Thank you for publishing this code. What license is it distributed under? Can other use, modify, and share this codebase? 
https://choosealicense.com 

Thanks 👍

**Comment by mbnmbn00** [comment]
FunGAP is freely available only for **noncommercial users**.
Yes. You can use, modify, and share this codebase ONLY IF you're not a commercial user.

I'm new to publish a program, so I'm not sure which license fits into this. Can you advice?

**Comment by colinbrislawn** [comment]
OK! This might be helpful: 
https://www.quora.com/What-is-the-best-free-for-non-commercial-use-license-to-use-for-an-open-source-project 

From that article: 
>Seems like you mean to dual-license your application.  So that some people (in your case, non-commercial use) get it under an open source license, and other people (commercial establishments) pay for it.

Thank you for clarifying that this package is for noncommercial use only. I'll close this issue for now.
