### ISSUE TITLE
Update fungap.def?

### ISSUE THREAD

**Issue by pierrj** [CompSynBioLab-KoreaUniv/FunGAP#81]
Hello,

It seems that fungap.def has not been updated for v1.1.1. Specifically, singularity is unable to build because it looks for 'patch_braker.pl'.

I update the .def file by changing the "from" line to v1.1.1 and remove the 'patch_braker.pl' line from %files. Singularity was able to properly build the image after those changes.

Please let me know if that is alright!

**Comment by mbnmbn00** [comment]
I didn't build the `.def` file so I am not sure at this moment. I asked the builder for the update, but she might be busy.
I would like to test the update you made.

Could you make a pull request? Then, I will test and accept it.

**Comment by pierrj** [comment]
done!
