### ISSUE TITLE
braker.pl needs writeable directory (singularity container)

### ISSUE THREAD

**Issue by pierrj** [CompSynBioLab-KoreaUniv/FunGAP#82]
I am running FunGAP through singularity and having this bug:

```
# BRAKER CALL: /opt/conda/bin/braker.pl --fungus --softmasking --cores=20 --genome=/global/scratch/users/pierrj/fungap_runs/gladieux_all/test_run/fungap_out/maker_out/masked_assembly.fasta.adjusted --bam=/global/scratch/users/pierrj/fungap_runs/gladieux_all/test_run/fungap_out/hisat2_out/ERR5875670.bam --species=ERR5875670 --gff3 --AUGUSTUS_CONFIG_PATH=/opt/conda/bin/../config --BAMTOOLS_PATH=/opt/conda/bin --GENEMARK_PATH=/workspace/FunGAP/external/gmes_linux_64 --SAMTOOLS_PATH=/opt/conda/bin --workingdir=/global/scratch/users/pierrj/fungap_runs/gladieux_all/test_run/fungap_out/braker_out/ERR5875670 --translation_table=1 --AUGUSTUS_BIN_PATH=/opt/conda/bin
# Sat Jan 22 18:18:22 2022: braker.pl version 2.1.5
# Sat Jan 22 18:18:22 2022: Configuring of BRAKER for using external tools...
# Sat Jan 22 18:18:22 2022: Command line flag --AUGUSTUS_CONFIG_PATH was provided. Setting $AUGUSTUS_CONFIG_PATH in braker.pl to /opt/conda/bin/../config.
# Sat Jan 22 18:18:22 2022: ERROR: in file /opt/conda/bin/braker.pl at line 1740
AUGUSTUS_CONFIG_PATH/species (in this case /opt/conda/bin/../config/ERR5875670) is not writeable.
```

BRAKER is failing because it is unable to write to the singularity filesystem. Could you please fix the container image to address this issue? Or let me know if there is any fix? I poked around with the singularity documentation but I am not very familiar with it.

**Comment by mbnmbn00** [comment]
Hmm. That's interesting. I am also not familiar with Singularity.
Please give me some time. I will figure it out and try to fix it. Thanks for reporting!!

**Comment by pierrj** [comment]
No worries! Just FYI, here is what I ended up needing to do to get it to work on my end, I basically removed the reference to AUGUSTUS_CONFIG_PATH in run_braker.py and instead used AUGUSTUS environmental variables referring to a copy of the AUGUSTUS directory on my cluster:
`sudo singularity build --sandbox fungap_sandbox/ fungap.def
sudo singularity shell --writable fungap_sandbox/
cd /workspace/FunGAP/
sed -e s/--AUGUSTUS_CONFIG_PATH={}//g -i run_braker.py
sed -e s/bam_file, species, augustus_config_path, bamtools_path,/bam_file, species, bamtools_path,/g run_braker.py
exit
cp -r fungap_sandbox/opt/conda/config/ fungap_config_copy/
sudo singularity build fungap.sif fungap_sandbox/
`
Then transferred `fungap.sif` and `fungap_config_copy` to the cluster

Then on the cluster:
`export AUGUSTUS_CONFIG_PATH=${HOME}/fungap_config_copy/
export AUGUSTUS_SCRIPTS_PATH=/opt/conda/bin
singularity exec /global/scratch/users/pierrj/fungap_runs/fungap.sif python /workspace/FunGAP/fungap.py \
                                                        --output_dir fungap_out \
                                                        --trans_read_1 ERR5875670_1.fastq \
                                                        --trans_read_2 ERR5875670_2.fastq \
                                                        --genome_assembly ${genome}_genomic.fna  \
                                                        --augustus_species magnaporthe_grisea  \
                                                        --sister_proteome prot_db.faa  \
                                                        --busco_dataset sordariomycetes_odb10 \
                                                        --num_cores ${SLURM_NTASKS}
`

**Comment by mbnmbn00** [comment]
That's interesting!
I will test it out soon and let you know how it goes.

**Comment by mbnmbn00** [comment]
I think I found a way to do it.

1) Add this line to the `fungap.def`
```
chmod -R o+rwX /opt/conda/config
```

2) Build the image using `--sandbox` option
```
sudo singularity build --sandbox sandbox fungap.def
```
However, it requires 16GB instead of 4.9GB.

3) Execute the `singularity shell` with `--writable`
```
singularity shell --writable sandbox
```

4) Check
```
Singularity> cd /opt/conda/config/
Singularity> touch a
```

So far, this is what I found. I will run full FunGAP soon and let you know how it goes.

**Comment by mbnmbn00** [comment]
Okay. Finished the test. I have a question.
Did you have a problem with not-defined `$AUGUSTUS_SCRIPTS_PATH`?

Usually, conda sets the variables, but somehow it doesn't work in Singularity.
(I will be on vacation for a while, will update the `.def` and manual once I get back)

**Comment by pierrj** [comment]
Yes, I had to set the following to get it to work:
`export AUGUSTUS_SCRIPTS_PATH=/opt/conda/bin`

**Comment by pierrj** [comment]
Another issue that I needed to fix, braker.pl needs to write its config file to a new directory each time. It causes this error otherwise:
`ERROR:/global/scratch/users/pierrj/fungap_runs/fungap_config_copy/species/ERR5875670 already exists. Choose another species name, delete this directory or use the existing species with the option --useexisting.`

Here was my modification to run_braker.py (line 127):
```
augustus_config_path = os.path.join(
                os.path.dirname(D_CONF['AUGUSTUS_PATH']), '../config')
```
To:
```
augustus_config_path = os.environ["AUGUSTUS_CONFIG_PATH"]
```

Just figured I would keep you updated. Have a nice vacation!

**Comment by mbnmbn00** [comment]
Thanks!! That would work.

However, I don't think I will modify the `run_braker.py` script since we need two additional commands to make the Singularity work.

```
cp -r fungap_sandbox/opt/conda/config/ fungap_config_copy/
export AUGUSTUS_CONFIG_PATH=${HOME}/fungap_config_copy/
```

So, I'm thinking to modify the `.def` file. I will update and test it once again, and release it.

Thanks for your input! I learned a lot!

**Comment by simonalexanderuw** [comment]
I experience the same issue.
Was the fungap.def updated and released, or an alternative solution recommended?

**Comment by mbnmbn00** [comment]
Can you share what error you see? In the meanwhile, I will check if it works correctly.

**Comment by simonalexanderuw** [comment]
The full error, and file it is being written into are:
`cat braker_Environmental_R.log
#**********************************************************************************
#                               BRAKER CONFIGURATION
#**********************************************************************************
# BRAKER CALL: /opt/conda/bin/braker.pl --fungus --softmasking --cores=32 --genome=/...path.../FunGAP/maker_out/masked_assembly.fasta.adjusted --bam=/...path.../fungap/testing/test03/FunGAP/hisat2_out/Environmental_R.bam --species=Environmental_R --gff3 --AUGUSTUS_CONFIG_PATH=/opt/conda/bin/../config --BAMTOOLS_PATH=/opt/conda/bin --GENEMARK_PATH=/workspace/FunGAP/external/gmes_linux_64_4 --SAMTOOLS_PATH=/opt/conda/bin --workingdir=/...path.../FunGAP/braker_out/Environmental_R --translation_table=1 --AUGUSTUS_BIN_PATH=/opt/conda/bin
# Wed Dec 14 22:01:12 2022: braker.pl version 2.1.5
# Wed Dec 14 22:01:12 2022: Configuring of BRAKER for using external tools...
# Wed Dec 14 22:01:12 2022: Command line flag --AUGUSTUS_CONFIG_PATH was provided. Setting $AUGUSTUS_CONFIG_PATH in braker.pl to /opt/conda/bin/../config.
# Wed Dec 14 22:01:12 2022: ERROR: in file /opt/conda/bin/braker.pl at line 1740
AUGUSTUS_CONFIG_PATH/species (in this case /opt/conda/bin/../config/Environmental_R) is not writeable.
There are 3 alternative ways to set this variable for braker.pl:
   a) provide command-line argument --AUGUSTUS_CONFIG_PATH=/your/path
   b) use an existing environment variable $AUGUSTUS_CONFIG_PATH
      for setting the environment variable, run
           export AUGUSTUS_CONFIG_PATH=/your/path
      in your shell. You may append this to your .bashrc or
      .profile file in order to make the variable available to all
      your bash sessions.
   c) braker.pl can try guessing the location of
      $AUGUSTUS_CONFIG_PATH from an augustus executable that is
      available in your $PATH variable.
      If you try to rely on this option, you can check by typing
           which augustus
      in your shell, whether there is an augustus executable in
      your $PATH
      Be aware: the $AUGUSTUS_CONFIG_PATH must be writable for
                braker.pl because braker.pl is a pipeline that
                optimizes parameters that reside in that
                directory. This might be problematic in case you
                are using a system-wide installed augustus
                installation that resides in a directory that is
                not writable to you as a user`

I've had to shorten the full path with "...path..."

I tried `export AUGUSTUS_CONFIG_PATH=$ALTast_dir/FunGAP` before calling fungap but this not appear to get picker up.

**Comment by pierrj** [comment]
Yeah unfortunately this wasn't working super well for me so I had to change some stuff around. Unfortunately, there just doesn't seem to be a way to conveniently have a file be writeable within a singularity container so I had to copy the directory outside of the container and change `run_braker.py` to look for the `AUGUST_CONFIG_PATH` environmental variable instead.

Here's is the fork where I made those changes:
https://github.com/pierrj/FunGAP/tree/master/docker

Changes are to:
- `docker/fungap.def` - some new instructions, including copying the two items listed below into the singularity container
- `docker/run_braker.py` - modified version is in the docker directory, to be copied into the singularity image
- `docker/external` - directory that needs to be copied into the singularity image

You should be able to just use my branch and follow the regular instructions. Then you just need to set `AUGUSTUS_CONFIG_PATH` to a writeable directory and it should run without issue.

**Comment by mbnmbn00** [comment]
Thanks Pierre for the comment.

I forgot to update the `fungap.def` file after fixing it.
Now I have updated `fungap.def` and `REAME.md` and tested the new version in a fresh Ubuntu and it worked okay.

But either way should be okay as long as you can run without any issues.
Let me know if you have more questions. I will close this issue after you confirm the fix!

**Comment by simonalexanderuw** [comment]
Hi, apologies for the delay, thanks to both of you for the suggestions/updates.

Unfortunately neither solved my issue. BUT, I think it's related to the environment I'm trying to setup in, rather than the code.

Basically we're trying to set this up on a cluster to be used by a number of different users across different projects. We install using owner:group A:A to then be called by a user with owner:group B:C. I _think_ at the moment that the permissions are not being passed down through the python.subprocess command - it's an _idea_ that I haven't been able to fully verify yet.

If I install, via the conda method, in a project's folder (with owner:group B:C) then the sample test runs. We can't use the Singularity method since we can't make this writeable.

Since we can install 'locally' for the different projects then we can get this running.

Thanks for your help with this.

**Comment by mbnmbn00** [comment]
Hello, glad I hear some update from you.

So only issue for Singularity is that the FunGAP (Braker) tries to write something in the program directory.
As Pierre suggested, you can change the directory with some set-ups.
I think `AUGUSTUS_CONFIG_PATH` will help you.

So I guess the conda method works for you?

**Comment by simonalexanderuw** [comment]
Yes, the conda method works. Thanks.
