### ISSUE TITLE
Issue while running Marker

### ISSUE THREAD

**Issue by sommeslag** [CompSynBioLab-KoreaUniv/FunGAP#84]
Hi, 

I’v installed FunGAP using the docker container. While building the image, two errors appeared.
I don’t have the exact error code anymore but it was caused by the fact that the gene mark release that I downloaded was named gmes_linux_64_4.tar.gz instead of gmes_linux_64.tar.gz. I adjusted the Dockerfile to the correct name and the installation went fine after that.

While running FunGAP, I’ve encountered a problem with Marker. The program returned following error and the pipeline stopped running:

`
Possible precedence issue with control flow operator at /opt/conda/envs/maker/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
STATUS: Parsing control files...
ERROR: The 'probuild' file[s] /workspace/FunGAP/external/gmes_linux_64/probuild do not exist.
Please check settings in the control files.
ERROR: The 'gmhmme3' file[s] /workspace/FunGAP/external/gmes_linux_64/gmhmme3 do not exist.
Please check settings in the control files.
ERROR: The HMM file[s] provided for gmhmm do not exist:
	/fungap_workspace/fungap_out/maker_out/genemark_out/output/gmhmm.mod
--> rank=NA, hostname=8c073ef94e1c
`

I’m not really familiar with using Docker containers. Does anyone know what caused this issue and how to fix it? Could it have something to do with the naming of the gene mark release?

Thank you!

Sarah

**Comment by mbnmbn00** [comment]
Hello,

1) `gmes_linux_64_4.tar.gz`: I will update the Docker file. Thank you for letting me know!

2) This error message is ignorable. Something related to BioPerl within Maker.
```
Possible precedence issue with control flow operator at /opt/conda/envs/maker/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805. STATUS: Parsing control files... 
```

3) Okay. I think GeneMark changed their file/directory names. I need to download myself and see the files.
```
/workspace/FunGAP/external/gmes_linux_64/probuild
```
Meanwhile, you can go to the `/workspace/FunGAP/external/` directory and see where the `probuild` located.
I will do it myself and let you know how to fix the issue! Thanks!

**Comment by sommeslag** [comment]
Hi,

Thank you for the answer already!

The `/workspace/FunGAP/external/` directory does not seem to exist, or at least I cannot acces it:


![image](https://user-images.githubusercontent.com/104629243/166438715-66fc33a2-672f-41e3-a1e9-899c53aeeafb.png)


Again, I'm really not an expert at these kind of things.
Could this be part of the problem?

Thank you!

**Comment by mbnmbn00** [comment]
Hello, for that problem, you should use:
```
cd /workspace/FunGAP/external/
```
instead of:
```
cd ./workspace/FunGAP/external/
```
`.` meaning current directory (where you are now).

I will definitely help you until you finish the run, so please send me any errors you encounter.

**Comment by sommeslag** [comment]
Ok, thank you!

Location of the probuild directory:
`/workspace/FunGAP/external/gmes_linux_64_4/probuild`

So, it is indeed just a naming problem (gmes_linux_64_4 instead of gmes_linux_64).

**Comment by mbnmbn00** [comment]
Yes! You can edit `fungap.conf` file to update the path.
Meanwhile, I will try to update the file in the next version.
