### ISSUE TITLE
Transcriptome

### ISSUE THREAD

**Issue by giriarteS** [CompSynBioLab-KoreaUniv/FunGAP#85]
I have several single end rna libraries and the final transcriptome. How can I feed that into FUNGAP to avoid the whole trinity step?

**Comment by mbnmbn00** [comment]
Hello,

Let's say your single-end RNA library is `test_s.fastq`.
Then, your Trinity output name will be: `fungap_out/trinity_out/trinity_test/Trinity_test.fasta`.

- Note that `fungap_out` is the `--output_dir fungap_out` argument that you input.

So create the directories
```
mkdir -p fungap_out/trinity_out/trinity_test/
```
Then, put your transcriptome assembly file as `Trinity_test.fasta`.

You may want to skip the `run_hisat2` stage, too by doing similar thing.
Put your bam file as `fungap_out/hisat2_out/test.bam`.
(If you don't have bam file, you may create an empty file by typing `touch fungap_out/hisat2_out/test.bam`.

This will skip two steps and use the files that you provide.
Let me know if you have any further questions.

**Comment by mbnmbn00** [comment]
(Could you create a new post?)

Unfortunately, FunGAP doesn't support multiple RNA-seq libraries.
However, one library is okay to produce nearly-best output.

But let me know if you want to know how to incorporate gene predictions from multiple libraries.
