### ISSUE TITLE
download_sister_orgs.py

### ISSUE THREAD

**Issue by LiZhihua1982** [CompSynBioLab-KoreaUniv/FunGAP#86]
Hi, when I used the "download_sister_orgs.py"  for example, "/download_sister_orgs.py --taxon "Debaryomyces hansenii" --email_address zhaochiza@163.com --num_sisters 5".  Sometimes it downloaded 3 items while sometimes it downloaded 6 items as below? How we fix it? Do we need re-download the "sister_orgs.list" sister organisms manually? Thanks!

(base) root@fc966344ae2f:/workspace/FunGAP# ./download_sister_orgs.py --taxon "Debaryomyces hansenii" --email_address zhaochiza@163.com --num_sisters 5
Validate input taxon...

===
Taxon: Debaryomyces hansenii
Rank: species
Lineage: cellular organisms; Eukaryota; Opisthokonta; Fungi; Dikarya; Ascomycota; saccharomyceta; Saccharomycotina; Saccharomycetes; Saccharomycetales; CUG-Ser1 clade; Debaryomycetaceae; Debaryomyces
===

Downloading protein sequence files...
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/024/256/405/GCA_024256405.1_ASM2425640v1/*protein.faa.gz
No downloadable file for this entry: GCA_024256405.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/016/097/625/GCA_016097625.1_CAU_DHC11_v01_alt/*protein.faa.gz
No downloadable file for this entry: GCA_016097625.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/016/097/515/GCA_016097515.1_CAU_DHC11_v01_pri/*protein.faa.gz
No downloadable file for this entry: GCA_016097515.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/013/759/195/GCA_013759195.1_ASM1375919v1/*protein.faa.gz
No downloadable file for this entry: GCA_013759195.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/013/759/155/GCA_013759155.1_ASM1375915v1/*protein.faa.gz
No downloadable file for this entry: GCA_013759155.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/006/942/325/GCA_006942325.1_Dha_155/*protein.faa.gz
No downloadable file for this entry: GCA_006942325.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/006/942/305/GCA_006942305.1_Dha_1449/*protein.faa.gz
No downloadable file for this entry: GCA_006942305.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/006/942/225/GCA_006942225.1_Dha_17914/*protein.faa.gz
No downloadable file for this entry: GCA_006942225.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/006/942/235/GCA_006942235.1_Dha_7426/*protein.faa.gz
No downloadable file for this entry: GCA_006942235.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/006/942/215/GCA_006942215.1_Dha_398/*protein.faa.gz
No downloadable file for this entry: GCA_006942215.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/006/942/205/GCA_006942205.1_Dha_j26/*protein.faa.gz
No downloadable file for this entry: GCA_006942205.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/708/665/GCA_003708665.2_ASM370866v2/*protein.faa.gz
No downloadable file for this entry: GCA_003708665.2
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/708/605/GCA_003708605.2_ASM370860v2/*protein.faa.gz
No downloadable file for this entry: GCA_003708605.2
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/708/965/GCA_003708965.1_ASM370896v1/*protein.faa.gz
No downloadable file for this entry: GCA_003708965.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/708/935/GCA_003708935.1_ASM370893v1/*protein.faa.gz
No downloadable file for this entry: GCA_003708935.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/708/665/GCA_003708665.1_ASM370866v1/*protein.faa.gz
No downloadable file for this entry: GCA_003708665.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/708/605/GCA_003708605.1_ASM370860v1/*protein.faa.gz
No downloadable file for this entry: GCA_003708605.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/708/585/GCA_003708585.1_ASM370858v1/*protein.faa.gz
No downloadable file for this entry: GCA_003708585.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/349/505/GCA_003349505.1_ASM334950v1/*protein.faa.gz
No downloadable file for this entry: GCA_003349505.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/900/186/205/GCA_900186205.1_CANPSY1/*protein.faa.gz
No downloadable file for this entry: GCA_900186205.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/682/995/GCA_001682995.1_ASM168299v1/*protein.faa.gz
No downloadable file for this entry: GCA_001682995.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/239/015/GCA_000239015.2_ASM23901v2/*protein.faa.gz
No downloadable file for this entry: GCA_000239015.2
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/239/015/GCA_000239015.1_ASM23901v1/*protein.faa.gz
No downloadable file for this entry: GCA_000239015.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/006/445/GCF_000006445.1_ASM644v1/*protein.faa.gz
No downloadable file for this entry: GCF_000006445.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/182/765/GCA_000182765.1_ASM18276v1/*protein.faa.gz
No downloadable file for this entry: GCA_000182765.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/182/765/GCF_000182765.1_ASM18276v2/*protein.faa.gz
[Run] mv GCF_000182765.1_ASM18276v2_protein.faa.gz /workspace/FunGAP/sister_orgs/GCF_000182765.1_protein.faa.gz
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/708/605/GCA_003708605.2_ASM370860v2/*protein.faa.gz
No downloadable file for this entry: GCA_003708605.2
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/149/445/GCA_000149445.1_ASM14944v1/*protein.faa.gz
No downloadable file for this entry: GCA_000149445.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/020/027/125/GCA_020027125.1_ASM2002712v1/*protein.faa.gz
No downloadable file for this entry: GCA_020027125.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/023/625/715/GCA_023625715.1_ASM2362571v1/*protein.faa.gz
No downloadable file for this entry: GCA_023625715.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/006/942/215/GCA_006942215.1_Dha_398/*protein.faa.gz
No downloadable file for this entry: GCA_006942215.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/017/655/625/GCA_017655625.1_BP57/*protein.faa.gz
[Run] mv GCA_017655625.1_BP57_protein.faa.gz /workspace/FunGAP/sister_orgs/GCA_017655625.1_protein.faa.gz
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/019/280/635/GCA_019280635.1_ASM1928063v1/*protein.faa.gz
No downloadable file for this entry: GCA_019280635.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/024/256/405/GCA_024256405.1_ASM2425640v1/*protein.faa.gz
No downloadable file for this entry: GCA_024256405.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/008/062/615/GCA_008062615.2_ASM806261v2/*protein.faa.gz
No downloadable file for this entry: GCA_008062615.2
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/006/335/GCF_000006335.1_ASM633v1/*protein.faa.gz
No downloadable file for this entry: GCF_000006335.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/900/231/965/GCA_900231965.1_Meycar_Culqui/*protein.faa.gz
No downloadable file for this entry: GCA_900231965.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/023/625/775/GCA_023625775.1_ASM2362577v1/*protein.faa.gz
No downloadable file for this entry: GCA_023625775.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/002/864/075/GCA_002864075.1_CtY66041.0/*protein.faa.gz
No downloadable file for this entry: GCA_002864075.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/015/708/755/GCA_015708755.1_ASM1570875v1/*protein.faa.gz
No downloadable file for this entry: GCA_015708755.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/022/984/785/GCA_022984785.1_ASM2298478v1/*protein.faa.gz
No downloadable file for this entry: GCA_022984785.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/223/485/GCF_000223485.1_Spathaspora_passalidarum_v2.0/*protein.faa.gz
[Run] mv GCF_000223485.1_Spathaspora_passalidarum_v2.0_protein.faa.gz /workspace/FunGAP/sister_orgs/GCF_000223485.1_protein.faa.gz
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/013/759/195/GCA_013759195.1_ASM1375919v1/*protein.faa.gz
No downloadable file for this entry: GCA_013759195.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/015/227/795/GCA_015227795.1_ASM1522779v1/*protein.faa.gz
No downloadable file for this entry: GCA_015227795.1
[Run] wget --quiet -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/023/623/315/GCA_023623315.1_ASM2362331v1/*protein.faa.gz
No downloadable file for this entry: GCA_023623315.1

Done. Check "sister_orgs.list" for downloaded files details

(base) root@fc966344ae2f:/workspace/FunGAP/sister_orgs# ls
GCA_017655625.1_protein.faa.gz	GCF_000182765.1_protein.faa.gz	GCF_001447935.1_protein.faa.gz	sister_orgs.list
GCF_000006445.2_protein.faa.gz	GCF_000223485.1_protein.faa.gz	GCF_001447935.2_protein.faa.gz

**Comment by mbnmbn00** [comment]
Hello,

The reason is that not all NCBI entries have protein sequence files.
I was worried the script runs endlessly, so I limit the number of download attempts up to (num_sisters × 10). If you set `--num_sisters 5` then the script attempts 50 times of download. I think your three files came from that.

The selection of 50 entries are random, so when you run again you got three other files.
The easiest fix will be changing the line 139,
```
    while len(asm_ids) < (num_sisters * 10):
```
Change 10 to 100 or bigger.

If you have 6 files already, you could also delete one and concatenate them.
I will not close yet, but let me know if it helps.

**Comment by LiZhihua1982** [comment]
Hello, 
Thank you very much for your quick reply! I have another two questions, 1: Do concatenate three files or five files will cause to different annotation results? 2: if we want to use the Uniprot protein (for example: https://www.uniprot.org/proteomes/UP000000599), or Mycocosm (https://mycocosm.jgj.doe.gov/mycocosm/home) instead of these protein downloaded from NCBI. is it OK?

**Comment by mbnmbn00** [comment]
1) Yes. But the effect might not be big.

Protein sequences are used in 1) Maker blastx and 2) BLASTp to score each
model.
There will be a higher chance of picking a good model when you use a bigger
(or curated) database.
Because FunGAP also uses other evidence (transcriptome, pfam, and busco),
the effect would be not be that big.

2) Yes! As long as it's a protein FASTA file, it will work. But you also
may consider *computing time*.

Let me know if you have any other questions!

All the Best,
Byoungnam

**Comment by LiZhihua1982** [comment]
Dear Dr.Byoungnam,
    Thank you very much!

Best regards

Li Zhihua

________________________________
发件人: mbnmbn00 ***@***.***>
发送时间: 2022年7月29日 1:07
收件人: CompSynBioLab-KoreaUniv/FunGAP ***@***.***>
抄送: Li Zhihua ***@***.***>; Author ***@***.***>
主题: Re: [CompSynBioLab-KoreaUniv/FunGAP] download_sister_orgs.py (Issue #86)


1) Yes. But the effect might not be big.

Protein sequences are used in 1) Maker blastx and 2) BLASTp to score each
model.
There will be a higher chance of picking a good model when you use a bigger
(or curated) database.
Because FunGAP also uses other evidence (transcriptome, pfam, and busco),
the effect would be not be that big.

2) Yes! As long as it's a protein FASTA file, it will work. But you also
may consider *computing time*.

Let me know if you have any other questions!

All the Best,
Byoungnam

―
