### ISSUE TITLE
RepeatModeler issue

### ISSUE THREAD

**Issue by shaobinzhong** [CompSynBioLab-KoreaUniv/FunGAP#88]
I tried to test run FunGAP again, but have error for running the RepeatModeler. The out.log is shown below. Please help.
============ New Run 2022-09-02 15:01:03.026664 ============
[09-02 15:01] START: wrapper_run_hisat2
[Wrapper] /mmfs1/projects/shaobin.zhong/FUNGAP2/FunGAP-master/run_hisat2.py --read_files CocheC5_EST_all_1.fastq CocheC5_EST_all_2.fastq --output_dir /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/hisat2_out --log_dir /mmfs1/projects/shaobin.zho
ng/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/logs --ref_fasta /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/Cochliobolus_heterostrophus_C5.fasta --num_cores 12 --max_intron 2000
[09-02 15:01] START: Hisat2
[Note] Running hisat2-build has already been finished
[Run] /mmfs1/projects/shaobin.zhong/anaconda3/envs/fungap2/bin/hisat2 --max-intronlen 2000 -p 12 -x /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/Cochliobolus_heterostrophus_C5.fasta -1 /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/CocheC5_EST_all_1.fastq -2 /mmfs
1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/CocheC5_EST_all_2.fastq 2> /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/logs/hisat2_CocheC5_EST_all.log | /mmfs1/projects/shaobin.zhong/anaconda3/envs/fungap2/bin/samtools view -bSF4 - | /mmfs1/pr
ojects/shaobin.zhong/anaconda3/envs/fungap2/bin/samtools sort - -o /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/hisat2_out/CocheC5_EST_all.bam
[09-02 15:01] DONE : Hisat2
[09-02 15:01] DONE : wrapper_run_hisat2

[09-02 15:01] START: wrapper_run_trinity
[Wrapper] /mmfs1/projects/shaobin.zhong/FUNGAP2/FunGAP-master/run_trinity.py --bam_files /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/hisat2_out/CocheC5_EST_all.bam --output_dir /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output
_CocheC5_BC2/trinity_out --log_dir /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/logs --num_cores 12 --max_intron 2000 --jaccard_clip
[09-02 15:01] START: Trinity for CocheC5_EST_all
[Run] /mmfs1/projects/shaobin.zhong/anaconda3/envs/fungap2/bin/Trinity --jaccard_clip --genome_guided_bam /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/hisat2_out/CocheC5_EST_all.bam --genome_guided_max_intron 2000 --max_memory 10G --CPU 12 --o
utput /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/trinity_out/trinity_CocheC5_EST_all > /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/logs/trinity_CocheC5_EST_all.log 2>&1
[09-02 15:09] DONE : Trinity for CocheC5_EST_all
[09-02 15:09] DONE : wrapper_run_trinity

[09-02 15:09] START: wrapper_run_repeat_modeler
[Wrapper] /mmfs1/projects/shaobin.zhong/FUNGAP2/FunGAP-master/run_repeat_modeler.py --genome_assembly /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/Cochliobolus_heterostrophus_C5.fasta --output_dir /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC
5_BC2/repeat_modeler_out --log_dir /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/logs --num_cores 12
[09-02 15:09] START running RepeatModeler
[Run] /mmfs1/projects/shaobin.zhong/anaconda3/envs/fungap2/bin/BuildDatabase -name /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/Cochliobolus_heterostrophus_C5.fasta /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/Cochliobolus_heterostrophus_C5.fasta > /mmfs1/projec
ts/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/logs/build_database.log 2>&1
[Run] /mmfs1/projects/shaobin.zhong/anaconda3/envs/fungap2/bin/RepeatModeler -database /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/Cochliobolus_heterostrophus_C5.fasta -pa 12 > /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/logs/repeat_m
odeler.log 2>&1
[09-02 15:58] DONE  running RepeatModeler
[ERROR] RepeatModeler has finished abnormally. There is no consensi.fa.classified file.
Check input files...
TRANS_READ_FILES is ok...
GENOME_ASSEMBLY is ok...
SISTER_PROTEOME is ok...
BUSCO_DATASET is ok...

Traceback (most recent call last):
  File "/mmfs1/projects/shaobin.zhong/FUNGAP2/FunGAP-master/fungap.py", line 839, in <module>
    main()
  File "/mmfs1/projects/shaobin.zhong/FUNGAP2/FunGAP-master/fungap.py", line 192, in main
    repeat_model_file = run_repeat_modeler(
  File "/mmfs1/projects/shaobin.zhong/FUNGAP2/FunGAP-master/fungap.py", line 420, in run_repeat_modeler
    check_call(command_args)
  File "/mmfs1/projects/shaobin.zhong/anaconda3/envs/fungap2/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mmfs1/projects/shaobin.zhong/FUNGAP2/FunGAP-master/run_repeat_modeler.py', '--genome_assembly', '/mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/Cochliobolus_heterostrophus_C5.fasta', '--output_dir', '/mmfs1/projects/shaobin.zhon
g/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/repeat_modeler_out', '--log_dir', '/mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/logs', '--num_cores', '12']' returned non-zero exit status 2.

**Comment by mbnmbn00** [comment]
Hello,

Could you upload the below file?
```
/mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/logs/repeat_m
odeler.log
```

I recommend running the FunGAP with the `Saccharomyces` test data before the actual runs.

**Comment by shaobinzhong** [comment]
Here are the logs:
[repeat_modeler.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/9481358/repeat_modeler.log)
[run_repeat_modeler.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/9481359/run_repeat_modeler.log)

**Comment by mbnmbn00** [comment]
Okay. I think I have experience similar to this.
https://github.com/rmhubley/RepeatModeler/issues/9

If you see `consensi.fa` and `families.stk` files, you may run `RepeatClassifier` to finish the RepeatModeler run.

```
$PATH_TO_REOEAT_MODELER;RepeatModeler-open-1.0.11/RepeatClassifier \
  -consensi consensi.fa \
  -stockholm families.stk
```

Those files could be located here:
```
/mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/repeat_modeler_out/RM_2231650.FriSep21509152022
```

In the meanwhile, I recommend running with test dataset to confirm it's a data-specific error, not FunGAP error.

**Comment by shaobinzhong** [comment]
I have the same issue with the Saccharomyces test data. Then I run RepeatClassifier:

RepeatClassifier  \
-consensi /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap2_test_output1/repeat_modeler_out/RM_2742663.FriSep161655362022/consensi.fa \
-stockholm /mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap2_test_output1/repeat_modeler_out/RM_2742663.FriSep161655362022/families.stk

and I got the following message:
[shaobin.zhong@login0004 FUNGAP_DIR_2021_12_23]$ more RepeatModeler_RepeatClassifier.o255349
No database indicated or it is an empty file.

**Comment by mbnmbn00** [comment]
I also found this:
http://avrilomics.blogspot.com/2015/02/finding-repeats-using-repeatmodeler.html

I see the same error message as yours.
It seems you can resolve this if you can install RepeatModeler via GitHub.

I will test RepeatModeler myself on fresh Ubuntu and let you know.

**Comment by mbnmbn00** [comment]
I just installed and tested RepeatModeler, and it worked fine.
This is how I checked in a fresh Ubuntu (I used Amazon EC2).

*1. Anaconda3 v4.14*

```
wget https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-x86_64.sh
bash Anaconda3-2022.05-Linux-x86_64.sh
```

*2. Install RepeatModeler*

```
conda create -y -n fungap
conda activate fungap
conda install micromamba -c conda-forge
micromamba install repeatmodeler=2.0.1 -c bioconda -c conda-forge
```

*3. Download RepeatMasker databases*

```
conda activate fungap
cd $(dirname $(which RepeatMasker))/../share/RepeatMasker
echo -e "\n2\n$(dirname $(which rmblastn))\n\n5\n" > tmp && ./configure < tmp
```

*4. Download test dataset*

```
wget ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/146/045/GCF_000146045.2_R64/GCF_000146045.2_R64_genomic.fna.gz
gunzip GCF_000146045.2_R64_genomic.fna.gz
```

*5. Run RepeatModeler*

```
RepeatModeler --version  # 2.0.1
ASSEMBLY=GCF_000146045.2_R64_genomic.fna
BuildDatabase -name ${ASSEMBLY} ${ASSEMBLY} > builddatabase.log
RepeatModeler -database ${ASSEMBLY} -pa 4 > repeatmodeler.log
```

I also attach the [repeatmodeler.log](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/9620579/repeatmodeler.log) file.

Hope it helps your test. It took not much time, so please follow the procedure and test on your machine.

**Comment by shaobinzhong** [comment]
Thank you so much for your help! We reinstalled RepeatModeler according to your procedure. I am testing the pipeline and will let you know how it works.

**Comment by yangverse** [comment]
Hi, 

Thank you for the help! I am with shaobinzhong. We still get the issue after the reinstallation. I find there is a non-empty consensi.fa file in round-1 output. But the consensi.fa becomes empty since round-2, and the ncResults...err file has the below errors:

`Warning: Query_2: Cannot resolve lcl|Query_2: unknown
Error: Failed to resolve SeqId: lcl|Query_2
Error: NCBI C++ Exception:
    T0 "/opt/conda/conda-bld/blast_1658184301332/work/blast/c++/src/algo/blast/format/blast_format.cpp", line 1473: Error: (CException::eUnknown) BLASTFORMAT::ncbi::CBlastFormat::PrintOneResultSet() - Failed to resolve SeqId: lcl|Query_2`

Is it a problem?

Thanks.

**Comment by mbnmbn00** [comment]
Hmm

1) Which OS are you using? (we tested it on Ubuntu)
2) Can you configure the RepeatMasker manually? (was there some error when you configured it?)
```
conda activate fungap
cd $(dirname $(which RepeatMasker))/../share/RepeatMasker
./configure
# Then follow the instruction of RepeatMasker
```
3) If anything doesn't work, Docker or Singularity seems the only option for us.
https://github.com/CompSynBioLab-KoreaUniv/FunGAP/tree/master/docker
But note you need superuser permission to install and run Docker.

4) If you are using non-Ubuntu, you may install it from the source code and compile it yourself.
https://github.com/Dfam-consortium/RepeatModeler

If you succeed in installing & testing the RepeatModeler, let me know how to configure the FunGAP.

**Comment by shaobinzhong** [comment]
Okay thank you very much for your help. I will take your recommendation to do the the test run. Shaobin

Sent from my iPhone

On Sep 2, 2022, at 7:09 PM, mbnmbn00 ***@***.***> wrote:

﻿

Okay. I think I have experience similar to this.
Dfam-consortium/RepeatModeler#9<https://github.com/Dfam-consortium/RepeatModeler/issues/9>

If you see consensi.fa and families.stk files, you may run RepeatClassifier to finish the RepeatModeler run.

$PATH_TO_REOEAT_MODELER;RepeatModeler-open-1.0.11/RepeatClassifier \
  -consensi consensi.fa \
  -stockholm families.stk


Those files could be located here:

/mmfs1/projects/shaobin.zhong/FUNGAP_DIR_2021_12_23/fungap_output_CocheC5_BC2/repeat_modeler_out/RM_2231650.FriSep21509152022


In the meanwhile, I recommend running with test dataset to confirm it's a data-specific error, not FunGAP error.
