### ISSUE TITLE
problem with the example BUSCO dataset

### ISSUE THREAD

**Issue by krostifangers** [CompSynBioLab-KoreaUniv/FunGAP#91]
Hello
I just installed FunGAP. I performed the configuration test, and everything worked well. 
However, when I tried to run the example on Saccharomyces, running the following command-line : 
```
$FUNGAP_DIR/fungap.py  \
  --genome_assembly GCF_000146045.2_R64_genomic.fna \
  --trans_read_1 SRR1198667_1.fastq \
  --trans_read_2 SRR1198667_2.fastq \
  --augustus_species saccharomyces_cerevisiae_S288C \
  --busco_dataset ascomycota_odb10 \
  --sister_proteome prot_db.faa \
  --num_cores 8
```
I get the following message : 
[ERROR] Invalid BUSCO DATASET: ascomycota_odb10. Run busco --list-datasets to get a full list available datasets
I do not understand as I already have the ascomycota_odb10 folder in the FunGAP directory. 
I tried to search for the BUSCO binary in my fungap env, but only found a script name "busco" to run busco.
So, what should I do?
I am working on debian 11.
All the best
Christophe

**Comment by mbnmbn00** [comment]
I just installed from the scratch and didn't get that error.

**Check your BUSCO installation**

FunGAP first runs `busco --list-datasets` and same the output.
Then, it checks if your input is included in the list of BUSCO databases.

So, if you failed to run `busco --list-datasets` then you might get the error you have got.
One way to check is to run:
```bash
conda activate fungap
which busco  # it should be same with the path in the fungap.conf file
busco --list-datasets
```

If it doesn't work, let me know. I will try to find another way to check it.

**Comment by krostifangers** [comment]
Hi
Thank you for answering me so quickly.
In fact, when I run busco --list-datasets I get nothing. 
I checked busco installation with the code you provided me, and the busco installation is the same as the one in fungap.conf
 (/home/krostif/miniconda/envs/fungap/bin/busco). How can I configure busco in order to make it get the ascomycota_odb10 dataset?
Thank you in advance
Christophe

**Comment by mbnmbn00** [comment]
How about this?
```bash
> busco --version
BUSCO 5.4.3
```

I think older BUSCO doesn't have the option.
You have to see something like this:
```
busco --list-datasets
2023-01-04 15:32:49 INFO:	Downloading information on latest versions of BUSCO data...
2023-01-04 15:32:53 INFO:	Downloading file 'https://busco-data.ezlab.org/v5/data/information/lineages_list.2021-12-14.txt.tar.gz'
2023-01-04 15:32:54 INFO:	Decompressing file '/tools/FunGAP/busco_downloads/information/lineages_list.2021-12-14.txt.tar.gz'
```

**Comment by krostifangers** [comment]
Hi
I reinstalled everything from scratch, but I just changed busco version (busco 5.4.3) and everything worked well.
So thank you for your advices
All the best
Krostif

**Comment by mbnmbn00** [comment]
Glad to hear that!!

* Could you click the "star" button to support this program?

**Comment by cfz1998** [comment]
> 

Hi！ @mbnmbn00 
I got the same error! But i alreadly have the BUSCO 5.4.4. Could I using the local database for BUSCO? I think it's straightly way.

**Comment by cfz1998** [comment]
![image](https://user-images.githubusercontent.com/60096719/219952405-347191ea-ffd6-4a00-b821-bbb9be0c025b.png)
I commented out the lines in check_inputs.py and using global path for busco_db.

**Comment by mbnmbn00** [comment]
Thanks. Glad you could tweak the program.

**Comment by MANaranjo** [comment]
Hi,

I had a similar problem. It seems that check_input.py is checking the available datasets assuming they end in "obd10", but newer versions of BUSCO have odb12 already. I modified the line:

busco_dbs = re.findall(r'\S+_odb10', output)

to

busco_dbs = re.findall(r'\S+_odb12', output)

And it now works fine.

Hope this comment might be helpful to someone out there (or myself in a couple of months)!

**Comment by JatinKaushik7827** [comment]
Hii,

I  have installed FunGAP using singularity image and trying to run it. 
The command is as follows:
"singularity exec --writable ${FUNGAP_DIR}/docker/sandbox /workspace/FunGAP/fungap.py   --output_dir s_hep_assembly   --trans_read_1 SRR29464655_1.fastq   --trans_read_2 SRR29464655_2.fastq   --genome_assembly s_hep_assembly.fa    --augustus_species fusarium_graminearum    --sister_proteome prot_db.faa    --num_cores 36   --busco_dataset ascomycota_odb12" 
and getting similar error: "[ERROR] Invalid BUSCO DATASET: ascomycota_odb10. Run busco --list-datasets to get a full list available datasets"

The command busco --v gives: BUSCO 5.6.0

Can someone help figuring out what's the root cause?

Thanks in advance
Jatin

**Comment by mbnmbn00** [comment]
Hi, I will look at the error soon. It sounds like I need to update some codes.
