### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by amoltej** [CompSynBioLab-KoreaUniv/FunGAP#92]
can someone please help to resolve following installation error?

Thanks
Amol
![image](https://user-images.githubusercontent.com/17108522/213949211-5023e36b-02c1-4f78-993d-29b2c2972be9.png)

**Comment by mbnmbn00** [comment]
The message indicates that you don't have `gmes_linux_64_4.tar.gz` file.
Download `gmes_linux_64_4.tar.gz` and `gm_key_64.gz` and put it in the `docker` directory.

**Comment by amoltej** [comment]
This is how my docker Dir looks
![image](https://user-images.githubusercontent.com/17108522/213962505-f3267638-c939-46f0-945a-c86e87e3abf9.png)

**Comment by mbnmbn00** [comment]
Can you edit the Docerfile line 6? from
```
COPY gmes_linux_64.tar.gz /workspace/FunGAP/external/
```
to
```
COPY gmes_linux_64_4.tar.gz /workspace/FunGAP/external/
```

Sorry. This must to be a bug or I made some mistake here. I will tag @lmtani who wrote the script to get some help.

**Comment by amoltej** [comment]
That worked! 
Thanks Heaps 

Amol

**Comment by mbnmbn00** [comment]
Glad you resolved the issue. If you don't mind, could you click the star button? So people get more attention for this program.
