### ISSUE TITLE
./fungap.py  returned non-zero exit status 1.

### ISSUE THREAD

**Issue by LiZhihua1982** [CompSynBioLab-KoreaUniv/FunGAP#93]
(base) root@065b09900fc1:/workspace/FunGAP# ./fungap.py --genome_assembly /data/HR3_assembly_flye.fasta --trans_read_1 /data/RNA_seq/fastp_out/HR301_1.fastq --trans_read_2 /data/RNA_seq/fastp_out/HR301_2.fastq --augustus_species debaryomyces_hansenii --busco_dataset ascomycota_odb10 --sister_proteome /data/prot_db.faa --num_cores 8 --output_dir fungap_HR3_out/

============ New Run 2023-02-17 11:40:57.775759 ============
Check input files...
TRANS_READ_FILES is ok...
GENOME_ASSEMBLY is ok...
SISTER_PROTEOME is ok...
BUSCO_DATASET is ok...

[02-17 11:41] START: wrapper_run_hisat2
[Wrapper] /workspace/FunGAP/run_hisat2.py --read_files /data/RNA_seq/fastp_out/HR301_1.fastq /data/RNA_seq/fastp_out/HR301_2.fastq --output_dir /workspace/FunGAP/fungap_HR3_out/hisat2_out --log_dir /workspace/FunGAP/fungap_HR3_out/logs --ref_fasta /data/HR3_assembly_flye.fasta --num_cores 8 --max_intron 2000
[02-17 11:41] START: Hisat2
[Run] /opt/conda/bin/hisat2-build -p 8 /data/HR3_assembly_flye.fasta /data/HR3_assembly_flye.fasta > /workspace/FunGAP/fungap_HR3_out/logs/hisat2-build.log 2>&1
[Note] Running Hisat2 has already been finished for HR301
[02-17 11:41] DONE : Hisat2
[02-17 11:41] DONE : wrapper_run_hisat2

[02-17 11:41] START: wrapper_run_trinity
[Wrapper] /workspace/FunGAP/run_trinity.py --bam_files /workspace/FunGAP/fungap_HR3_out/hisat2_out/HR301.bam --output_dir /workspace/FunGAP/fungap_HR3_out/trinity_out --log_dir /workspace/FunGAP/fungap_HR3_out/logs --num_cores 8 --max_intron 2000 --jaccard_clip
[02-17 11:41] START: Trinity for HR301
[Run] /opt/conda/bin/Trinity --jaccard_clip --genome_guided_bam /workspace/FunGAP/fungap_HR3_out/hisat2_out/HR301.bam --genome_guided_max_intron 2000 --max_memory 10G --CPU 8 --output /workspace/FunGAP/fungap_HR3_out/trinity_out/trinity_HR301 > /workspace/FunGAP/fungap_HR3_out/logs/trinity_HR301.log 2>&1
Traceback (most recent call last):
  File "/workspace/FunGAP/run_trinity.py", line 160, in <module>
    main()
  File "/workspace/FunGAP/run_trinity.py", line 97, in main
    run_trinity(
  File "/workspace/FunGAP/run_trinity.py", line 149, in run_trinity
    os.rename(trinity_output, new_output)
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/FunGAP/fungap_HR3_out/trinity_out/trinity_HR301/Trinity-GG.fasta' -> '/workspace/FunGAP/fungap_HR3_out/trinity_out/trinity_HR301/Trinity_HR301.fasta'
Traceback (most recent call last):
  File "./fungap.py", line 839, in <module>
    main()
  File "./fungap.py", line 188, in main
    trinity_asms = run_trinity(
  File "./fungap.py", line 393, in run_trinity
    check_call(command_args)
  File "/opt/conda/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/workspace/FunGAP/run_trinity.py', '--bam_files', '/workspace/FunGAP/fungap_HR3_out/hisat2_out/HR301.bam', '--output_dir', '/workspace/FunGAP/fungap_HR3_out/trinity_out', '--log_dir', '/workspace/FunGAP/fungap_HR3_out/logs', '--num_cores', '8', '--max_intron', '2000', '--jaccard_clip']' returned non-zero exit status 1.

**Comment by mbnmbn00** [comment]
Trinity seems to have failed to run.

Can you send me this directory?

```
/workspace/FunGAP/fungap_HR3_out/logs/
```

Or 

```
/workspace/FunGAP/fungap_HR3_out/logs/trinity_HR301.log
```

It seems you ran the pipeline twice.
```
[Note] Running Hisat2 has already been finished for HR301
```

Can you double-check Hisat2 ran properly? I.e., BAM file produced correctly?

**Comment by LiZhihua1982** [comment]
Thank you very much!
I have fixed this problem. Because my assembly genome with long characters after > in the fasta format. I have changed it in one word that can work.

**Comment by mbnmbn00** [comment]
Okay. That's good to know! I may update the code to check if the input FASTA file has too long names.
