### ISSUE TITLE
mpirun

### ISSUE THREAD

**Issue by cfz1998** [CompSynBioLab-KoreaUniv/FunGAP#95]
Could FunGAP support mpirun for maker? The maker process is so slower.
``` shell
mpirun -n num_cores maker
```

**Comment by cfz1998** [comment]
There are some errors in this code.
![image](https://user-images.githubusercontent.com/60096719/220223463-47868a91-73cd-4e9f-9855-cc055e49939b.png)
These executables are not always in the dir of the maker.

**Comment by mbnmbn00** [comment]
Thanks for suggestion.
If you look at `maker_opts.ctl` file, there's an option called `cpus=`, and FunGAP changes this number to user-provided one.

Do you think `mpirun` makes it run faster than putting the number in `cpus=`?
If you do, I definitely check that out and update the code.

**Comment by cfz1998** [comment]
In other cases (like plant genome), *mpirun* may run faster than putting the number in *cpus=*. But this may introduces some configuration file issues. 

And i think the codes in the run_maker.py line 466 -472 may cause an exception. For me, the path of  *blastn* not in "os.path.dirname(maker_bin)". I think it would be better to change it to this
``` python
    # Program paths
    for program in [
            'makeblastdb', 'blastn', 'blastx', 'tblastx', 'RepeatMasker',
            'exonerate', 'snap', 'augustus', 'tRNAscan-SE', 'snoscan']:
        replace('maker_exe.ctl', '{}='.format(program), '{}={}'.format(
            program, D_CONF[program.upper()+"_PATH"]
        ))
```

**Comment by mbnmbn00** [comment]
Thanks. I have updated the code!
Let me know if you have further questions!!
